/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpClientRequestConfig } from '../type';
import BaseSpotterApiSdk from '../base-api-sdk';
import { ResponseResultListCooperationAmazonAccountAccountVOModel } from '../model';

/**
 * AccountApi - object-oriented interface
 * @export
 * @class AccountApi
 * @extends {BaseSpotterApiSdk}
 */
export class SpotterAccountApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
     * 获取所有运营账号信息
     * @summary 获取所有运营账号信息
     * @param {*} [options] Override http request option.
     * @memberof AccountApi
     */
    async all(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListCooperationAmazonAccountAccountVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-cooperation-web/amazon/account/all',
        });
    }
}
