/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
import BaseSpotterApiSdk from '../base-api-sdk';
import { JobOperatorReqModel } from '../model';
import { JobPageReqModel } from '../model';
import { ResponseResultBooleanModel } from '../model';
import { ResponseResultExportJobInfoVoModel } from '../model';
import { ResponseResultExportTemplateUploadVOModel } from '../model';
import { ResponseResultListBusinessLineVOModel } from '../model';
import { ResponseResultPageVOJobPageVOModel } from '../model';
import { ResponseResultStringModel } from '../model';
import { StorageJobSubmitReqModel } from '../model';

/**
 * Request parameters for _delete operation in GmeshExportApi.
 * @export
 * @interface GmeshExportApiDeleteRequest
 * @extend {JobOperatorReqModel}
 */
export type GmeshExportApiDeleteRequest = JobOperatorReqModel;

/**
 * Request parameters for download operation in GmeshExportApi.
 * @export
 * @interface GmeshExportApiDownloadRequest
 * @extend {JobOperatorReqModel}
 */
export type GmeshExportApiDownloadRequest = JobOperatorReqModel;

/**
 * Request parameters for page operation in GmeshExportApi.
 * @export
 * @interface GmeshExportApiPageRequest
 * @extend {JobPageReqModel}
 */
export type GmeshExportApiPageRequest = JobPageReqModel;

/**
 * Request parameters for query operation in GmeshExportApi.
 * @export
 * @interface GmeshExportApiQueryRequest
 */
export interface GmeshExportApiQueryRequest {
    readonly evidence?: string;
}

/**
 * Request parameters for submit operation in GmeshExportApi.
 * @export
 * @interface GmeshExportApiSubmitRequest
 * @extend {StorageJobSubmitReqModel}
 */
export type GmeshExportApiSubmitRequest = StorageJobSubmitReqModel;

/**
 * Request parameters for uploadTemplate operation in GmeshExportApi.
 * @export
 * @interface GmeshExportApiUploadTemplateRequest
 */
export type GmeshExportApiUploadTemplateRequest = FormData;

/**
 * GmeshExportApi - object-oriented interface
 * @export
 * @class GmeshExportApi
 * @extends {BaseSpotterApiSdk}
 */
export class SpotterGmeshExportApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
     * -导出中心列表-删除
     * @summary -导出中心列表-删除
     * @param {GmeshExportApiDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @memberof GmeshExportApi
     */
    async _delete(
        requestParameters: GmeshExportApiDeleteRequest,
        options?: HttpClientRequestConfig,
    ) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/export/job/delete',
            data: requestParameters,
        });
    }
    /**
     * 所属业务线
     * @summary 获取业务线
     * @param {*} [options] Override http request option.
     * @memberof GmeshExportApi
     */
    async businessLine(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListBusinessLineVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-storage-web/export/job/businessLine',
        });
    }
    /**
     * 获取临时授权的 URL .
     * @summary -导出中心列表-下载
     * @param {GmeshExportApiDownloadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @memberof GmeshExportApi
     */
    async download(
        requestParameters: GmeshExportApiDownloadRequest,
        options?: HttpClientRequestConfig,
    ) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/export/job/download',
            data: requestParameters,
        });
    }
    /**
     * -导出中心列表
     * @summary -导出中心列表
     * @param {GmeshExportApiPageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @memberof GmeshExportApi
     */
    async page(requestParameters: GmeshExportApiPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOJobPageVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/export/job/page',
            data: requestParameters,
        });
    }
    /**
     * 凭证查询
     * @summary 凭证查询
     * @param {GmeshExportApiQueryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @memberof GmeshExportApi
     */
    async query(requestParameters: GmeshExportApiQueryRequest, options?: HttpClientRequestConfig) {
        const params = {} as any;
        if (requestParameters?.evidence !== undefined) {
            params['evidence'] = requestParameters?.evidence;
        }
        return this.httpClient.request<ResponseResultExportJobInfoVoModel>({
            ...options,
            method: 'GET',
            url: '/spotter-storage-web/export/job/query',
            params: requestParameters,
        });
    }
    /**
     * 任务提交
     * @summary 任务提交
     * @param {GmeshExportApiSubmitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @memberof GmeshExportApi
     */
    async submit(
        requestParameters: GmeshExportApiSubmitRequest,
        options?: HttpClientRequestConfig,
    ) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/export/job/submit',
            data: requestParameters,
        });
    }
    /**
     * 模版上传
     * @summary 模版上传
     * @param {GmeshExportApiUploadTemplateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @memberof GmeshExportApi
     */
    async uploadTemplate(
        requestParameters: GmeshExportApiUploadTemplateRequest,
        options?: HttpClientRequestConfig,
    ) {
        return this.httpClient.request<ResponseResultExportTemplateUploadVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/export/job/upload',
            data: requestParameters,
        });
    }
}
