/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpClientRequestConfig } from '../type';
import BaseSpotterApiSdk from '../base-api-sdk';
import { ResponseResultListWarehouseCommonBaseCompanyStorageVOModel } from '../model';
import { WarehouseCommonBaseStorageCompanyQueryRequestModel } from '../model';

/**
 * Request parameters for storageList operation in SevcApi.
 * @export
 * @interface SevcApiStorageListRequest
 * @extend {WarehouseCommonBaseStorageCompanyQueryRequestModel}
 */
export type SevcApiStorageListRequest = WarehouseCommonBaseStorageCompanyQueryRequestModel;

/**
 * SevcApi - object-oriented interface
 * @export
 * @class SevcApi
 * @extends {BaseSpotterApiSdk}
 */
export class SpotterSevcApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
     * 获取仓库列表,可根据公司id查，也可模糊查询
     * @summary 获取仓库列表,可根据公司id查，也可模糊查询
     * @param {SevcApiStorageListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @deprecated
     * @memberof SevcApi
     */
    async storageList(
        requestParameters: SevcApiStorageListRequest,
        options?: HttpClientRequestConfig,
    ) {
        return this.httpClient.request<ResponseResultListWarehouseCommonBaseCompanyStorageVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-warehouse-web/company/storage/storage/list',
            data: requestParameters,
        });
    }
}
