/* tslint:disable */
/* eslint-disable */
/**
 * Api SwaggerJson
 * 此文件由Spotter DevTools生成，请勿手动修改
 *
 * The version of the OpenAPI document: 1732084753814
 * Contact: william.duan@spotterio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
import { ResponseResultListSupplierBaseListVOModel } from '../model';
import { ResponseResultListSupplierInfoVOModel } from '../model';
import { SupplierBaseListSearchReqModel } from '../model';
import { SupplierWebSupplierSupplierListSearchRequestModel } from '../model';

/**
 * Request parameters for baseList operation in SupplierApi.
 * @export
 * @interface SupplierApiBaseListRequest
 * @extend {SupplierBaseListSearchReqModel}
 */
export type SupplierApiBaseListRequest = SupplierBaseListSearchReqModel;

/**
 * Request parameters for list operation in SupplierApi.
 * @export
 * @interface SupplierApiListRequest
 * @extend {SupplierWebSupplierSupplierListSearchRequestModel}
 */
export type SupplierApiListRequest = SupplierWebSupplierSupplierListSearchRequestModel;

/**
 * SupplierApi - object-oriented interface
 * @export
 * @class SupplierApi
 * @extends {BaseSpotterApiSdk}
 */
export class SpotterSupplierApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
     * 供应商基础信息列表查询-不区分渠道站点
     * @summary 供应商基础信息列表查询-不区分渠道站点
     * @param {SupplierApiBaseListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @memberof SupplierApi
     */
    async baseList(
        requestParameters: SupplierApiBaseListRequest,
        options?: HttpClientRequestConfig,
    ) {
        return this.httpClient.request<ResponseResultListSupplierBaseListVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-supplier-web/supplier/base/list',
            data: requestParameters,
        });
    }
    /**
     * 供应商列表查询
     * @summary 供应商列表查询
     * @param {SupplierApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @memberof SupplierApi
     */
    async list(requestParameters: SupplierApiListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListSupplierInfoVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-supplier-web/supplier/list',
            data: requestParameters,
        });
    }
}
