/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 
 * @export
 * @interface AddressInfoQueryRequestModel
 */
export interface AddressInfoQueryRequestModel {
    /**
     * 主键id
     * @type {number}
     * @memberof AddressInfoQueryRequestModel
     */
    'id'?: number;
    /**
     * 状态：0-废弃 1-启用
     * @type {string}
     * @memberof AddressInfoQueryRequestModel
     */
    'status'?: string;
    /**
     * 收件人名称
     * @type {string}
     * @memberof AddressInfoQueryRequestModel
     */
    'contact'?: string;
    /**
     * 展示条数
     * @type {number}
     * @memberof AddressInfoQueryRequestModel
     */
    'pageSize': number;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof AddressInfoQueryRequestModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 地址code
     * @type {string}
     * @memberof AddressInfoQueryRequestModel
     */
    'addressCode'?: string;
    /**
     * 当前页数
     * @type {number}
     * @memberof AddressInfoQueryRequestModel
     */
    'currentPage': number;
    /**
     * 地址类型
     * @type {Array<string>}
     * @memberof AddressInfoQueryRequestModel
     */
    'addressTypes'?: Array<string>;
}

