/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BtrBTRDetailOfferSKUVOModel } from './btr-btrdetail-offer-skuvomodel';

/**
 * 订单详情
 * @export
 * @interface BtrBTRDetailOfferVOModel
 */
export interface BtrBTRDetailOfferVOModel {
    /**
     * 订单状态
     * @type {string}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'status': string;
    /**
     * 订单Id
     * @type {string}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'offerId': string;
    /**
     * 销售数量
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'unitSold': number;
    /**
     * 订单名称
     * @type {string}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'offerName': string;
    /**
     * 账号马甲,此offer中的sSKU所属的SVC账号
     * @type {string}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'accountCode': string;
    /**
     * 创建时间
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'createdAtMs': number;
    /**
     * 最早发货日期
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'windowStart': number;
    /**
     * 此offer中所有sSKU售出产品件数的和 / 所有sSKU责任商供应数量之和
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'unitSoldPercent': number;
    /**
     * 接受产品
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'acceptedProducts': number;
    /**
     * 接受数量
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'acceptedQuantity': number;
    /**
     * 总滞销费
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'diyRetentionFees': number;
    /**
     * 提供产品
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'submittedProducts': number;
    /**
     * sSkus信息
     * @type {Array<BtrBTRDetailOfferSKUVOModel>}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'btrDetailOfferSKUVOList': Array<BtrBTRDetailOfferSKUVOModel>;
    /**
     * 提供数量
     * @type {number}
     * @memberof BtrBTRDetailOfferVOModel
     */
    'customerSubmittedQuantity': number;
}

