/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 确认详情 订单详情 单条sku详情
 * @export
 * @interface BtrBTRAffirmDetailSKUVOModel
 */
export interface BtrBTRAffirmDetailSKUVOModel {
    /**
     * ASIN
     * @type {string}
     * @memberof BtrBTRAffirmDetailSKUVOModel
     */
    'asin': string;
    /**
     * sSku
     * @type {string}
     * @memberof BtrBTRAffirmDetailSKUVOModel
     */
    'ssku': string;
    /**
     * 产品名称
     * @type {string}
     * @memberof BtrBTRAffirmDetailSKUVOModel
     */
    'itemName': string;
    /**
     * 制造商建议零售价
     * @type {number}
     * @memberof BtrBTRAffirmDetailSKUVOModel
     */
    'listPrice': number;
    /**
     * 提供数量
     * @type {number}
     * @memberof BtrBTRAffirmDetailSKUVOModel
     */
    'customerSubmittedQuantity': number;
}

