/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 提交的sSku信息
 * @export
 * @interface BTRCreateSKUReqModel
 */
export interface BTRCreateSKUReqModel {
    /**
     * 
     * @type {string}
     * @memberof BTRCreateSKUReqModel
     */
    'ssku'?: string;
    /**
     * 提供数量
     * @type {number}
     * @memberof BTRCreateSKUReqModel
     */
    'customerSubmittedQuantity': number;
}

