/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 获取Item列表
 * @export
 * @interface CatalogOfferOfferItemActiveListAllVOModel
 */
export interface CatalogOfferOfferItemActiveListAllVOModel {
    /**
     * ASIN
     * @type {string}
     * @memberof CatalogOfferOfferItemActiveListAllVOModel
     */
    'asin': string;
    /**
     * sSKU
     * @type {string}
     * @memberof CatalogOfferOfferItemActiveListAllVOModel
     */
    'ssku': string;
    /**
     * 筛选状态 200可以被选择 1000515 已存在「处理中」的BTR订单，状态变更后操作 1000516 已存在「已生效」的BTR订单，状态变更后操作
     * @type {number}
     * @memberof CatalogOfferOfferItemActiveListAllVOModel
     */
    'status': number;
    /**
     * 名称
     * @type {string}
     * @memberof CatalogOfferOfferItemActiveListAllVOModel
     */
    'itemName': string;
    /**
     * 制造商建议零售价
     * @type {number}
     * @memberof CatalogOfferOfferItemActiveListAllVOModel
     */
    'listPrice': number;
    /**
     * 装箱数量
     * @type {number}
     * @memberof CatalogOfferOfferItemActiveListAllVOModel
     */
    'itemsPerInnerPack': number;
}

