/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 产品概览(romerx)
 * @export
 * @interface CooperationProductRProductSummaryVOModel
 */
export interface CooperationProductRProductSummaryVOModel {
    /**
     * 产品id
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'id': number;
    /**
     * 最高平均价格, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'map': number;
    /**
     * 商品统一代码, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'upc': number;
    /**
     * 产品ID-亚马逊标准标识码
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'asin': string;
    /**
     * 产品ID-用户自定义sku
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'msku': string;
    /**
     * 制造商建议零售价
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'msrp': number;
    /**
     * 产品ID-Spotter产品唯一表示
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'ssku': string;
    /**
     * VC报价协议-采购价
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'price': number;
    /**
     * 品牌id
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'brandId': number;
    /**
     * 利润测算-$，关税（海关关税）
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'dutyTax': number;
    /**
     * 产品属性-产品型号
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'modelNo': string;
    /**
     * VC报价协议-折扣，百分比
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'discount': number;
    /**
     * 利润测算-$，产品的成本，即货值-Item Cost
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'itemCost': number;
    /**
     * VC报价协议-品牌损失率
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'brandLost': number;
    /**
     * 品牌名
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'brandName': string;
    /**
     * 公司id
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'companyId': number;
    /**
     * 利润测算-$，其他成本
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'otherCost': number;
    /**
     * 品牌方在SC销售时产品的退货率,百分比, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'returnRate': number;
    /**
     * 外箱宽度, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'cartonWidth': number;
    /**
     * 历史销售数据, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'historySale': number;
    /**
     * 是否需要填写有效期与生产批号(0:否 1是)
     * @type {boolean}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'needBatchNo': boolean;
    /**
     * 产品名称
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'productName': string;
    /**
     * 外箱高度, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'cartonHeight': number;
    /**
     * 外箱长度, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'cartonLength': number;
    /**
     * 外箱重量, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'cartonWeight': number;
    /**
     * 仓储报价协议-免仓租期
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'freeLeaseDays': number;
    /**
     * 亚马逊一级类目node_id
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'primaryNodeId': number;
    /**
     * 产品线id
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'productLineId': number;
    /**
     * 利润测算-$，推广花费（ 含广告费，推广营销费用等）
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'promotionCost': number;
    /**
     * 利润测算-$，从中国到美国的运费-The freight fee
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'cnUsFreightFee': number;
    /**
     * 产品编码
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'productBarcode': string;
    /**
     * 产品属性-类目名称
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'primaryNodeName': string;
    /**
     * 产品属性-类型（产品线）
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'productLineName': string;
    /**
     * 利润测算记录id
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'profitMeasureId': number;
    /**
     * VC报价协议-编号
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'vcAgreementCode': string;
    /**
     * VC后台invoice cost
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'catalogCostPrice': number;
    /**
     * 产品包装宽度, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'itemPackageWidth': number;
    /**
     * 上次修改时间，毫秒时间戳
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'lastModifyTimeMs': number;
    /**
     * 利润测算-$，产品非推广类的总成本（含货值，物流，关税，仓储）
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'productTotalCost': number;
    /**
     * 利润测算-百分比，推广费费率
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'promotionFeeRate': number;
    /**
     * SC配送费, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'scFulfillmentFee': number;
    /**
     * 利润测算-百分比，推广期间对应的利润率
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'grossProfitMargin': number;
    /**
     * 产品包装高度, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'itemPackageHeight': number;
    /**
     * 产品包装长度, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'itemPackageLength': number;
    /**
     * 产品包装重量, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'itemPackageWeight': number;
    /**
     * 装箱数量, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'itemsPerInnerPack': number;
    /**
     * 危险品代码
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'dangerousGoodsCode': string;
    /**
     * 如果latestVCCustomerAgreementStatus为rejected，那么该字段返回拒绝原因
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'latestRejectReason': string;
    /**
     * SC平台费, 列表不需要展示，编辑弹窗使用
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'scReferralFreeRate': number;
    /**
     * 利润测算-百分比，广告花费费率-Advertising Cost Rate
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'advertisingCostRate': number;
    /**
     * 是否危险品,dangerous:危险品,not_dangerous:不是危险品
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'dangerousGoodsOrNot': string;
    /**
     * 产品所属最新一条协议id
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'latestVcAgreementId': number;
    /**
     * 仓储报价协议-编号
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'storageAgreementCode': string;
    /**
     * 是否效期产品,expiration_date_product:效期产品,not_expiration_date_product:非效期产品
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'expirationDateProduct': string;
    /**
     * 生效中的仓储报价协议
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'storageFeeAgreementId': number;
    /**
     * 该产品是否创建catalog offer，已创建：true，未创建：false
     * @type {boolean}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'existCatalogOfferOrNot': boolean;
    /**
     * 生效中的VC报价协议
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'vcQuotationAgreementId': number;
    /**
     * 仓储报价协议-每箱仓储费
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'vcpoFulfillmentFeePerCase': number;
    /**
     * 仓储报价协议-每件仓储费
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'vcpoFulfillmentFeePerPiece': number;
    /**
     * 产品所属最新一条协议状态,用户侧包装状态
     * @type {string}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'latestVCCustomerAgreementStatus': string;
    /**
     * 仓储报价协议-折后每箱仓储费
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'discountVcpoFulfillmentFeePerCase': number;
    /**
     * 仓储报价协议-折后每件配送费
     * @type {number}
     * @memberof CooperationProductRProductSummaryVOModel
     */
    'discountVcpoFulfillmentFeePerPiece': number;
}

