/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 亚马逊账号查询参数
 * @export
 * @interface CooperationAmazonAccountAccountSearchRequestModel
 */
export interface CooperationAmazonAccountAccountSearchRequestModel {
    /**
     * 主键id
     * @type {number}
     * @memberof CooperationAmazonAccountAccountSearchRequestModel
     */
    'id'?: number;
    /**
     * 公司id
     * @type {number}
     * @memberof CooperationAmazonAccountAccountSearchRequestModel
     */
    'companyId'?: number;
    /**
     * VC账号在SEVC的名称，给客户看的马甲
     * @type {string}
     * @memberof CooperationAmazonAccountAccountSearchRequestModel
     */
    'accountCode'?: string;
    /**
     * 关键词
     * @type {string}
     * @memberof CooperationAmazonAccountAccountSearchRequestModel
     */
    'likeAccountCode'?: string;
}

