/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 产品信息概览（romerx）
 * @export
 * @interface CooperationProductRProductSummaryPageSearchRequestModel
 */
export interface CooperationProductRProductSummaryPageSearchRequestModel {
    /**
     * 品牌id
     * @type {number}
     * @memberof CooperationProductRProductSummaryPageSearchRequestModel
     */
    'brandId'?: number;
    /**
     * 查询关键字，支持产品名称/产品型号/sSKU/MSKU/ASIN
     * @type {string}
     * @memberof CooperationProductRProductSummaryPageSearchRequestModel
     */
    'keyword'?: string;
    /**
     * 展示条数
     * @type {number}
     * @memberof CooperationProductRProductSummaryPageSearchRequestModel
     */
    'pageSize': number;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof CooperationProductRProductSummaryPageSearchRequestModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 当前页数
     * @type {number}
     * @memberof CooperationProductRProductSummaryPageSearchRequestModel
     */
    'currentPage': number;
    /**
     * 产品线id
     * @type {number}
     * @memberof CooperationProductRProductSummaryPageSearchRequestModel
     */
    'productLineId'?: number;
    /**
     * 产品是否存在生效中的VC报价协议
     * @type {boolean}
     * @memberof CooperationProductRProductSummaryPageSearchRequestModel
     */
    'isExistActiveVCAgreement'?: boolean;
    /**
     * 最近一次VC报价协议状态（用户包装VC协议状态）
     * @type {string}
     * @memberof CooperationProductRProductSummaryPageSearchRequestModel
     */
    'latestCustomerVCAgreementStatus'?: string;
}

