/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * spt物流新增-商品信息
 * @export
 * @interface EssSevcOrderDetailReqModel
 */
export interface EssSevcOrderDetailReqModel {
    /**
     * asin
     * @type {string}
     * @memberof EssSevcOrderDetailReqModel
     */
    'asin'?: string;
    /**
     * msku
     * @type {string}
     * @memberof EssSevcOrderDetailReqModel
     */
    'msku'?: string;
    /**
     * ssku
     * @type {string}
     * @memberof EssSevcOrderDetailReqModel
     */
    'ssku': string;
    /**
     * 序号
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'index'?: number;
    /**
     * 外箱高
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'boxHigh': number;
    /**
     * 发货箱数
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'cartons': number;
    /**
     * 外箱宽
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'boxWidth': number;
    /**
     * 总件数
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'totalNum'?: number;
    /**
     * 外箱长
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'boxLength': number;
    /**
     * 外箱重量
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'boxWeight': number;
    /**
     * 每箱件数
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'innerPack': number;
    /**
     * 
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'singleHigh'?: number;
    /**
     * 产品名称
     * @type {string}
     * @memberof EssSevcOrderDetailReqModel
     */
    'productName'?: string;
    /**
     * 
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'singleWidth'?: number;
    /**
     * 
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'storageType'?: number;
    /**
     * 
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'singleLength'?: number;
    /**
     * 
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'singleWeight'?: number;
    /**
     * 产品码
     * @type {string}
     * @memberof EssSevcOrderDetailReqModel
     */
    'productBarcode': string;
    /**
     * 有效期
     * @type {number}
     * @memberof EssSevcOrderDetailReqModel
     */
    'effectiveDateMs'?: number;
    /**
     * 收货海外仓
     * @type {string}
     * @memberof EssSevcOrderDetailReqModel
     */
    'receivingStorageCode': string;
}

