/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EssSevcOrderDetailReqModel } from './ess-sevc-order-detail-req-model';

/**
 * spt物流新增
 * @export
 * @interface EssSevcOrderAddReqModel
 */
export interface EssSevcOrderAddReqModel {
    /**
     * 仓库类型(1自发仓 2云仓 3自营仓)
     * @type {number}
     * @memberof EssSevcOrderAddReqModel
     */
    'storageType': number;
    /**
     * 商品信息
     * @type {Array<EssSevcOrderDetailReqModel>}
     * @memberof EssSevcOrderAddReqModel
     */
    'orderDetailReqList': Array<EssSevcOrderDetailReqModel>;
}

