/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 角色列表单条信息
 * @export
 * @interface GuardWebRoleRoleListOneVOModel
 */
export interface GuardWebRoleRoleListOneVOModel {
    /**
     * 角色Id
     * @type {number}
     * @memberof GuardWebRoleRoleListOneVOModel
     */
    'id': number;
    /**
     * 角色代号
     * @type {string}
     * @memberof GuardWebRoleRoleListOneVOModel
     */
    'code': string;
    /**
     * 角色名称
     * @type {string}
     * @memberof GuardWebRoleRoleListOneVOModel
     */
    'name': string;
    /**
     * 公司Id
     * @type {number}
     * @memberof GuardWebRoleRoleListOneVOModel
     */
    'companyId': number;
    /**
     * 0可以删除1不可以删除
     * @type {number}
     * @memberof GuardWebRoleRoleListOneVOModel
     */
    'isUndeletable': number;
}

