/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户信息(简易数据)
 * @export
 * @interface GuardWebUserUserSimpleVOModel
 */
export interface GuardWebUserUserSimpleVOModel {
    /**
     * 用户Id
     * @type {string}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'id': string;
    /**
     * 用户名称 (展示使用)
     * @type {string}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'name': string;
    /**
     * 用户邮箱
     * @type {string}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'email': string;
    /**
     * 部门id
     * @type {number}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'orgId': number;
    /**
     * 电话
     * @type {string}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'phone': string;
    /**
     * 用户头像
     * @type {string}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'avatar': string;
    /**
     * 用户状态 -1:冻结 1:启用2:待激活
     * @type {number}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'status': number;
    /**
     * 飞书用户id
     * @type {string}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'feishuId': string;
    /**
     * 微信用户id
     * @type {string}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'wechatId': string;
    /**
     * 公司Id
     * @type {number}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'companyId': number;
    /**
     * 创建时间
     * @type {string}
     * @memberof GuardWebUserUserSimpleVOModel
     */
    'createdAt': string;
}

