/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OfferItemActiveListAllReqModel
 */
export interface OfferItemActiveListAllReqModel {
    /**
     * 展示条数
     * @type {number}
     * @memberof OfferItemActiveListAllReqModel
     */
    'pageSize': number;
    /**
     * 当前页数
     * @type {number}
     * @memberof OfferItemActiveListAllReqModel
     */
    'currentPage': number;
}

