/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * （分页）业务id关联日志查询
 * @export
 * @interface OperationOperationSearchPageRequestModel
 */
export interface OperationOperationSearchPageRequestModel {
    /**
     * 业务id
     * @type {string}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'bizId': string;
    /**
     * 操作动作类型
     * @type {string}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'action'?: string;
    /**
     * 日志返回语言，中文：zh_CN，英文：en_US，不传默认英文
     * @type {string}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'locale'?: string;
    /**
     * 操作执行结果
     * @type {string}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'result'?: string;
    /**
     * 业务类型
     * @type {string}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'bizType'?: string;
    /**
     * 传空或false，仅返回当前登录用户所属公司的操作日志，为true返回所有
     * @type {boolean}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'showAll'?: boolean;
    /**
     * 展示条数
     * @type {number}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'pageSize': number;
    /**
     * 操作人id
     * @type {string}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'operatorId'?: string;
    /**
     * 当前页数
     * @type {number}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'currentPage': number;
    /**
     * 操作时间查询，左区间
     * @type {number}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'leftOperationTimeMs'?: number;
    /**
     * 操作时间查询，右区间
     * @type {number}
     * @memberof OperationOperationSearchPageRequestModel
     */
    'rightOperationTimeMs'?: number;
}

