/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MoneyDTOModel } from './money-dtomodel';
// May contain unused imports in some cases
// @ts-ignore
import { OrderMultichannelCommodityPackageVOModel } from './order-multichannel-commodity-package-vomodel';

/**
 * 产品信息视图
 * @export
 * @interface OrderFulfillmentProductVOModel
 */
export interface OrderFulfillmentProductVOModel {
    /**
     * 履约单号
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'foNo': string;
    /**
     * MSKU
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'msku': string;
    /**
     * sSKU
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'ssku': string;
    /**
     * 渠道订单号
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'pltNo': string;
    /**
     * 系统订单号
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'sptNo': string;
    /**
     * 箱数
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'boxNum': number;
    /**
     * pltSku
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'pltSku': string;
    /**
     * 状态
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'status': string;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'brandName': string;
    /**
     * 公司ID
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'companyId': number;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderFulfillmentProductVOModel
     */
    'costPrice': MoneyDTOModel;
    /**
     * 装箱数量
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'innerPack': number;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderFulfillmentProductVOModel
     */
    'totalPrice': MoneyDTOModel;
    /**
     * 公司编码
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'companyCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'companyName': string;
    /**
     * 下单时间
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'orderedOnMs': number;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'productName': string;
    /**
     * 发货仓库编码
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'storageCode': string;
    /**
     * 发货仓库名称
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'storageName': string;
    /**
     * 渠道订单名称
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'pltOrderName': string;
    /**
     * 邮件发送状态
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'emailSendFlag': number;
    /**
     * 实际到达日期
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'actualArrivedMs': number;
    /**
     * 下单数量
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'orderedQuantity': number;
    /**
     * 实际发货日期
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'actualShippingMs': number;
    /**
     * 接单数量
     * @type {number}
     * @memberof OrderFulfillmentProductVOModel
     */
    'confirmedQuantity': number;
    /**
     * 0 不需要换标、1 需要换标
     * @type {string}
     * @memberof OrderFulfillmentProductVOModel
     */
    'changeProLabelFlag': string;
    /**
     * 商品装箱信息
     * @type {Array<OrderMultichannelCommodityPackageVOModel>}
     * @memberof OrderFulfillmentProductVOModel
     */
    'commodityPackageList': Array<OrderMultichannelCommodityPackageVOModel>;
}

