/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 待客户处理视图
 * @export
 * @interface OrderMultichannelPendingPageVOModel
 */
export interface OrderMultichannelPendingPageVOModel {
    /**
     * 预计提货时间
     * @type {number}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'frd': number;
    /**
     * 销售订单号
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'pltNo': string;
    /**
     * 公司ID
     * @type {number}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'companyId': number;
    /**
     * 订单类型:FBA、MO
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'orderType': string;
    /**
     * 运输类型:SP、LTL
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'transType': string;
    /**
     * 失败原因
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'failReason': string;
    /**
     * 异常状态:logistics_error、attach_not_upload
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'failStatus': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'companyCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'companyName': string;
    /**
     * 订单创建日期
     * @type {number}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'orderedOnMs': number;
    /**
     * 发货仓库
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'storageCode': string;
    /**
     * 发货仓库
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'storageName': string;
    /**
     * 销售订单号名称
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'pltOrderName': string;
    /**
     * 面单获取方式-是否SPT提供面单:0-否、1-是
     * @type {string}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'sptLabelFlag': string;
    /**
     * 待上传附件列表:attachShippingLabel、attachBol、attachBoxLabel、attachProductLabel
     * @type {Array<string>}
     * @memberof OrderMultichannelPendingPageVOModel
     */
    'pendingUploadAttachList': Array<string>;
}

