/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CheckResultModel } from './check-result-model';

/**
 * 批量预校验附件结果
 * @export
 * @interface OrderMultichannelPreCheckAttachVOModel
 */
export interface OrderMultichannelPreCheckAttachVOModel {
    /**
     * 是否全部校验通过
     * @type {boolean}
     * @memberof OrderMultichannelPreCheckAttachVOModel
     */
    'success': boolean;
    /**
     * 校验结果
     * @type {Array<CheckResultModel>}
     * @memberof OrderMultichannelPreCheckAttachVOModel
     */
    'checkResultList': Array<CheckResultModel>;
}

