/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * spt order详细信息查询
 * @export
 * @interface OrderB2bSptOrderDetailQueryModel
 */
export interface OrderB2bSptOrderDetailQueryModel {
    /**
     * spt订单号
     * @type {string}
     * @memberof OrderB2bSptOrderDetailQueryModel
     */
    'sptNo': string;
}

