/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * Gmesh亚马逊订单分页req
 * @export
 * @interface OrderPoAmzOrderPageReqGmeshModel
 */
export interface OrderPoAmzOrderPageReqGmeshModel {
    /**
     * sa订单号
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'saCode'?: string;
    /**
     * 亚马逊订单号
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'amzCode'?: string;
    /**
     * ASIN/sSKU/产品名称的模糊查询
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'keyword'?: string;
    /**
     * 异常订单 1:到货异常；2：系统拒单
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'unusual'?: number;
    /**
     * 预计提货时间终止
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'frdEndMs'?: number;
    /**
     * 展示条数
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'pageSize': number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'brandName'?: string;
    /**
     * 公司id
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'companyId'?: number;
    /**
     * 订单类型:PO订单；DI订单；PO-BBO订单
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'orderType'?: string;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 亚马逊BBO询盘订单提交状态：NEW 未提交,EXECUTING 提交中,SUCCESS 已提交
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'subStatus'?: string;
    /**
     * 截止时间
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'deadlineMs'?: number;
    /**
     * 预计提货时间起始
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'frdStartMs'?: number;
    /**
     * vendor code
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'vendorCode'?: string;
    /**
     * 当前页数
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'currentPage': number;
    /**
     * 订单状态
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'orderStatus'?: string;
    /**
     * 发货仓库
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'storageCode'?: string;
    /**
     * 最晚发货时间
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'windowEndMs'?: number;
    /**
     * 亚马逊实际接单状态：AC:接单,OS:本次不接单,CP:本次不接单且不需要继续来单
     * @type {string}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'confirmStatus'?: string;
    /**
     * 最早发货时间
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'windowStartMs'?: number;
    /**
     * 订单下单-搜索结束时间
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'orderedOnEndMs'?: number;
    /**
     * vendor code列表
     * @type {Array<string>}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'vendorCodeList'?: Array<string>;
    /**
     * 订单状态
     * @type {Array<string>}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'orderStatusList'?: Array<string>;
    /**
     * 账号经理
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'accountManagerId'?: number;
    /**
     * external id异常状态: 0:正常,1:异常
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'externalIdStatus'?: number;
    /**
     * 订单下单-搜索开始时间
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'orderedOnStartMs'?: number;
    /**
     * 是否发送过shipment：0：没有，1：有
     * @type {number}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'shipmentSendFlag'?: number;
    /**
     * shipment异常状态
     * @type {Array<number>}
     * @memberof OrderPoAmzOrderPageReqGmeshModel
     */
    'shipmentUnusualStatus'?: Array<number>;
}

