/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 请求结果数据
 * @export
 * @interface OrderSaveVOModel
 */
export interface OrderSaveVOModel {
    /**
     * ASIN
     * @type {string}
     * @memberof OrderSaveVOModel
     */
    'asin': string;
    /**
     * MSKU
     * @type {string}
     * @memberof OrderSaveVOModel
     */
    'msku': string;
    /**
     * sSKU
     * @type {string}
     * @memberof OrderSaveVOModel
     */
    'ssku': string;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderSaveVOModel
     */
    'productName': string;
    /**
     * catalog装箱数量
     * @type {number}
     * @memberof OrderSaveVOModel
     */
    'catalogInnerPack': number;
    /**
     * 上传装箱数量
     * @type {number}
     * @memberof OrderSaveVOModel
     */
    'currentInnerPack': number;
    /**
     * 商务上报装箱数量
     * @type {number}
     * @memberof OrderSaveVOModel
     */
    'productInnerPack': number;
}

