/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 缺货看板查询
 * @export
 * @interface OrderFulfillmentFulfillmentLackQueryReqModel
 */
export interface OrderFulfillmentFulfillmentLackQueryReqModel {
    /**
     * ASIN/sSKU/产品名称的模糊查询
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackQueryReqModel
     */
    'keyword'?: string;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackQueryReqModel
     */
    'brandName'?: string;
    /**
     * 公司ID
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentLackQueryReqModel
     */
    'companyId'?: number;
    /**
     * 账号经理ID
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackQueryReqModel
     */
    'accountManagerId'?: string;
    /**
     * 要求发货仓库编码
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackQueryReqModel
     */
    'originStorageCode'?: string;
}

