/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MoneyDTOModel } from './money-dtomodel';

/**
 * 履约明细
 * @export
 * @interface OrderB2bFulfillDetailPageVOModel
 */
export interface OrderB2bFulfillDetailPageVOModel {
    /**
     * 预计提货时间
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'frd': number;
    /**
     * 履约订单号
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'foNo': string;
    /**
     * MSKU
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'msku': string;
    /**
     * sSKU
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'ssku': string;
    /**
     * PO订单号
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'pltNo': string;
    /**
     * SA订单号
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'sptNo': string;
    /**
     * ucode
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'ucode': string;
    /**
     * 平台SKU
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'pltSku': string;
    /**
     * 收货地
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'shipTo': string;
    /**
     * 订单状态
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'status': string;
    /**
     * 数据版本号
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'version': number;
    /**
     * 品牌
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'brandName': string;
    /**
     * 公司ID
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'companyId': number;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'costPrice': MoneyDTOModel;
    /**
     * 装箱数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'innerPack': number;
    /**
     * 订单类型:PO、PO-BBO、DI
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'orderType': string;
    /**
     * UPC/EAN
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'productId': string;
    /**
     * 产品子状态
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'subStatus': string;
    /**
     * 最晚发货日期
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'windowEnd': number;
    /**
     * 编辑结果
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'editResult': string;
    /**
     * External Id
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'externalId': string;
    /**
     * 产品失败状态
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'failStatus': string;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'totalPrice': MoneyDTOModel;
    /**
     * Vendor Code
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'accountCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'companyCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'companyName': string;
    /**
     * 订单创建日期
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'orderedOnMs': number;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'productName': string;
    /**
     * 发货仓库编码
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'storageCode': string;
    /**
     * 发货仓库名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'storageName': string;
    /**
     * 最早发货日期
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'windowStart': number;
    /**
     * PO订单名
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'pltOrderName': string;
    /**
     * 是否已经解冻
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'unfreezeFlag': string;
    /**
     * 产品接单状态
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'productStatus': string;
    /**
     * 实际到达日期
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'actualArrivedMs': number;
    /**
     * 倒计时
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'countDownTimeMs': number;
    /**
     * VC账号
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'mainAccountName': string;
    /**
     * 采购数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'orderedQuantity': number;
    /**
     * 实际发货日期
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'actualShippingMs': number;
    /**
     * 实际接单数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'confirmedQuantity': number;
    /**
     * 产品扩展异常标识：0-正常，1-异常
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'externalIdExpFlag': string;
    /**
     * 账号经理
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'accountManagerName': string;
    /**
     * BBO类型，且未二次确认
     * @type {boolean}
     * @memberof OrderB2bFulfillDetailPageVOModel
     */
    'bboNotSecondConfirm': boolean;
}

