/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SEVC亚马逊BTR订单导出Req
 * @export
 * @interface OrderOrderAmzBtrExportReqModel
 */
export interface OrderOrderAmzBtrExportReqModel {
    /**
     * gmesh导出标识：传true代表导出代办列表，false代表导出全部列表
     * @type {boolean}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'todo'?: boolean;
    /**
     * 订单状态列表
     * @type {Array<string>}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'status'?: Array<string>;
    /**
     * 订单名称
     * @type {string}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'offerName'?: string;
    /**
     * ssku/asin模糊搜索
     * @type {string}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'searchKey'?: string;
    /**
     * 订单id
     * @type {string}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'amazonOfferId'?: string;
    /**
     * 创建时间截止
     * @type {number}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'createdAtEndMs'?: number;
    /**
     * 账号经理id
     * @type {number}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'accountManagerId'?: number;
    /**
     * 创建时间开始
     * @type {number}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'createdAtStartMs'?: number;
    /**
     * 当前审批人id
     * @type {number}
     * @memberof OrderOrderAmzBtrExportReqModel
     */
    'currentManagerId'?: number;
}

