/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderB2bConfirmDetailReqModel } from './order-b2b-confirm-detail-req-model';

/**
 * 确认请求
 * @export
 * @interface OrderB2bConfirmReqModel
 */
export interface OrderB2bConfirmReqModel {
    /**
     * spt订单号
     * @type {string}
     * @memberof OrderB2bConfirmReqModel
     */
    'sptNo'?: string;
    /**
     * 接单明细
     * @type {Array<OrderB2bConfirmDetailReqModel>}
     * @memberof OrderB2bConfirmReqModel
     */
    'confirmDetailList'?: Array<OrderB2bConfirmDetailReqModel>;
}

