/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderPoOrderAmzInventoryVOModel } from './order-po-order-amz-inventory-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { OrderPoOrderAmzItemDetailVOModel } from './order-po-order-amz-item-detail-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { OrderPoOrderAmzItemShipmentVOModel } from './order-po-order-amz-item-shipment-vomodel';

/**
 * SEVC亚马逊订单VO
 * @export
 * @interface OrderPoOrderAmzSevcVOModel
 */
export interface OrderPoOrderAmzSevcVOModel {
    /**
     * id
     * @type {number}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'id': number;
    /**
     * asin
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'asin': string;
    /**
     * sSku
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'ssku': string;
    /**
     * 产品标题
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'title': string;
    /**
     * sa订单号
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'saCode': string;
    /**
     * UPC/EAN
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'upcEan': string;
    /**
     * bbo成本价
     * @type {number}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'bboCost': number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'brandName': string;
    /**
     * 装箱数量
     * @type {number}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'innerPack': number;
    /**
     * 订单类型:PO；DI
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'orderType': string;
    /**
     * External Id
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'externalId': string;
    /**
     * 预计接单数量
     * @type {number}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'maxQuantity': number;
    /**
     * 订单状态:NEW,PENDING,ACKNOWLEDGED,CLOSED
     * @type {string}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'orderStatus': string;
    /**
     * 下单时间
     * @type {number}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'orderedOnMs': number;
    /**
     * 库存信息VO列表
     * @type {Array<OrderPoOrderAmzInventoryVOModel>}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'inventoryList': Array<OrderPoOrderAmzInventoryVOModel>;
    /**
     * 亚马逊订单商品详情VO列表
     * @type {Array<OrderPoOrderAmzItemDetailVOModel>}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'itemDetailList': Array<OrderPoOrderAmzItemDetailVOModel>;
    /**
     * 采购数量
     * @type {number}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'orderedQuantity': number;
    /**
     * External ID状态：0:正常，1：异常\'
     * @type {number}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'externalIdStatus': number;
    /**
     * 亚马逊订单商品&物流信息VO列表
     * @type {Array<OrderPoOrderAmzItemShipmentVOModel>}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'itemShipmentList': Array<OrderPoOrderAmzItemShipmentVOModel>;
    /**
     * 实际接单数量
     * @type {number}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'confirmedQuantity': number;
    /**
     * 二次确认标记
     * @type {boolean}
     * @memberof OrderPoOrderAmzSevcVOModel
     */
    'secondConfirmedFlag': boolean;
}

