/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * SEVC亚马逊订单导出Req
 * @export
 * @interface OrderPoAmzOrderExportReqSevcModel
 */
export interface OrderPoAmzOrderExportReqSevcModel {
    /**
     * sa订单号
     * @type {string}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'saCode'?: string;
    /**
     * ASIN/sSKU/产品名称的模糊查询
     * @type {string}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'keyword'?: string;
    /**
     * 展示条数
     * @type {number}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'pageSize': number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'brandName'?: string;
    /**
     * 订单类型:PO订单；DI订单；PO-BBO订单
     * @type {string}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'orderType'?: string;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 导出类型 1-新订单｜2-全部订单
     * @type {number}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'exportType': number;
    /**
     * 当前页数
     * @type {number}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'currentPage': number;
    /**
     * 订单状态
     * @type {string}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'orderStatus'?: string;
    /**
     * 最晚发货时间
     * @type {number}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'windowEndMs'?: number;
    /**
     * 订单类型:PO订单；DI订单；PO-BBO订单
     * @type {Array<string>}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'orderTypeList'?: Array<string>;
    /**
     * 最早发货时间
     * @type {number}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'windowStartMs'?: number;
    /**
     * 订单下单-搜索结束时间
     * @type {number}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'orderedOnEndMs'?: number;
    /**
     * 订单状态:New:待确认  Pending:处理中  Acknowledged:已确认
     * @type {Array<string>}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'orderStatusList'?: Array<string>;
    /**
     * 订单下单-搜索开始时间
     * @type {number}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'orderedOnStartMs'?: number;
    /**
     * 是否发送过shipment：0：没有，1：有
     * @type {number}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'shipmentSendFlag'?: number;
    /**
     * 0:未接单 1:已接单
     * @type {boolean}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'orderReceivedStatus'?: boolean;
    /**
     * 二次确认标记
     * @type {boolean}
     * @memberof OrderPoAmzOrderExportReqSevcModel
     */
    'secondConfirmedFlag'?: boolean;
}

