/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 重新发货
 * @export
 * @interface OrderMultichannelShipReqModel
 */
export interface OrderMultichannelShipReqModel {
    /**
     * 履约详情code
     * @type {Array<string>}
     * @memberof OrderMultichannelShipReqModel
     */
    'ucodeList': Array<string>;
}

