/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 履约明细页面分页请求
 * @export
 * @interface OrderB2bFulfillDetailPageQueryModel
 */
export interface OrderB2bFulfillDetailPageQueryModel {
    /**
     * 订单状态
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'status'?: string;
    /**
     * MSKU/sSKU/产品名称的模糊查询
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'keyword'?: string;
    /**
     * 履约订单号列表
     * @type {Array<string>}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'foNoList'?: Array<string>;
    /**
     * 预计提货日期-结束
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'frdMsEnd'?: number;
    /**
     * 展示条数
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'pageSize': number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'brandName'?: string;
    /**
     * 公司id
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'companyId'?: number;
    /**
     * 订单类型
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'orderType'?: string;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 系统订单号列表
     * @type {Array<string>}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'sptNoList'?: Array<string>;
    /**
     * 订单子状态
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'subStatus'?: string;
    /**
     * 预计提货日期-开始
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'frdMsStart'?: number;
    /**
     * 订单状态列表
     * @type {Array<string>}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'statusList'?: Array<string>;
    /**
     * Vendor Code
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'accountCode'?: string;
    /**
     * 当前页数
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'currentPage': number;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'storageCode'?: string;
    /**
     * 异常订单标
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'exceptionTag'?: string;
    /**
     * 待自动创建出库单
     * @type {boolean}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'noFailStatus'?: boolean;
    /**
     * 订单类型列表
     * @type {Array<string>}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'orderTypeList'?: Array<string>;
    /**
     * 销售订单号列表
     * @type {Array<string>}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'pltOrderNames'?: Array<string>;
    /**
     * 产品接单状态
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'productStatus'?: string;
    /**
     * 
     * @type {Array<SortQueryModel>}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'sortQueryList'?: Array<SortQueryModel>;
    /**
     * 订单失败状态列表
     * @type {Array<string>}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'failStatusList'?: Array<string>;
    /**
     * 订单创建日期-结束
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'orderedOnMsEnd'?: number;
    /**
     * 最晚发货日期-结束
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'windowEndMsEnd'?: number;
    /**
     * VC账号
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'mainAccountCode'?: string;
    /**
     * 账号经理
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'accountManagerId'?: number;
    /**
     * 订单创建日期-开始
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'orderedOnMsStart'?: number;
    /**
     * 最晚发货日期-开始
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'windowEndMsStart'?: number;
    /**
     * 最早发货日期-结束
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'windowStartMsEnd'?: number;
    /**
     * 实际到达日期-结束
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'actualArrivedMsEnd'?: number;
    /**
     * 最早发货日期-开始
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'windowStartMsStart'?: number;
    /**
     * 实际发货日期-结束
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'actualShippingMsEnd'?: number;
    /**
     * 实际到达日期-开始
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'actualArrivedMsStart'?: number;
    /**
     * 实际发货日期-开始
     * @type {number}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'actualShippingMsStart'?: number;
    /**
     * bbo二次确认:0 未二次确认，1 已二次确认
     * @type {string}
     * @memberof OrderB2bFulfillDetailPageQueryModel
     */
    'bboSecondConfirmStatus'?: string;
}

