/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderB2bFulfillDetailSimpleVOModel } from './order-b2b-fulfill-detail-simple-vomodel';

/**
 * spt order详细信息
 * @export
 * @interface OrderB2bSptOrderDetailVOModel
 */
export interface OrderB2bSptOrderDetailVOModel {
    /**
     * msku
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'msku': string;
    /**
     * ssku
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'ssku': string;
    /**
     * spt订单号
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'sptNo': string;
    /**
     * 渠道sku
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'pltSku': string;
    /**
     * 品牌
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'brandName': string;
    /**
     * 订单类型
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'orderType': string;
    /**
     * spotter产品id
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'productId': string;
    /**
     * 发货窗口结束
     * @type {number}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'windowEnd': number;
    /**
     * vendor code
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'accountCode': string;
    /**
     * 订单创建日期
     * @type {number}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'orderedOnMs': number;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'productName': string;
    /**
     * 发货窗口起始
     * @type {number}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'windowStart': number;
    /**
     * 采购数量
     * @type {number}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'orderedQuantity': number;
    /**
     * 履约明细
     * @type {Array<OrderB2bFulfillDetailSimpleVOModel>}
     * @memberof OrderB2bSptOrderDetailVOModel
     */
    'fulfillDetailList': Array<OrderB2bFulfillDetailSimpleVOModel>;
}

