/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 平台订单分页请求
 * @export
 * @interface OrderFulfillmentFulfillmentPageReqModel
 */
export interface OrderFulfillmentFulfillmentPageReqModel {
    /**
     * 履约单号
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'foNo'?: string;
    /**
     * 多个履约单号
     * @type {Array<string>}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'foNos'?: Array<string>;
    /**
     * 要求发运时间-结束
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'frdEnd'?: number;
    /**
     * 渠道订单号
     * @type {Array<string>}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'pltNos'?: Array<string>;
    /**
     * 系统订单号列表
     * @type {Array<string>}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'sptNos'?: Array<string>;
    /**
     * MSKU/sSKU/产品名称的模糊查询
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'keyword'?: string;
    /**
     * 要求发运时间-开始
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'frdStart'?: number;
    /**
     * 展示条数
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'pageSize': number;
    /**
     * 风险标记：1-有风险 0-无风险
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'riskFlag'?: string;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'brandName'?: string;
    /**
     * 公司id
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'companyId'?: number;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 订单状态
     * @type {Array<string>}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'statusList'?: Array<string>;
    /**
     * Vendor Code
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'accountCode'?: string;
    /**
     * 当前页数
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'currentPage': number;
    /**
     * 发货仓库
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'storageCode'?: string;
    /**
     * 邮件发送状态
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'emailSendFlag'?: number;
    /**
     * 渠道订单名称列表
     * @type {Array<string>}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'pltOrderNames'?: Array<string>;
    /**
     * 订单失败状态列表
     * @type {Array<string>}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'failStatusList'?: Array<string>;
    /**
     * 订单下单-搜索结束时间
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'orderedOnMsEnd'?: number;
    /**
     * VC 账号
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'mainAccountCode'?: string;
    /**
     * 账号经理
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'accountManagerId'?: number;
    /**
     * 订单下单-搜索开始时间
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'orderedOnMsStart'?: number;
    /**
     * 要求发货仓库
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'originStorageCode'?: string;
    /**
     * 实际到达日期-结束
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'actualArrivedMsEnd'?: number;
    /**
     * 实际发货日期-结束
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'actualShippingMsEnd'?: number;
    /**
     * 实际到达日期-开始
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'actualArrivedMsStart'?: number;
    /**
     * 公司&店铺映射
     * @type {{ [key: string]: Array<string>; }}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'companyAndAccountMap'?: { [key: string]: Array<string>; };
    /**
     * 实际发货日期-开始
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentPageReqModel
     */
    'actualShippingMsStart'?: number;
}

