/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 多渠道订单附件保存请求
 * @export
 * @interface OrderMultichannelAttachSaveReqModel
 */
export interface OrderMultichannelAttachSaveReqModel {
    /**
     * 附件地址
     * @type {string}
     * @memberof OrderMultichannelAttachSaveReqModel
     */
    'url': string;
    /**
     * 附件类型
     * @type {string}
     * @memberof OrderMultichannelAttachSaveReqModel
     */
    'type': string;
}

