/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 产品信息视图
 * @export
 * @interface OrderFulfillmentAccountVOModel
 */
export interface OrderFulfillmentAccountVOModel {
    /**
     * 所属公司id
     * @type {number}
     * @memberof OrderFulfillmentAccountVOModel
     */
    'companyId': number;
    /**
     * 店铺编码
     * @type {string}
     * @memberof OrderFulfillmentAccountVOModel
     */
    'accountCode': string;
    /**
     * 店铺名称
     * @type {string}
     * @memberof OrderFulfillmentAccountVOModel
     */
    'accountName': string;
}

