/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 亚马逊Df订单库存VO
 * @export
 * @interface OrderDfOrderAmzDfInventoryVOModel
 */
export interface OrderDfOrderAmzDfInventoryVOModel {
    /**
     * 可售数量
     * @type {number}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'num': number;
    /**
     * ASIN
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'asin': string;
    /**
     * ssku
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'ssku': string;
    /**
     * 可售数量更新值
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'syncNum': string;
    /**
     * VC账号id
     * @type {number}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'accountId': number;
    /**
     * 品牌
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'brandName': string;
    /**
     * ILLEGAL_PRODUCT:产品状态异常 OTHER:其他原因
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'failReason': string;
    /**
     * 数据同步状态：EXECUTING:执行中 FAIL:执行失败 SUCCESS:执行成功
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'syncStatus': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'companyName': string;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'productName': string;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'storageCode': string;
    /**
     * 仓库中文名称
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'storageName': string;
    /**
     * 仓库类型
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'storageType': string;
    /**
     * 产品状态
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'productStatus': string;
    /**
     * 单件区可用库存
     * @type {number}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'dropShipAvailable': number;
    /**
     * 账号经理
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'accountManagerName': string;
    /**
     * SVC账号/VC账号
     * @type {string}
     * @memberof OrderDfOrderAmzDfInventoryVOModel
     */
    'registeredBusinessName': string;
}

