/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 库存信息
 * @export
 * @interface OrderB2bInventoryVOModel
 */
export interface OrderB2bInventoryVOModel {
    /**
     * ssku
     * @type {string}
     * @memberof OrderB2bInventoryVOModel
     */
    'ssku': string;
    /**
     * 仓库推送状态 1-推送成功 0-推送失败
     * @type {string}
     * @memberof OrderB2bInventoryVOModel
     */
    'pushStatus': string;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderB2bInventoryVOModel
     */
    'storageCode': string;
    /**
     * 仓库名称
     * @type {string}
     * @memberof OrderB2bInventoryVOModel
     */
    'storageName': string;
    /**
     * 可用库存
     * @type {number}
     * @memberof OrderB2bInventoryVOModel
     */
    'availableNum': number;
}

