/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 订单确认响应视图
 * @export
 * @interface OrderFulfillmentFulfillmentConfirmRespDetailVOModel
 */
export interface OrderFulfillmentFulfillmentConfirmRespDetailVOModel {
    /**
     * sSKU
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentConfirmRespDetailVOModel
     */
    'ssku': string;
    /**
     * 渠道订单号
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentConfirmRespDetailVOModel
     */
    'pltNo': string;
    /**
     * 系统订单号
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentConfirmRespDetailVOModel
     */
    'sptNo': string;
    /**
     * 失败原因
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentConfirmRespDetailVOModel
     */
    'failReason': string;
}

