/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 待客户处理分页请求
 * @export
 * @interface OrderMultichannelPendingPageQueryModel
 */
export interface OrderMultichannelPendingPageQueryModel {
    /**
     * MSKU/sSKU/产品名称的模糊查询
     * @type {string}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'keyword'?: string;
    /**
     * 预计提货日期-结束
     * @type {number}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'frdMsEnd'?: number;
    /**
     * 展示条数
     * @type {number}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'pageSize': number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'brandName'?: string;
    /**
     * 公司id
     * @type {number}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'companyId'?: number;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 运输类型:SP、LTL
     * @type {string}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'transType'?: string;
    /**
     * 预计提货日期-开始
     * @type {number}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'frdMsStart'?: number;
    /**
     * 当前页数
     * @type {number}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'currentPage': number;
    /**
     * 发货仓库
     * @type {string}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'storageCode'?: string;
    /**
     * 面单获取方式-是否SPT提供面单:0-否、1-是
     * @type {string}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'sptLabelFlag'?: string;
    /**
     * 订单类型列表:FBA、MO
     * @type {Array<string>}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'orderTypeList'?: Array<string>;
    /**
     * 销售订单号列表
     * @type {Array<string>}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'pltOrderNames'?: Array<string>;
    /**
     * 异常状态列表
     * @type {Array<string>}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'failStatusList'?: Array<string>;
    /**
     * 订单创建日期-结束
     * @type {number}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'orderedOnMsEnd'?: number;
    /**
     * 账号经理
     * @type {number}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'accountManagerId'?: number;
    /**
     * 订单创建日期-开始
     * @type {number}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'orderedOnMsStart'?: number;
    /**
     * 待上传附件列表:attachShippingLabel、attachBol、attachBoxLabel、attachProductLabel
     * @type {Array<string>}
     * @memberof OrderMultichannelPendingPageQueryModel
     */
    'pendingUploadAttachList'?: Array<string>;
}

