/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * Gmesh亚马逊订单查询req
 * @export
 * @interface OrderPoOrderAmzQueryReqModel
 */
export interface OrderPoOrderAmzQueryReqModel {
    /**
     * MSKU/ASIN/sSKU/产品名称的模糊查询
     * @type {string}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'keyword'?: string;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'brandName'?: string;
    /**
     * 搜索类型
     * @type {string}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'searchKey'?: string;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 订单状态
     * @type {string}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'orderStatus'?: string;
    /**
     * 搜索值
     * @type {Array<string>}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'searchValue'?: Array<string>;
    /**
     * 更新时间
     * @type {number}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'updateTimeMs'?: number;
    /**
     * 订单下单-搜索结束时间
     * @type {number}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'orderedOnEndMs'?: number;
    /**
     * 订单状列表
     * @type {Array<string>}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'orderStatusList'?: Array<string>;
    /**
     * 订单下单-搜索开始时间
     * @type {number}
     * @memberof OrderPoOrderAmzQueryReqModel
     */
    'orderedOnStartMs'?: number;
}

