/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 请求结果数据
 * @export
 * @interface OrderAmzStatisticsVOSevcModel
 */
export interface OrderAmzStatisticsVOSevcModel {
    /**
     * 总金额
     * @type {number}
     * @memberof OrderAmzStatisticsVOSevcModel
     */
    'totalAmount'?: number;
    /**
     * 接单率
     * @type {number}
     * @memberof OrderAmzStatisticsVOSevcModel
     */
    'receivedRate'?: number;
    /**
     * 采购总金额
     * @type {number}
     * @memberof OrderAmzStatisticsVOSevcModel
     */
    'orderedAmount'?: number;
    /**
     * PO-BBO订单待发货数量
     * @type {number}
     * @memberof OrderAmzStatisticsVOSevcModel
     */
    'waitDeliveryOrder'?: number;
    /**
     * 待确认订单数量
     * @type {number}
     * @memberof OrderAmzStatisticsVOSevcModel
     */
    'waitConfirmedOrder'?: number;
    /**
     * 接单总金额
     * @type {number}
     * @memberof OrderAmzStatisticsVOSevcModel
     */
    'confirmedTotalAmount'?: number;
    /**
     * 总采购数量
     * @type {number}
     * @memberof OrderAmzStatisticsVOSevcModel
     */
    'totalOrderedQuantity'?: number;
    /**
     * 总实际接单数量
     * @type {number}
     * @memberof OrderAmzStatisticsVOSevcModel
     */
    'totalConfirmedQuantity'?: number;
}

