/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 商品装箱信息
 * @export
 * @interface OrderMultichannelCommodityPackageVOModel
 */
export interface OrderMultichannelCommodityPackageVOModel {
    /**
     * 单箱规格 - 高
     * @type {number}
     * @memberof OrderMultichannelCommodityPackageVOModel
     */
    'high': number;
    /**
     * 单箱规格 - 宽
     * @type {number}
     * @memberof OrderMultichannelCommodityPackageVOModel
     */
    'width': number;
    /**
     * 单箱规格 - 长
     * @type {number}
     * @memberof OrderMultichannelCommodityPackageVOModel
     */
    'length': number;
    /**
     * 单箱重量
     * @type {number}
     * @memberof OrderMultichannelCommodityPackageVOModel
     */
    'weight': number;
    /**
     * 装箱数量
     * @type {number}
     * @memberof OrderMultichannelCommodityPackageVOModel
     */
    'innerPack': number;
    /**
     * 可售数量
     * @type {number}
     * @memberof OrderMultichannelCommodityPackageVOModel
     */
    'availableNum': number;
}

