/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderMultichannelAttachSaveReqModel } from './order-multichannel-attach-save-req-model';
// May contain unused imports in some cases
// @ts-ignore
import { OrderMultichannelContactSaveReqModel } from './order-multichannel-contact-save-req-model';
// May contain unused imports in some cases
// @ts-ignore
import { OrderMultichannelProductSaveReqModel } from './order-multichannel-product-save-req-model';

/**
 * 多渠道订单编辑
 * @export
 * @interface OrderMultichannelEditReqModel
 */
export interface OrderMultichannelEditReqModel {
    /**
     * 预计提货日期
     * @type {number}
     * @memberof OrderMultichannelEditReqModel
     */
    'frd': number;
    /**
     * 销售订单号，不用传！！！
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'pltNo'?: string;
    /**
     * 系统订单号
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'sptNo': string;
    /**
     * 运输商
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'carrier'?: string;
    /**
     * 订单类型
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'orderType': string;
    /**
     * 运输模式
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'transType': string;
    /**
     * 公司编码
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'companyCode': string;
    /**
     * 订单备注
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'orderRemark'?: string;
    /**
     * 下单时间
     * @type {number}
     * @memberof OrderMultichannelEditReqModel
     */
    'orderedOnMs'?: number;
    /**
     * 始发仓
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'storageCode': string;
    /**
     * 运输追踪单号
     * @type {Array<string>}
     * @memberof OrderMultichannelEditReqModel
     */
    'trackingNum'?: Array<string>;
    /**
     * 销售订单名称，作为销售订单号传入！！！
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'pltOrderName': string;
    /**
     * 面单获取方式
     * @type {string}
     * @memberof OrderMultichannelEditReqModel
     */
    'sptLabelFlag': string;
    /**
     * 附件列表
     * @type {Array<OrderMultichannelAttachSaveReqModel>}
     * @memberof OrderMultichannelEditReqModel
     */
    'attachSaveReqList'?: Array<OrderMultichannelAttachSaveReqModel>;
    /**
     * 
     * @type {OrderMultichannelContactSaveReqModel}
     * @memberof OrderMultichannelEditReqModel
     */
    'destContactSaveReq'?: OrderMultichannelContactSaveReqModel;
    /**
     * 产品信息列表
     * @type {Array<OrderMultichannelProductSaveReqModel>}
     * @memberof OrderMultichannelEditReqModel
     */
    'productSaveReqList': Array<OrderMultichannelProductSaveReqModel>;
}

