/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 履约明细
 * @export
 * @interface OrderB2bFulfillDetailSimpleVOModel
 */
export interface OrderB2bFulfillDetailSimpleVOModel {
    /**
     * 预计提货时间
     * @type {number}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'frd': number;
    /**
     * ssku
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'ssku': string;
    /**
     * 渠道订单号
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'pltNo': string;
    /**
     * 履约明细唯一标识
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'ucode': string;
    /**
     * 运送地点
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'shipTo': string;
    /**
     * 装箱数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'innerPack': number;
    /**
     * 订单类型:FBA、MO
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'orderType': string;
    /**
     * External Id
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'externalId': string;
    /**
     * 订单创建日期
     * @type {number}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'orderedOnMs': number;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'storageCode': string;
    /**
     * 仓库名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'storageName': string;
    /**
     * 采购数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'orderedQuantity': number;
    /**
     * 实际接单数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'confirmedQuantity': number;
    /**
     * 产品异常标识：0-正常，1-异常
     * @type {string}
     * @memberof OrderB2bFulfillDetailSimpleVOModel
     */
    'externalIdExpFlag': string;
}

