/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 亚马逊DF订单分页Req
 * @export
 * @interface OrderDfOrderAmzDfPageReqModel
 */
export interface OrderDfOrderAmzDfPageReqModel {
    /**
     * asin列表
     * @type {Array<string>}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'asins'?: Array<string>;
    /**
     * ssku列表
     * @type {Array<string>}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'sskus'?: Array<string>;
    /**
     * DF订单号
     * @type {string}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'amzCode'?: string;
    /**
     * ASIN/sSKU/产品名称的模糊查询
     * @type {string}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'keyword'?: string;
    /**
     * 要求发运时间终止时间戳
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'frdEndMs'?: number;
    /**
     * 展示条数
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'pageSize': number;
    /**
     * VC账号id
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'accountId'?: number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'brandName'?: string;
    /**
     * 公司id
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'companyId'?: number;
    /**
     * 搜索类型
     * @type {string}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'searchKey'?: string;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 要求发运时间起始时间戳
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'frdStartMs'?: number;
    /**
     * 同步状态
     * @type {string}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'syncStatus'?: string;
    /**
     * 供应商编码
     * @type {string}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'vendorCode'?: string;
    /**
     * 当前页数
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'currentPage': number;
    /**
     * 搜索值
     * @type {Array<string>}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'searchValue'?: Array<string>;
    /**
     * 确认发货仓库
     * @type {string}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'storageCode'?: string;
    /**
     * 仓库类型(1自发仓 2云仓 3自营仓)
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'storageType'?: number;
    /**
     * 邮件发送状态: 0:未发送,1:已发送
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'emailSendFlag'?: number;
    /**
     * 产品状态
     * @type {string}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'productStatus'?: string;
    /**
     * 订单下单-搜索结束时间
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'orderedOnEndMs'?: number;
    /**
     * 订单状态: New:待确认,Pending:处理中,UNSHIPPED:待发货,SHIPPED:已发货,ARRIVED:已到货,CANCELED:已取消
     * @type {Array<string>}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'orderStatusList'?: Array<string>;
    /**
     * 账号经理id
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'accountManagerId'?: number;
    /**
     * 订单下单-搜索开始时间
     * @type {number}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'orderedOnStartMs'?: number;
    /**
     * 产品状态列表
     * @type {Array<string>}
     * @memberof OrderDfOrderAmzDfPageReqModel
     */
    'productStatusList'?: Array<string>;
}

