/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 订单缺货看板VO
 * @export
 * @interface OrderFulfillmentFulfillmentLackVOModel
 */
export interface OrderFulfillmentFulfillmentLackVOModel {
    /**
     * msku
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'msku': string;
    /**
     * ssku
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'ssku': string;
    /**
     * pltSku
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'pltSku': string;
    /**
     * 品牌
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'brandName': string;
    /**
     * 公司ID
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'companyId': string;
    /**
     * 公司Code
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'companyCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'companyName': string;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'productName': string;
    /**
     * 单间区缺货数量
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'lackQuantity': number;
    /**
     * 账号经理ID
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'accountManagerId': string;
    /**
     * 要求发货仓库编码
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'originStorageCode': string;
    /**
     * 要求发货仓库名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'originStorageName': string;
    /**
     * 账号经理
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentLackVOModel
     */
    'accountManagerName': string;
}

