/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 金额
 * @export
 * @interface OrderB2bB2bStatisticsVOModel
 */
export interface OrderB2bB2bStatisticsVOModel {
    /**
     * 接单率
     * @type {string}
     * @memberof OrderB2bB2bStatisticsVOModel
     */
    'receivedRate': string;
    /**
     * 待确认订单数量
     * @type {number}
     * @memberof OrderB2bB2bStatisticsVOModel
     */
    'newOrderCount': number;
    /**
     * 待提交订单数量
     * @type {number}
     * @memberof OrderB2bB2bStatisticsVOModel
     */
    'pendingOrderCount': number;
    /**
     * 待发货订单数量
     * @type {number}
     * @memberof OrderB2bB2bStatisticsVOModel
     */
    'unshippedOrderCount': number;
    /**
     * 总采购数量
     * @type {number}
     * @memberof OrderB2bB2bStatisticsVOModel
     */
    'totalOrderedQuantity': number;
    /**
     * 总接单数量
     * @type {number}
     * @memberof OrderB2bB2bStatisticsVOModel
     */
    'totalConfirmedQuantity': number;
    /**
     * 二次确认订单数量
     * @type {number}
     * @memberof OrderB2bB2bStatisticsVOModel
     */
    'secondConfirmOrderCount': number;
}

