/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 多渠道订单附件视图
 * @export
 * @interface OrderMultichannelAttachVOModel
 */
export interface OrderMultichannelAttachVOModel {
    /**
     * 附件地址
     * @type {string}
     * @memberof OrderMultichannelAttachVOModel
     */
    'url': string;
    /**
     * 附件名称
     * @type {string}
     * @memberof OrderMultichannelAttachVOModel
     */
    'name': string;
    /**
     * 附件类型:attachShippingLabel、attachBol、attachBoxLabel、attachProductLabel、attachProLabel、attachBolSignBill、attachArrivalCertificate、attachPalletLabel、default
     * @type {string}
     * @memberof OrderMultichannelAttachVOModel
     */
    'type': string;
}

