/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderB2bFulfillDetailSimpleVOModel } from './order-b2b-fulfill-detail-simple-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { OrderB2bInventoryVOModel } from './order-b2b-inventory-vomodel';

/**
 * spt order明细列表,附带库存信息
 * @export
 * @interface OrderB2bSptOrderDetailsWithIvtVOModel
 */
export interface OrderB2bSptOrderDetailsWithIvtVOModel {
    /**
     * 库存信息
     * @type {Array<OrderB2bInventoryVOModel>}
     * @memberof OrderB2bSptOrderDetailsWithIvtVOModel
     */
    'inventoryList': Array<OrderB2bInventoryVOModel>;
    /**
     * 履约明细
     * @type {Array<OrderB2bFulfillDetailSimpleVOModel>}
     * @memberof OrderB2bSptOrderDetailsWithIvtVOModel
     */
    'fulfillDetailList': Array<OrderB2bFulfillDetailSimpleVOModel>;
}

