/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 订单更新原因
 * @export
 * @interface OrderPoAmzOrderUpdateVOModel
 */
export interface OrderPoAmzOrderUpdateVOModel {
    /**
     * asin
     * @type {string}
     * @memberof OrderPoAmzOrderUpdateVOModel
     */
    'asin': string;
    /**
     * 原因
     * @type {string}
     * @memberof OrderPoAmzOrderUpdateVOModel
     */
    'reason': string;
    /**
     * 是否成功
     * @type {boolean}
     * @memberof OrderPoAmzOrderUpdateVOModel
     */
    'result': boolean;
    /**
     * saCode
     * @type {string}
     * @memberof OrderPoAmzOrderUpdateVOModel
     */
    'saCode': string;
    /**
     * 亚马逊订单号list
     * @type {Array<string>}
     * @memberof OrderPoAmzOrderUpdateVOModel
     */
    '亚马逊订单号list': Array<string>;
}

