/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 亚马逊Df订单VO
 * @export
 * @interface OrderDfOrderAmzDfItemVOModel
 */
export interface OrderDfOrderAmzDfItemVOModel {
    /**
     * 要求发运时间
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'frd': number;
    /**
     * asin
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'asin': string;
    /**
     * sSku
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'ssku': string;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'title': string;
    /**
     * DF订单号
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'amzCode': string;
    /**
     * 异常订单 0:正常,3:库存不足
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'unusual': number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'brandName': string;
    /**
     * 采购价
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'costPrice': number;
    /**
     * 总采购价
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'totalPrice': number;
    /**
     * vendorCode
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'vendorCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'companyName': string;
    /**
     * 订单状态:New,Pending,Unshipped,Shipped,Arrived,Canceled
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'orderStatus': string;
    /**
     * 下单日期
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'orderedOnMs': number;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'storageCode': string;
    /**
     * 仓库中文名称
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'storageName': string;
    /**
     * 亚马逊发货日期
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'amzDeliveryMs': number;
    /**
     * 邮件发送状态: 0 未发送，1 已发送
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'emailSendFlag': number;
    /**
     * 实际发货日期
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'sptDeliveryMs': number;
    /**
     * 产品数量
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'orderedQuantity': number;
    /**
     * 接单数量
     * @type {number}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'confirmedQuantity': number;
    /**
     * 账号经理
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'accountManagerName': string;
    /**
     * SVC账号/VC账号
     * @type {string}
     * @memberof OrderDfOrderAmzDfItemVOModel
     */
    'registeredBusinessName': string;
}

