/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 多渠道订单统计
 * @export
 * @interface OrderMultichannelStatisticsVOModel
 */
export interface OrderMultichannelStatisticsVOModel {
    /**
     * 待客户处理的渠道订单数量
     * @type {number}
     * @memberof OrderMultichannelStatisticsVOModel
     */
    'pendingCount': number;
    /**
     * 发货异常的履约明细数量
     * @type {number}
     * @memberof OrderMultichannelStatisticsVOModel
     */
    'exceptionShipCount': number;
    /**
     * 面单打印失败的渠道订单数量
     * @type {number}
     * @memberof OrderMultichannelStatisticsVOModel
     */
    'logisticErrorCount': number;
    /**
     * 附件未上传的渠道订单数量
     * @type {number}
     * @memberof OrderMultichannelStatisticsVOModel
     */
    'attachNotUploadCount': number;
}

