/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 批量预校验附件参数
 * @export
 * @interface OrderMultichannelPreCheckAttachReqModel
 */
export interface OrderMultichannelPreCheckAttachReqModel {
    /**
     * 文件类型
     * @type {string}
     * @memberof OrderMultichannelPreCheckAttachReqModel
     */
    'attachType': string;
    /**
     * 公司code
     * @type {string}
     * @memberof OrderMultichannelPreCheckAttachReqModel
     */
    'companyCode': string;
    /**
     * 是否校验重复销售单号
     * @type {boolean}
     * @memberof OrderMultichannelPreCheckAttachReqModel
     */
    'checkDupName'?: boolean;
    /**
     * 平台订单名称，单个上传时必传，此情况下不会再校验文件名。批量上传时不能传。
     * @type {string}
     * @memberof OrderMultichannelPreCheckAttachReqModel
     */
    'pltOrderName'?: string;
    /**
     * 预校验的文件名字，包括后缀
     * @type {Array<string>}
     * @memberof OrderMultichannelPreCheckAttachReqModel
     */
    'attachNameList': Array<string>;
}

