/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderFulfillmentLogisticRoutingVOModel } from './order-fulfillment-logistic-routing-vomodel';

/**
 * 物流信息视图
 * @export
 * @interface OrderFulfillmentLogisticVOModel
 */
export interface OrderFulfillmentLogisticVOModel {
    /**
     * 系统订单号
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'foNo': string;
    /**
     * MSKU
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'msku': string;
    /**
     * sSKU
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'ssku': string;
    /**
     * 标签地址
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'label': string;
    /**
     * 渠道订单号
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'pltNo': string;
    /**
     * 承运商
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'carrier': string;
    /**
     * 运输模式
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'transType': string;
    /**
     * 更新时间
     * @type {number}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'updatedMs': number;
    /**
     * 包裹状态
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'parcelStatus': string;
    /**
     * 渠道订单名称
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'pltOrderName': string;
    /**
     * 运输追踪单号
     * @type {string}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'trackingNumber': string;
    /**
     * 包裹路由信息列表
     * @type {Array<OrderFulfillmentLogisticRoutingVOModel>}
     * @memberof OrderFulfillmentLogisticVOModel
     */
    'logisticRoutingList': Array<OrderFulfillmentLogisticRoutingVOModel>;
}

