/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderBboOrderAmzBboItemVOModel } from './order-bbo-order-amz-bbo-item-vomodel';

/**
 * SEVC亚马逊BBO订单询盘VO
 * @export
 * @interface OrderBboOrderAmzBboSevcVOModel
 */
export interface OrderBboOrderAmzBboSevcVOModel {
    /**
     * id
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'id': number;
    /**
     * asin
     * @type {string}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'asin': string;
    /**
     * sSku
     * @type {string}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'ssku': string;
    /**
     * 接单详情列表
     * @type {Array<OrderBboOrderAmzBboItemVOModel>}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'items': Array<OrderBboOrderAmzBboItemVOModel>;
    /**
     * 产品标题
     * @type {string}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'title': string;
    /**
     * spt采购价
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'sptPrice': number;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'brandName': string;
    /**
     * 截止时间
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'deadlineMs': number;
    /**
     * 倒计时
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'countdownMs': number;
    /**
     * 订单状态:NEW,PENDING,ACKNOWLEDGED,CLOSED,EXECUTING
     * @type {string}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'orderStatus': string;
    /**
     * 下单时间
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'orderedOnMs': number;
    /**
     * BBO采购价
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'sptBboPrice': number;
    /**
     * 折扣
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'sptBboDiscount': number;
    /**
     * 差价
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'sptPriceDifference': number;
    /**
     * 采购总数量
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'orderedTotalQuantity': number;
    /**
     * BBO采购总金额
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'sptOrderedTotalPrice': number;
    /**
     * BBO接单总金额
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'bboTotalConfirmedPrice': number;
    /**
     * 接单总数量
     * @type {number}
     * @memberof OrderBboOrderAmzBboSevcVOModel
     */
    'confirmedTotalQuantity': number;
}

