/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 亚马逊订单库存VO
 * @export
 * @interface OrderPoOrderAmzInventoryVOModel
 */
export interface OrderPoOrderAmzInventoryVOModel {
    /**
     * ssku
     * @type {string}
     * @memberof OrderPoOrderAmzInventoryVOModel
     */
    'ssku': string;
    /**
     * 0 推送中,1 成功,2 失败
     * @type {string}
     * @memberof OrderPoOrderAmzInventoryVOModel
     */
    'pushStatus': string;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderPoOrderAmzInventoryVOModel
     */
    'storageCode': string;
    /**
     * 仓库名称
     * @type {string}
     * @memberof OrderPoOrderAmzInventoryVOModel
     */
    'storageName': string;
    /**
     * spt可用库存
     * @type {number}
     * @memberof OrderPoOrderAmzInventoryVOModel
     */
    'transitAvailable': number;
}

