/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 平台订单编辑请求
 * @export
 * @interface OrderFulfillmentFulfillmentModifyReqModel
 */
export interface OrderFulfillmentFulfillmentModifyReqModel {
    /**
     * 订单详情唯一编码
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentModifyReqModel
     */
    'ucode': string;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentModifyReqModel
     */
    'storageCode': string;
}

