/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MoneyDTOModel } from './money-dtomodel';

/**
 * 履约明细
 * @export
 * @interface OrderB2bFulfillDetailVOModel
 */
export interface OrderB2bFulfillDetailVOModel {
    /**
     * 预计提货时间
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'frd': number;
    /**
     * 履约单号
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'foNo': string;
    /**
     * msku
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'msku': string;
    /**
     * ssku
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'ssku': string;
    /**
     * 渠道订单号
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'pltNo': string;
    /**
     * spotter订单号
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'sptNo': string;
    /**
     * 履约明细唯一标识
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'ucode': string;
    /**
     * pltSku
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'pltSku': string;
    /**
     * 运送地点
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'shipTo': string;
    /**
     * 订单状态
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'status': string;
    /**
     * version
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'version': number;
    /**
     * 是否可编辑
     * @type {boolean}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'editable': boolean;
    /**
     * 品牌名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'brandName': string;
    /**
     * 公司ID
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'companyId': number;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'costPrice': MoneyDTOModel;
    /**
     * 装箱数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'innerPack': number;
    /**
     * 订单类型:FBA、MO
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'orderType': string;
    /**
     * UPC/EAN
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'productId': string;
    /**
     * windowEnd
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'windowEnd': number;
    /**
     * External Id
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'externalId': string;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'totalPrice': MoneyDTOModel;
    /**
     * vendor code
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'accountCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'companyCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'companyName': string;
    /**
     * 订单创建日期
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'orderedOnMs': number;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'productName': string;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'storageCode': string;
    /**
     * 仓库名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'storageName': string;
    /**
     * windowStart
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'windowStart': number;
    /**
     * 取消原因
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'cancelReason': string;
    /**
     * 渠道订单名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'pltOrderName': string;
    /**
     * 实际到达时间
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'actualArrivedMs': number;
    /**
     * 主账号
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'mainAccountCode': string;
    /**
     * 主账号名称
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'mainAccountName': string;
    /**
     * 采购数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'orderedQuantity': number;
    /**
     * 实际发货时间
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'actualShippingMs': number;
    /**
     * 实际接单数量
     * @type {number}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'confirmedQuantity': number;
    /**
     * 账号经理
     * @type {string}
     * @memberof OrderB2bFulfillDetailVOModel
     */
    'accountManagerName': string;
}

