/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 接单数量
 * @export
 * @interface OrderB2bConfirmDetailReqModel
 */
export interface OrderB2bConfirmDetailReqModel {
    /**
     * ssku
     * @type {string}
     * @memberof OrderB2bConfirmDetailReqModel
     */
    'ssku'?: string;
    /**
     * pltNo
     * @type {string}
     * @memberof OrderB2bConfirmDetailReqModel
     */
    'pltNo'?: string;
    /**
     * sptNo
     * @type {string}
     * @memberof OrderB2bConfirmDetailReqModel
     */
    'sptNo'?: string;
    /**
     * ucode
     * @type {string}
     * @memberof OrderB2bConfirmDetailReqModel
     */
    'ucode': string;
    /**
     * pltItemId
     * @type {string}
     * @memberof OrderB2bConfirmDetailReqModel
     */
    'pltItemId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrderB2bConfirmDetailReqModel
     */
    'needFreeze'?: boolean;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderB2bConfirmDetailReqModel
     */
    'storageCode'?: string;
    /**
     * 实际接单数量
     * @type {number}
     * @memberof OrderB2bConfirmDetailReqModel
     */
    'confirmedQuantity': number;
}

