/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 附件查询
 * @export
 * @interface OrderB2bAttachQueryReqModel
 */
export interface OrderB2bAttachQueryReqModel {
    /**
     * 履约单号
     * @type {string}
     * @memberof OrderB2bAttachQueryReqModel
     */
    'foNo'?: string;
    /**
     * 履约明细code
     * @type {string}
     * @memberof OrderB2bAttachQueryReqModel
     */
    'ucode'?: string;
}

