/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 多渠道订单详情
 * @export
 * @interface OrderMultichannelDetailQueryReqModel
 */
export interface OrderMultichannelDetailQueryReqModel {
    /**
     * 平台订单号
     * @type {string}
     * @memberof OrderMultichannelDetailQueryReqModel
     */
    'pltNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderMultichannelDetailQueryReqModel
     */
    'ucode'?: string;
    /**
     * 是否填充产品信息中的库存和尺寸信息
     * @type {boolean}
     * @memberof OrderMultichannelDetailQueryReqModel
     */
    'fillCommodityPackage'?: boolean;
}

