/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MoneyDTOModel } from './money-dtomodel';
// May contain unused imports in some cases
// @ts-ignore
import { OrderWmsInventoryVOModel } from './order-wms-inventory-vomodel';

/**
 * 平台订单视图
 * @export
 * @interface OrderFulfillmentFulfillmentVOModel
 */
export interface OrderFulfillmentFulfillmentVOModel {
    /**
     * 要求发运日期
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'frd': number;
    /**
     * 履约单号
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'foNo': string;
    /**
     * MSKU
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'msku': string;
    /**
     * sSKU
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'ssku': string;
    /**
     * 渠道订单号
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'pltNo': string;
    /**
     * 系统订单号
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'sptNo': string;
    /**
     * 履约详情唯一编码
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'ucode': string;
    /**
     * 平台SKU
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'pltSku': string;
    /**
     * 状态
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'status': string;
    /**
     * 风险标记：1-有风险 0-无风险
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'riskFlag': string;
    /**
     * SPT发运：SPT spotter发运、SELF 自发
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'shipType': string;
    /**
     * 品牌
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'brandName': string;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'costPrice': MoneyDTOModel;
    /**
     * 装箱数量
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'innerPack': string;
    /**
     * 子状态
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'subStatus': string;
    /**
     * 运输模式
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'transType': string;
    /**
     * 发货异常原因
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'failReason': string;
    /**
     * 发货异常状态
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'failStatus': string;
    /**
     * 待上传附件
     * @type {Array<string>}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'lackAttach': Array<string>;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'totalPrice': MoneyDTOModel;
    /**
     * Vendor Code
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'accountCode': string;
    /**
     * 店铺名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'accountName': string;
    /**
     * 公司编码
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'companyCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'companyName': string;
    /**
     * 下单时间
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'orderedOnMs': number;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'productName': string;
    /**
     * 发货仓库
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'storageCode': string;
    /**
     * 发货仓库名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'storageName': string;
    /**
     * 渠道订单名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'pltOrderName': string;
    /**
     * 邮件发送状态
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'emailSendFlag': number;
    /**
     * 库存列表
     * @type {Array<OrderWmsInventoryVOModel>}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'inventoryList': Array<OrderWmsInventoryVOModel>;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'totalPayPrice': MoneyDTOModel;
    /**
     * 实际到达日期
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'actualArrivedMs': number;
    /**
     * VC 账号Code
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'mainAccountCode': string;
    /**
     * VC 账号名称
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'mainAccountName': string;
    /**
     * 数量
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'orderedQuantity': number;
    /**
     * 账号经理ID
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'accountManagerId': number;
    /**
     * 实际发货日期
     * @type {number}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'actualShippingMs': number;
    /**
     * 要求发货仓库code
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'originStorageCode': string;
    /**
     * 要求发货仓库名字
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'originStorageName': string;
    /**
     * 账号经理名字
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'accountManagerName': string;
    /**
     * 订单箱数
     * @type {string}
     * @memberof OrderFulfillmentFulfillmentVOModel
     */
    'orderedCartonQuantity': string;
}

