/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 亚马逊订单商品详情和扩展详情VO
 * @export
 * @interface OrderBboOrderAmzBboItemVOModel
 */
export interface OrderBboOrderAmzBboItemVOModel {
    /**
     * id
     * @type {number}
     * @memberof OrderBboOrderAmzBboItemVOModel
     */
    'id': number;
    /**
     * 亚马逊订单号
     * @type {string}
     * @memberof OrderBboOrderAmzBboItemVOModel
     */
    'amzCode': string;
    /**
     * 装箱数量
     * @type {string}
     * @memberof OrderBboOrderAmzBboItemVOModel
     */
    'innerPack': string;
    /**
     * 发货窗口
     * @type {string}
     * @memberof OrderBboOrderAmzBboItemVOModel
     */
    'shipWindow': string;
    /**
     * 采购数量
     * @type {number}
     * @memberof OrderBboOrderAmzBboItemVOModel
     */
    'orderedQuantity': number;
    /**
     * 接单数量
     * @type {number}
     * @memberof OrderBboOrderAmzBboItemVOModel
     */
    'confirmedQuantity': number;
}

