/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MoneyDTOModel } from './money-dtomodel';

/**
 * 多渠道履约明细视图
 * @export
 * @interface OrderMultichannelMcFulfillDetailVOModel
 */
export interface OrderMultichannelMcFulfillDetailVOModel {
    /**
     * 要求发运日期
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'frd': number;
    /**
     * 履约单号
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'foNo': string;
    /**
     * MSKU
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'msku': string;
    /**
     * sSKU
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'ssku': string;
    /**
     * 渠道订单号
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'pltNo': string;
    /**
     * 系统订单号
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'sptNo': string;
    /**
     * 履约详情唯一编码
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'ucode': string;
    /**
     * 箱数
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'boxNum': number;
    /**
     * 平台SKU
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'pltSku': string;
    /**
     * 状态
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'status': string;
    /**
     * 品牌
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'brandName': string;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'costPrice': MoneyDTOModel;
    /**
     * 装箱数量
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'innerPack': number;
    /**
     * 订单类型:FBA、MO
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'orderType': string;
    /**
     * 子状态
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'subStatus': string;
    /**
     * 运输类型:SP、LTL
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'transType': string;
    /**
     * 发货异常原因
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'failReason': string;
    /**
     * 发货异常状态
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'failStatus': string;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'totalPrice': MoneyDTOModel;
    /**
     * 账号编码
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'accountCode': string;
    /**
     * 公司编码
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'companyCode': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'companyName': string;
    /**
     * 下单时间
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'orderedOnMs': number;
    /**
     * 产品名称
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'productName': string;
    /**
     * 发货仓库
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'storageCode': string;
    /**
     * 发货仓库名称
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'storageName': string;
    /**
     * 渠道订单名称
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'pltOrderName': string;
    /**
     * 面单获取方式-是否SPT提供面单:0-否、1-是
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'sptLabelFlag': string;
    /**
     * 邮件发送状态
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'emailSendFlag': number;
    /**
     * 
     * @type {MoneyDTOModel}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'totalPayPrice': MoneyDTOModel;
    /**
     * 实际到达日期
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'actualArrivedMs': number;
    /**
     * 主账号编码
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'mainAccountCode': string;
    /**
     * 数量
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'orderedQuantity': number;
    /**
     * 账号经理ID
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'accountManagerId': number;
    /**
     * 实际发货日期
     * @type {number}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'actualShippingMs': number;
    /**
     * 账号经理名字
     * @type {string}
     * @memberof OrderMultichannelMcFulfillDetailVOModel
     */
    'accountManagerName': string;
}

