/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderDfOrderAmzDfItemVOModel } from './order-df-order-amz-df-item-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { OrderWmsInventoryVOModel } from './order-wms-inventory-vomodel';

/**
 * 亚马逊Df订单列表和库存列表VO
 * @export
 * @interface OrderDfOrderAmzDfWithInventoryVOModel
 */
export interface OrderDfOrderAmzDfWithInventoryVOModel {
    /**
     * DF订单列表
     * @type {Array<OrderDfOrderAmzDfItemVOModel>}
     * @memberof OrderDfOrderAmzDfWithInventoryVOModel
     */
    'itemVOS': Array<OrderDfOrderAmzDfItemVOModel>;
    /**
     * 库存列表map，ssku为key
     * @type {{ [key: string]: Array<OrderWmsInventoryVOModel>; }}
     * @memberof OrderDfOrderAmzDfWithInventoryVOModel
     */
    'inventoryMapVO': { [key: string]: Array<OrderWmsInventoryVOModel>; };
}

