/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * item实际接单数量及仓库
 * @export
 * @interface OrderPoOrderAmzItemUpdateReqModel
 */
export interface OrderPoOrderAmzItemUpdateReqModel {
    /**
     * 预计提货时间
     * @type {number}
     * @memberof OrderPoOrderAmzItemUpdateReqModel
     */
    'frd'?: number;
    /**
     * ASIN
     * @type {string}
     * @memberof OrderPoOrderAmzItemUpdateReqModel
     */
    'asin'?: string;
    /**
     * ssku
     * @type {string}
     * @memberof OrderPoOrderAmzItemUpdateReqModel
     */
    'ssku'?: string;
    /**
     * 亚马逊订单号
     * @type {string}
     * @memberof OrderPoOrderAmzItemUpdateReqModel
     */
    'amzCode'?: string;
    /**
     * 仓库编码
     * @type {string}
     * @memberof OrderPoOrderAmzItemUpdateReqModel
     */
    'storageCode'?: string;
    /**
     * 实际接单数量
     * @type {number}
     * @memberof OrderPoOrderAmzItemUpdateReqModel
     */
    'confirmedQuantity'?: number;
}

