/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 多渠道订单产品信息保存请求
 * @export
 * @interface OrderMultichannelProductSaveReqModel
 */
export interface OrderMultichannelProductSaveReqModel {
    /**
     * asin
     * @type {string}
     * @memberof OrderMultichannelProductSaveReqModel
     */
    'asin'?: string;
    /**
     * msku
     * @type {string}
     * @memberof OrderMultichannelProductSaveReqModel
     */
    'msku'?: string;
    /**
     * ssku
     * @type {string}
     * @memberof OrderMultichannelProductSaveReqModel
     */
    'ssku': string;
    /**
     * 订单箱数
     * @type {number}
     * @memberof OrderMultichannelProductSaveReqModel
     */
    'boxNum': number;
    /**
     * 装箱数量
     * @type {number}
     * @memberof OrderMultichannelProductSaveReqModel
     */
    'innerPack': number;
    /**
     * 是否换标
     * @type {string}
     * @memberof OrderMultichannelProductSaveReqModel
     */
    'changeProLabelFlag': string;
}

