/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 发货异常页面分页请求
 * @export
 * @interface OrderMultichannelExceptionPageQueryModel
 */
export interface OrderMultichannelExceptionPageQueryModel {
    /**
     * 履约单号列表
     * @type {Array<string>}
     * @memberof OrderMultichannelExceptionPageQueryModel
     */
    'foNoList'?: Array<string>;
    /**
     * 展示条数
     * @type {number}
     * @memberof OrderMultichannelExceptionPageQueryModel
     */
    'pageSize': number;
    /**
     * 公司id
     * @type {number}
     * @memberof OrderMultichannelExceptionPageQueryModel
     */
    'companyId'?: number;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof OrderMultichannelExceptionPageQueryModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 当前页数
     * @type {number}
     * @memberof OrderMultichannelExceptionPageQueryModel
     */
    'currentPage': number;
    /**
     * 销售订单号列表
     * @type {Array<string>}
     * @memberof OrderMultichannelExceptionPageQueryModel
     */
    'pltOrderNames'?: Array<string>;
}

