/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CatalogOfferOfferItemActiveListAllVOModel } from './catalog-offer-offer-item-active-list-all-vomodel';

/**
 * 请求结果数据
 * @export
 * @interface PageVOCatalogOfferOfferItemActiveListAllVOModel
 */
export interface PageVOCatalogOfferOfferItemActiveListAllVOModel {
    /**
     * 结果列表
     * @type {Array<CatalogOfferOfferItemActiveListAllVOModel>}
     * @memberof PageVOCatalogOfferOfferItemActiveListAllVOModel
     */
    'data': Array<CatalogOfferOfferItemActiveListAllVOModel>;
    /**
     * 是否有下一页,true=有，false=没有
     * @type {boolean}
     * @memberof PageVOCatalogOfferOfferItemActiveListAllVOModel
     */
    'isMore': boolean;
    /**
     * 每页显示的总条数
     * @type {number}
     * @memberof PageVOCatalogOfferOfferItemActiveListAllVOModel
     */
    'pageSize': number;
    /**
     * 总条数
     * @type {number}
     * @memberof PageVOCatalogOfferOfferItemActiveListAllVOModel
     */
    'totalNum': number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageVOCatalogOfferOfferItemActiveListAllVOModel
     */
    'totalPage': number;
    /**
     * 开始索引
     * @type {number}
     * @memberof PageVOCatalogOfferOfferItemActiveListAllVOModel
     */
    'startIndex': number;
    /**
     * 当前页
     * @type {number}
     * @memberof PageVOCatalogOfferOfferItemActiveListAllVOModel
     */
    'currentPage': number;
}

