/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel } from './shipment-web-common-vo-amz-shipment-with-simple-items-vomodel';

/**
 * 请求结果数据
 * @export
 * @interface PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
 */
export interface PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel {
    /**
     * 结果列表
     * @type {Array<ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel>}
     * @memberof PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'data': Array<ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel>;
    /**
     * 是否有下一页,true=有，false=没有
     * @type {boolean}
     * @memberof PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'isMore': boolean;
    /**
     * 每页显示的总条数
     * @type {number}
     * @memberof PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'pageSize': number;
    /**
     * 总条数
     * @type {number}
     * @memberof PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'totalNum': number;
    /**
     * 总页数
     * @type {number}
     * @memberof PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'totalPage': number;
    /**
     * 开始索引
     * @type {number}
     * @memberof PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'startIndex': number;
    /**
     * 当前页
     * @type {number}
     * @memberof PageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'currentPage': number;
}

