/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 包裹信息
 * @export
 * @interface ParcelInfoParamModel
 */
export interface ParcelInfoParamModel {
    /**
     * 数量
     * @type {number}
     * @memberof ParcelInfoParamModel
     */
    'count'?: number;
    /**
     * 宽
     * @type {number}
     * @memberof ParcelInfoParamModel
     */
    'width'?: number;
    /**
     * 高
     * @type {number}
     * @memberof ParcelInfoParamModel
     */
    'height'?: number;
    /**
     * 长
     * @type {number}
     * @memberof ParcelInfoParamModel
     */
    'length'?: number;
    /**
     * 单个包裹重量
     * @type {number}
     * @memberof ParcelInfoParamModel
     */
    'weight'?: number;
}

