/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductPageQueryReqModel
 */
export interface ProductPageQueryReqModel {
    /**
     * 产品名称/sSKU/MSKU/ASIN模糊查询
     * @type {string}
     * @memberof ProductPageQueryReqModel
     */
    'keyWork'?: string;
    /**
     * 展示条数
     * @type {number}
     * @memberof ProductPageQueryReqModel
     */
    'pageSize': number;
    /**
     * ssku列表
     * @type {Array<string>}
     * @memberof ProductPageQueryReqModel
     */
    'sskuList'?: Array<string>;
    /**
     * 公司id
     * @type {number}
     * @memberof ProductPageQueryReqModel
     */
    'companyId'?: number;
    /**
     * 订单类型
     * @type {string}
     * @memberof ProductPageQueryReqModel
     */
    'orderType': string;
    /**
     * 公司code
     * @type {string}
     * @memberof ProductPageQueryReqModel
     */
    'companyCode'?: string;
    /**
     * 当前页数
     * @type {number}
     * @memberof ProductPageQueryReqModel
     */
    'currentPage': number;
    /**
     * 仓库编码
     * @type {string}
     * @memberof ProductPageQueryReqModel
     */
    'storageCode': string;
    /**
     * 销售订单名称
     * @type {string}
     * @memberof ProductPageQueryReqModel
     */
    'pltOrderName'?: string;
}

