/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户拥有角色
 * @export
 * @interface RoleSimpleVOModel
 */
export interface RoleSimpleVOModel {
    /**
     * 角色代号
     * @type {string}
     * @memberof RoleSimpleVOModel
     */
    'code': string;
    /**
     * 角色名称
     * @type {string}
     * @memberof RoleSimpleVOModel
     */
    'name': string;
}

