/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 列表请求
 * @export
 * @interface ShipmentWebSevcAmzShipmentListReqModel
 */
export interface ShipmentWebSevcAmzShipmentListReqModel {
    /**
     * arn
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'arn'?: string;
    /**
     * asn
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'asn'?: string;
    /**
     * ARN/ASN
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'arsn'?: string;
    /**
     * 预计提货时间-结束
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'frdEnd'?: number;
    /**
     * sa订单
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'saPoNo'?: string;
    /**
     * 亚马逊采购订单号
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'amzPoNo'?: string;
    /**
     * 承运商
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'carrier'?: string;
    /**
     * 产品名称/ASIN/sSku
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'keyword'?: string;
    /**
     * 预计提货时间-开始
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'frdBegin'?: number;
    /**
     * 展示条数
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'pageSize': number;
    /**
     * 公司id
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'companyId'?: number;
    /**
     * 主状态: processing 处理中; pending_pick_up 待取件; in_transport 在途中; finished 已到达; canceled 已取消;
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'mainState'?: string;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 创建时间-结束
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'createAtEnd'?: number;
    /**
     * 当前页数
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'currentPage': number;
    /**
     * 发货仓库
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'storageCode'?: string;
    /**
     * VCPO物流单号
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'shipmentCode'?: string;
    /**
     * 子节点状态：none 无任务，in_process 处理中
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'subNodeState'?: string;
    /**
     * 创建时间-开始
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'createAtBegin'?: number;
    /**
     * 运输模式(SP/LTL/TL)
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'transportModel'?: string;
    /**
     * 实际到达日期-结束
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'actualDeliveryTimeMsEnd'?: number;
    /**
     * 实际到达日期-开始
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'actualDeliveryTimeMsBegin'?: number;
    /**
     * 交货日期 - 结束
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'carrierRequestedDeliveryDateEnd'?: number;
    /**
     * 交货日期 - 开始
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentListReqModel
     */
    'carrierRequestedDeliveryDateBegin'?: number;
}

