/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 列表导出请求
 * @export
 * @interface ShipmentWebCommonAmzDfShipmentExportReqModel
 */
export interface ShipmentWebCommonAmzDfShipmentExportReqModel {
    /**
     * arn/DF订单号
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'arn'?: string;
    /**
     * asn
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'asn'?: string;
    /**
     * ARN/ASN
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'arsn'?: string;
    /**
     * 预计提货时间-结束
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'frdEnd'?: number;
    /**
     * sa订单
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'saPoNo'?: string;
    /**
     * 亚马逊采购订单号
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'amzPoNo'?: string;
    /**
     * VCPO/DF订单号
     * @type {Array<string>}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'arnList'?: Array<string>;
    /**
     * 产品名称/ASIN/sSku
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'keyword'?: string;
    /**
     * 预计提货时间-开始
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'frdBegin'?: number;
    /**
     * 公司id
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'companyId'?: number;
    /**
     * 主状态：processing 处理中;pending_pick_up 待取件; pending_sync 待同步ASN; in_transport 在途中; finished 已交货; canceled 已取消
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'mainState'?: string;
    /**
     * 创建时间-结束
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'createAtEnd'?: number;
    /**
     * 发货仓库
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'storageCode'?: string;
    /**
     * VCPO/DF物流单号
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'shipmentCode'?: string;
    /**
     * 子节点状态：none 无任务，in_process 处理中
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'subNodeState'?: string;
    /**
     * 创建时间-开始
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'createAtBegin'?: number;
    /**
     * 站点
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'platformRegion'?: string;
    /**
     * 实际发货日期-结束
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'actualPickupDateMsEnd'?: number;
    /**
     * 到达日期-结束
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'actualDeliveryTimeMsEnd'?: number;
    /**
     * 实际发货日期-开始
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'actualPickupDateMsBegin'?: number;
    /**
     * 到达日期-开始
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentExportReqModel
     */
    'actualDeliveryTimeMsBegin'?: number;
}

