/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 物流列表请求
 * @export
 * @interface ShipmentWebSevcAmzShipmentLogisticsListReqModel
 */
export interface ShipmentWebSevcAmzShipmentLogisticsListReqModel {
    /**
     * 
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsListReqModel
     */
    'userId'?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsListReqModel
     */
    'varMap'?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsListReqModel
     */
    'businessId'?: string;
    /**
     * VCPO物流单号
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsListReqModel
     */
    'shipmentCode': string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsListReqModel
     */
    'idempotenceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsListReqModel
     */
    'messageTypeEnum'?: ShipmentWebSevcAmzShipmentLogisticsListReqModelMessageTypeEnumEnum;
}

export const ShipmentWebSevcAmzShipmentLogisticsListReqModelMessageTypeEnumEnum = {
    Sms: 'SMS',
    Email: 'EMAIL',
    Feishu: 'FEISHU',
    Dingtalk: 'DINGTALK',
    Dingtalkwithrobot: 'DINGTALKWITHROBOT',
    Inbox: 'INBOX',
    Telephone: 'TELEPHONE'
} as const;

export type ShipmentWebSevcAmzShipmentLogisticsListReqModelMessageTypeEnumEnum = typeof ShipmentWebSevcAmzShipmentLogisticsListReqModelMessageTypeEnumEnum[keyof typeof ShipmentWebSevcAmzShipmentLogisticsListReqModelMessageTypeEnumEnum];


