/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 详情请求
 * @export
 * @interface ShipmentWebSevcAmzShipmentDetailReqModel
 */
export interface ShipmentWebSevcAmzShipmentDetailReqModel {
    /**
     * id
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentDetailReqModel
     */
    'id': number;
}

