/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 运单号导出请求
 * @export
 * @interface ShipmentWebAmzShipmentLogisticsExportReqModel
 */
export interface ShipmentWebAmzShipmentLogisticsExportReqModel {
    /**
     * 
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'arsn'?: string;
    /**
     * 预计提货时间-结束
     * @type {number}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'frdEnd'?: number;
    /**
     * sa订单
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'saPoNo'?: string;
    /**
     * 亚马逊采购订单号
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'amzPoNo'?: string;
    /**
     * VCPO/DF订单号
     * @type {Array<string>}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'arnList'?: Array<string>;
    /**
     * 承运商
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'carrier'?: string;
    /**
     * 产品名称/ASIN/sSku
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'keyword'?: string;
    /**
     * 预计提货时间-开始
     * @type {number}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'frdBegin'?: number;
    /**
     * 公司
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'companyId'?: string;
    /**
     * 主状态：processing 处理中;pending_pick_up 待取件; pending_sync 待同步ASN; in_transport 在途中; finished 已交货; canceled 已取消
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'mainState'?: string;
    /**
     * VCPO物流列表/异常物流列表：abnormal 
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'exportType'?: string;
    /**
     * 创建时间-结束
     * @type {number}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'createAtEnd'?: number;
    /**
     * 发货仓库
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'storageCode'?: string;
    /**
     * VCPO物流单号
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'shipmentCode'?: string;
    /**
     * 创建时间-开始
     * @type {number}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'createAtBegin'?: number;
    /**
     * 运输模式(SP/LTL/TL)
     * @type {string}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'transportModel'?: string;
    /**
     * 实际发货日期-结束
     * @type {number}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'actualPickupDateMsEnd'?: number;
    /**
     * 到达日期-结束
     * @type {number}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'actualDeliveryTimeMsEnd'?: number;
    /**
     * 实际发货日期-开始
     * @type {number}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'actualPickupDateMsBegin'?: number;
    /**
     * 到达日期-开始
     * @type {number}
     * @memberof ShipmentWebAmzShipmentLogisticsExportReqModel
     */
    'actualDeliveryTimeMsBegin'?: number;
}

