/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ShipmentWebCommonVoAmzShipmentItemSimpleVOModel } from './shipment-web-common-vo-amz-shipment-item-simple-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { ShipmentWebCommonVoAmzShipmentVOModel } from './shipment-web-common-vo-amz-shipment-vomodel';

/**
 * amazon shipment数据结构
 * @export
 * @interface ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
 */
export interface ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel {
    /**
     * id
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'id': number;
    /**
     * arn/DF订单号
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'arn': string;
    /**
     * asn
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'asn': string;
    /**
     * 电子邮箱
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'email': string;
    /**
     * 联系电话
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'phone': string;
    /**
     * 运单号
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'proNo': string;
    /**
     * 收货地
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'shipTo': string;
    /**
     * 运输公司
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'carrier': string;
    /**
     * 出库类型
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'outType': string;
    /**
     * 发货地/发货仓库
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'shipFrom': string;
    /**
     * 总数量
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'totalQty': number;
    /**
     * 主状态：processing 处理中;pending_pick_up 待取件; pending_sync 待同步ASN; in_transport 在途中; finished 已交货; canceled 已取消
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'mainState': string;
    /**
     * 节点状态：pending_create_shipment: 创建shipment; pending_push_box_distribution: 向亚马逊提送箱数分配表；download_carton_label: 下载carton label; generate_shipping_list: 发货清单生成; sync_wms_shipment: 同步wms shipment; get_carrier_info: 获取carrier信息; download_shipping_label: shipping label/BOL下载; sync_carrier_to_wms: 向wms更新carrier信息; sync_wms_ex_info: 同步wms出库信息; pending_sync: 待同步ASN; in_transport: 在途中; finished: 已交付; canceled: 已取消;
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'nodeState': string;
    /**
     * 下单日期
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'orderOnMs': number;
    /**
     * vc账号
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'vendorCode': string;
    /**
     * 创建时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'createdAtMs': number;
    /**
     * 仓库编码
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'storageCode': string;
    /**
     * 仓库名称
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'storageName': string;
    /**
     * 总箱数
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'totalCarton': number;
    /**
     * 更新时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'updatedAtMs': number;
    /**
     * 取消原因
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'cancelReason': string;
    /**
     * 
     * @type {ShipmentWebCommonVoAmzShipmentVOModel}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'nextShipment': ShipmentWebCommonVoAmzShipmentVOModel;
    /**
     * VCPO物流单号/DF物流单号
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'shipmentCode': string;
    /**
     * 子节点状态：none 无任务，in_process 处理中
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'subNodeState': string;
    /**
     * 总托盘数，默认为0:unstacked
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'totalPallets': number;
    /**
     * 创建时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'createdTimeMs': number;
    /**
     * 更新时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'updatedTimeMs': number;
    /**
     * 运输模式 SP, LTL, TL
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'transportModel': string;
    /**
     * 实际提货时间/实际发货日期
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'actualPickupDateMs': number;
    /**
     * 实际到货时间/到达日期
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'actualDeliveryTimeMs': number;
    /**
     * 总体积
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'totalEstimatedVolume': number;
    /**
     * 总重量
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'totalEstimatedWeight': number;
    /**
     * 预计提货时间，即FRD
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'requestedPickupDateMs': number;
    /**
     * 预计到货时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'requestedDeliveryTimeMs': number;
    /**
     * 
     * @type {Array<ShipmentWebCommonVoAmzShipmentItemSimpleVOModel>}
     * @memberof ShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel
     */
    'amzShipmentItemSimpleVOList': Array<ShipmentWebCommonVoAmzShipmentItemSimpleVOModel>;
}

