/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ShipmentWebSevcAmzShipmentItemSimpleVOModel } from './shipment-web-sevc-amz-shipment-item-simple-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { ShipmentWebSevcAmzShipmentVOModel } from './shipment-web-sevc-amz-shipment-vomodel';

/**
 * amazon shipment简单数据结构
 * @export
 * @interface ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
 */
export interface ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel {
    /**
     * id
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'id': number;
    /**
     * arn
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'arn': string;
    /**
     * asn
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'asn': string;
    /**
     * 电子邮箱
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'email': string;
    /**
     * 联系电话
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'phone': string;
    /**
     * 运单号
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'proNo': string;
    /**
     * 收货地
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'shipTo': string;
    /**
     * 运输公司
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'carrier': string;
    /**
     * 出库类型
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'outType': string;
    /**
     * 发货地
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'shipFrom': string;
    /**
     * 总数量
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'totalQty': number;
    /**
     * 主状态: processing 处理中; pending_pick_up 待取件; in_transport 在途中; finished 已到达; canceled 已取消;
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'mainState': string;
    /**
     * 节点状态：pending_create_shipment 创建shipment;pending_push_box_distribution, 向亚马逊提送箱数分配表;pending_pick_up 待取件; sync_wms_shipment 同步wms shipment; download_carton_label 下载carton label; generate_shipping_list 发货清单生成; get_carrier_info 获取carrier信息;  download_shipping_label shippinglabel/BOL下载; sync_carrier_to_wms 向wms更新carrier信息; pending_sync 待同步ASN; in_transport 在途中; finished 已交付 canceled 已取消;
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'nodeState': string;
    /**
     * vc账号
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'vendorCode': string;
    /**
     * 总箱数
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'totalCarton': number;
    /**
     * 取消原因
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'cancelReason': string;
    /**
     * 
     * @type {ShipmentWebSevcAmzShipmentVOModel}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'nextShipment': ShipmentWebSevcAmzShipmentVOModel;
    /**
     * VCPO物流单号
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'shipmentCode': string;
    /**
     * 子节点状态：none 无任务，in_process 处理中
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'subNodeState': string;
    /**
     * 总托盘数，默认为0:unstacked
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'totalPallets': number;
    /**
     * 创建时间
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'createdTimeMs': number;
    /**
     * 更新时间
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'updatedTimeMs': number;
    /**
     * 运输模式 SP, LTL, TL
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'transportModel': string;
    /**
     * 实际提货时间
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'actualPickupDateMs': number;
    /**
     * 实际到货时间
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'actualDeliveryTimeMs': number;
    /**
     * 总体积
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'totalEstimatedVolume': number;
    /**
     * 总重量
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'totalEstimatedWeight': number;
    /**
     * 预计提货时间，即FRD
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'requestedPickupDateMs': number;
    /**
     * 预计到货时间
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'requestedDeliveryTimeMs': number;
    /**
     * 
     * @type {Array<ShipmentWebSevcAmzShipmentItemSimpleVOModel>}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'amzShipmentItemSimpleVOList': Array<ShipmentWebSevcAmzShipmentItemSimpleVOModel>;
    /**
     * 交货日期
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentWithSimpleItemsVOModel
     */
    'carrierRequestedDeliveryDate': number;
}

