/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * amazon shipment item数据结构
 * @export
 * @interface ShipmentWebCommonVoAmzShipmentItemVOModel
 */
export interface ShipmentWebCommonVoAmzShipmentItemVOModel {
    /**
     * id
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'id': number;
    /**
     * asin
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'asin': string;
    /**
     * ssku
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'ssku': string;
    /**
     * 标题/产品名称
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'title': string;
    /**
     * sa订单
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'saPoNo': string;
    /**
     * 亚马逊采购订单号
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'amzPoNo': string;
    /**
     * 品牌
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'brandName': string;
    /**
     * 公司id
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'companyId': number;
    /**
     * 1:PO订单；2:DI订单
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'orderType': string;
    /**
     * 发货窗口
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'shipWindow': string;
    /**
     * 订单日期，对应亚马逊订单orderon
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'orderDateMs': number;
    /**
     * 最晚发货时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'windowEndMs': number;
    /**
     * 出库数量/采购数量
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'outboundNums': number;
    /**
     * 有效期至，对应亚马逊订单expiry date
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'validUntilMs': number;
    /**
     * 创建时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'createdTimeMs': number;
    /**
     * 总箱数
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'outboundBoxes': number;
    /**
     * 更新时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'updatedTimeMs': number;
    /**
     * 最早发货时间
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'windowStartMs': number;
    /**
     * VCPO物流号
     * @type {string}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'shipmentAmzCode': string;
    /**
     * 总体积
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'totalEstimatedVolume': number;
    /**
     * 总重量
     * @type {number}
     * @memberof ShipmentWebCommonVoAmzShipmentItemVOModel
     */
    'totalEstimatedWeight': number;
}

