/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 详情请求
 * @export
 * @interface ShipmentWebCommonAmzDfShipmentDetailReqModel
 */
export interface ShipmentWebCommonAmzDfShipmentDetailReqModel {
    /**
     * id
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentDetailReqModel
     */
    'id'?: number;
    /**
     * 公司id
     * @type {number}
     * @memberof ShipmentWebCommonAmzDfShipmentDetailReqModel
     */
    'companyId'?: number;
    /**
     * shipmentCode
     * @type {string}
     * @memberof ShipmentWebCommonAmzDfShipmentDetailReqModel
     */
    'shipmentCode': string;
}

