/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * amazon shipment logistics数据结构
 * @export
 * @interface ShipmentWebSevcAmzShipmentLogisticsVOModel
 */
export interface ShipmentWebSevcAmzShipmentLogisticsVOModel {
    /**
     * id
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'id': number;
    /**
     * 运单号
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'proNo': string;
    /**
     * 是否到货
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'arrived': number;
    /**
     * 物流公司
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'carrier': string;
    /**
     * 公司id
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'companyId': number;
    /**
     * 到货日期
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'arrivedTimeMs': number;
    /**
     * 创建时间
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'createdTimeMs': number;
    /**
     * 物流信息
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'logisticsInfo': string;
    /**
     * 物流类型
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'logisticsType': number;
    /**
     * 更新时间
     * @type {number}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'updatedTimeMs': number;
    /**
     * VCPO物流号
     * @type {string}
     * @memberof ShipmentWebSevcAmzShipmentLogisticsVOModel
     */
    'shipmentAmzCode': string;
}

