/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 排序
 * @export
 * @interface SortQueryModel
 */
export interface SortQueryModel {
    /**
     * 需要排序的字段名
     * @type {string}
     * @memberof SortQueryModel
     */
    'column'?: string;
    /**
     * 正序 ascend| 倒序 descend
     * @type {string}
     * @memberof SortQueryModel
     */
    'sortType'?: string;
}

