/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SpotterMenuNavigationDomainVOModel
 */
export interface SpotterMenuNavigationDomainVOModel {
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'icon': string;
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'type': string;
    /**
     * 
     * @type {number}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'order': number;
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'indexKey': string;
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'nextCode': string;
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'activeIcon': string;
    /**
     * 
     * @type {string}
     * @memberof SpotterMenuNavigationDomainVOModel
     */
    'activePrefixPath': string;
}

