/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SskuItemParamModel
 */
export interface SskuItemParamModel {
    /**
     * ssku
     * @type {string}
     * @memberof SskuItemParamModel
     */
    'ssku'?: string;
    /**
     * 数量,skuPackage=true,代表打包后的数量
     * @type {number}
     * @memberof SskuItemParamModel
     */
    'count': number;
    /**
     * 宽
     * @type {number}
     * @memberof SskuItemParamModel
     */
    'width': number;
    /**
     * 高
     * @type {number}
     * @memberof SskuItemParamModel
     */
    'height': number;
    /**
     * 长
     * @type {number}
     * @memberof SskuItemParamModel
     */
    'length': number;
    /**
     * 重量
     * @type {number}
     * @memberof SskuItemParamModel
     */
    'weight': number;
    /**
     * 打包装的数量,skuPackage=true,此字段才会启用
     * @type {number}
     * @memberof SskuItemParamModel
     */
    'inPackageCount'?: number;
}

