/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 文件处理任务信息
 * @export
 * @interface StorageFileJobVOModel
 */
export interface StorageFileJobVOModel {
    /**
     * 
     * @type {string}
     * @memberof StorageFileJobVOModel
     */
    'bizCode': string;
    /**
     * 
     * @type {string}
     * @memberof StorageFileJobVOModel
     */
    'bizType': string;
    /**
     * 
     * @type {string}
     * @memberof StorageFileJobVOModel
     */
    'fileUrl': string;
    /**
     * 
     * @type {string}
     * @memberof StorageFileJobVOModel
     */
    'jobCode': string;
    /**
     * 
     * @type {string}
     * @memberof StorageFileJobVOModel
     */
    'message': string;
    /**
     * 
     * @type {number}
     * @memberof StorageFileJobVOModel
     */
    'operator': number;
    /**
     * 
     * @type {string}
     * @memberof StorageFileJobVOModel
     */
    'terminal': string;
    /**
     * 
     * @type {string}
     * @memberof StorageFileJobVOModel
     */
    'companyId': string;
    /**
     * 
     * @type {string}
     * @memberof StorageFileJobVOModel
     */
    'fileStatus': string;
    /**
     * 
     * @type {number}
     * @memberof StorageFileJobVOModel
     */
    'jobEndDate': number;
    /**
     * 
     * @type {number}
     * @memberof StorageFileJobVOModel
     */
    'jobStartDate': number;
}

