/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortQueryModel } from './sort-query-model';

/**
 * 轨迹追踪列表分页请求
 * @export
 * @interface TmsSevcTrackingTrackingPageRequestModel
 */
export interface TmsSevcTrackingTrackingPageRequestModel {
    /**
     * 履约单号
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'foNoList'?: Array<string>;
    /**
     * 展示条数
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'pageSize': number;
    /**
     * 
     * @type {SortQueryModel}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'sortQuery'?: SortQueryModel;
    /**
     * 状态
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'statusList'?: Array<string>;
    /**
     * 运输商
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'carrierList'?: Array<string>;
    /**
     * 当前页数
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'currentPage': number;
    /**
     * ssku/msku
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'keywordList'?: Array<string>;
    /**
     * 销售单号
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'orderCodeList'?: Array<string>;
    /**
     * 运输时长(1:0-15天 2:16-90天 3:90天以上)
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'transDuration'?: number;
    /**
     * 运输模式(SP/LTL/TL)
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'transTypeList'?: Array<string>;
    /**
     * 出库单号
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'outboundNoList'?: Array<string>;
    /**
     * 实际提货时间End
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'pickupTimeMsEnd'?: number;
    /**
     * 发货仓库
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'storageCodeList'?: Array<string>;
    /**
     * 实际到达日期End
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'arrivedTimeMsEnd'?: number;
    /**
     * 创建日期End
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'createdTimeMsEnd'?: number;
    /**
     * 出库类型
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'outboundTypeList'?: Array<string>;
    /**
     * 实际提货时间Start
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'pickupTimeMsStart'?: number;
    /**
     * 实际到达日期Start
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'arrivedTimeMsStart'?: number;
    /**
     * 创建日期Start
     * @type {number}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'createdTimeMsStart'?: number;
    /**
     * 追踪单号
     * @type {Array<string>}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'trackingNumberList'?: Array<string>;
    /**
     * 是否过滤空追踪单号
     * @type {boolean}
     * @memberof TmsSevcTrackingTrackingPageRequestModel
     */
    'trackingNumberNotNull'?: boolean;
}

