/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 物流商信息VO
 * @export
 * @interface TmsOpenCarrierVOModel
 */
export interface TmsOpenCarrierVOModel {
    /**
     * 主键id
     * @type {number}
     * @memberof TmsOpenCarrierVOModel
     */
    'id': number;
    /**
     * 状态：0-废弃 1-启用
     * @type {number}
     * @memberof TmsOpenCarrierVOModel
     */
    'status': number;
    /**
     * 物流商名称
     * @type {string}
     * @memberof TmsOpenCarrierVOModel
     */
    'carrier': string;
    /**
     * 承运商图标
     * @type {string}
     * @memberof TmsOpenCarrierVOModel
     */
    'iconUrl': string;
    /**
     * 物流商编码
     * @type {string}
     * @memberof TmsOpenCarrierVOModel
     */
    'carrierCode': string;
    /**
     * 创建时间
     * @type {number}
     * @memberof TmsOpenCarrierVOModel
     */
    'createdTimeMs': number;
    /**
     * 更新时间
     * @type {number}
     * @memberof TmsOpenCarrierVOModel
     */
    'updatedTimeMs': number;
    /**
     * 服务类型列表
     * @type {Array<string>}
     * @memberof TmsOpenCarrierVOModel
     */
    'carrierService': Array<string>;
}

