/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 备注信息
 * @export
 * @interface TmsRemarkModel
 */
export interface TmsRemarkModel {
    /**
     * 备注操作人
     * @type {string}
     * @memberof TmsRemarkModel
     */
    'operatorName'?: string;
    /**
     * 备注内容
     * @type {string}
     * @memberof TmsRemarkModel
     */
    'remarkContent'?: string;
    /**
     * 备注时间
     * @type {number}
     * @memberof TmsRemarkModel
     */
    'operatorTimeMs'?: number;
}

