/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 查询运费价格
 * @export
 * @interface TmsCommonLogisticsGetLogisticsPriceRequestModel
 */
export interface TmsCommonLogisticsGetLogisticsPriceRequestModel {
    /**
     * 单号
     * @type {string}
     * @memberof TmsCommonLogisticsGetLogisticsPriceRequestModel
     */
    'queryNo': string;
}

