/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TmsTrackingTrackingPageRequestModel } from './tms-tracking-tracking-page-request-model';

/**
 * 轨迹追踪导出请求
 * @export
 * @interface TmsTrackingTrackingExportRequestModel
 */
export interface TmsTrackingTrackingExportRequestModel {
    /**
     * 
     * @type {TmsTrackingTrackingPageRequestModel}
     * @memberof TmsTrackingTrackingExportRequestModel
     */
    'pageParam'?: TmsTrackingTrackingPageRequestModel;
    /**
     * 是否同步导出
     * @type {boolean}
     * @memberof TmsTrackingTrackingExportRequestModel
     */
    'syncExport'?: boolean;
    /**
     * 导出模版
     * @type {string}
     * @memberof TmsTrackingTrackingExportRequestModel
     */
    'excelTemplate'?: string;
}

