/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressInfoModel } from './address-info-model';
// May contain unused imports in some cases
// @ts-ignore
import { SskuItemParamModel } from './ssku-item-param-model';

/**
 * 运费询价请求V2
 * @export
 * @interface TmsCommonLogisticsAskLogisticsPriceRequestV2Model
 */
export interface TmsCommonLogisticsAskLogisticsPriceRequestV2Model {
    /**
     * sku信息
     * @type {Array<SskuItemParamModel>}
     * @memberof TmsCommonLogisticsAskLogisticsPriceRequestV2Model
     */
    'skuInfo': Array<SskuItemParamModel>;
    /**
     * 
     * @type {AddressInfoModel}
     * @memberof TmsCommonLogisticsAskLogisticsPriceRequestV2Model
     */
    'addressTo': AddressInfoModel;
    /**
     * sku是否已打包(按箱发货)
     * @type {boolean}
     * @memberof TmsCommonLogisticsAskLogisticsPriceRequestV2Model
     */
    'skuPackage': boolean;
    /**
     * 
     * @type {AddressInfoModel}
     * @memberof TmsCommonLogisticsAskLogisticsPriceRequestV2Model
     */
    'addressFrom': AddressInfoModel;
}

