/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 地址信息
 * @export
 * @interface TmsAddressModel
 */
export interface TmsAddressModel {
    /**
     * 电话
     * @type {string}
     * @memberof TmsAddressModel
     */
    'tel'?: string;
    /**
     * 邮编
     * @type {string}
     * @memberof TmsAddressModel
     */
    'zip'?: string;
    /**
     * 市
     * @type {string}
     * @memberof TmsAddressModel
     */
    'city'?: string;
    /**
     * email
     * @type {string}
     * @memberof TmsAddressModel
     */
    'email'?: string;
    /**
     * 州
     * @type {string}
     * @memberof TmsAddressModel
     */
    'state'?: string;
    /**
     * 国家
     * @type {string}
     * @memberof TmsAddressModel
     */
    'country'?: string;
    /**
     * 联系人
     * @type {string}
     * @memberof TmsAddressModel
     */
    'contacts'?: string;
    /**
     * 仓库编号
     * @type {string}
     * @memberof TmsAddressModel
     */
    'addressCode'?: string;
    /**
     * 详细地址，市，州省，邮编，国家
     * @type {string}
     * @memberof TmsAddressModel
     */
    'addressDetail'?: string;
    /**
     * 详细地址1
     * @type {string}
     * @memberof TmsAddressModel
     */
    'addressDetail1'?: string;
    /**
     * 详细地址2
     * @type {string}
     * @memberof TmsAddressModel
     */
    'addressDetail2'?: string;
    /**
     * 详细地址3
     * @type {string}
     * @memberof TmsAddressModel
     */
    'addressDetail3'?: string;
}

