/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddressInfoModel } from './address-info-model';
// May contain unused imports in some cases
// @ts-ignore
import { ParcelInfoParamModel } from './parcel-info-param-model';

/**
 * 运费询价请求
 * @export
 * @interface TmsCommonLogisticsAskLogisticsPriceRequestModel
 */
export interface TmsCommonLogisticsAskLogisticsPriceRequestModel {
    /**
     * 
     * @type {AddressInfoModel}
     * @memberof TmsCommonLogisticsAskLogisticsPriceRequestModel
     */
    'addressTo': AddressInfoModel;
    /**
     * 包裹信息
     * @type {Array<ParcelInfoParamModel>}
     * @memberof TmsCommonLogisticsAskLogisticsPriceRequestModel
     */
    'parcelInfo': Array<ParcelInfoParamModel>;
    /**
     * 
     * @type {AddressInfoModel}
     * @memberof TmsCommonLogisticsAskLogisticsPriceRequestModel
     */
    'addressFrom': AddressInfoModel;
}

