/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 物流明细
 * @export
 * @interface TmsTrackingRoutingModel
 */
export interface TmsTrackingRoutingModel {
    /**
     * 节点信息,location等拼接
     * @type {string}
     * @memberof TmsTrackingRoutingModel
     */
    'message'?: string;
    /**
     * 节点操作时间
     * @type {number}
     * @memberof TmsTrackingRoutingModel
     */
    'pointDateMs'?: number;
}

