/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TmsAddressModel } from './tms-address-model';
// May contain unused imports in some cases
// @ts-ignore
import { TmsOpenCarrierVOModel } from './tms-open-carrier-vomodel';

/**
 * 轨迹追踪列表数据
 * @export
 * @interface TmsSevcTrackingTrackingListVOModel
 */
export interface TmsSevcTrackingTrackingListVOModel {
    /**
     * id
     * @type {number}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'id': number;
    /**
     * msku
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'msku': string;
    /**
     * ssku
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'ssku': string;
    /**
     * 
     * @type {TmsAddressModel}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'addressTo': TmsAddressModel;
    /**
     * 销售单号
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'orderCode': string;
    /**
     * 运输模式
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'transType': string;
    /**
     * 最新一次备注
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'lastRemark': string;
    /**
     * 出库单号
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'outboundNo': string;
    /**
     * 
     * @type {TmsAddressModel}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'addressFrom': TmsAddressModel;
    /**
     * 
     * @type {TmsOpenCarrierVOModel}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'carrierInfo': TmsOpenCarrierVOModel;
    /**
     * 关闭时间
     * @type {number}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'closeTimeMs': number;
    /**
     * 创建时间
     * @type {number}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'createdAtMs': number;
    /**
     * 出库类型
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'outboundType': string;
    /**
     * 运输时长
     * @type {number}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'transDuration': number;
    /**
     * 追踪单号
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'trackingNumber': string;
    /**
     * 状态
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'trackingStatus': string;
    /**
     * 最新物流查询时间
     * @type {number}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'queryTrackingMs': number;
    /**
     * 最新物流动态信息
     * @type {string}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'lastLogisticsInfo': string;
    /**
     * 实际提货时间
     * @type {number}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'actualPickupTimeMs': number;
    /**
     * 实际到达时间
     * @type {number}
     * @memberof TmsSevcTrackingTrackingListVOModel
     */
    'actualArrivedTimeMs': number;
}

