/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 货币信息
 * @export
 * @interface UserCenterIamCurrencyVOModel
 */
export interface UserCenterIamCurrencyVOModel {
    /**
     * id
     * @type {number}
     * @memberof UserCenterIamCurrencyVOModel
     */
    'id': number;
    /**
     * 货币代码
     * @type {string}
     * @memberof UserCenterIamCurrencyVOModel
     */
    'currencyCode': string;
    /**
     * 货币名称
     * @type {string}
     * @memberof UserCenterIamCurrencyVOModel
     */
    'currencyName': string;
    /**
     * 货币英文名称
     * @type {string}
     * @memberof UserCenterIamCurrencyVOModel
     */
    'currencyEnName': string;
    /**
     * 货币符号
     * @type {string}
     * @memberof UserCenterIamCurrencyVOModel
     */
    'currencySymbol': string;
}

