/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 应用信息
 * @export
 * @interface UserCenterSsoAppInfoVOModel
 */
export interface UserCenterSsoAppInfoVOModel {
    /**
     * 应用ID
     * @type {string}
     * @memberof UserCenterSsoAppInfoVOModel
     */
    'id': string;
    /**
     * 应用URL
     * @type {string}
     * @memberof UserCenterSsoAppInfoVOModel
     */
    'url': string;
    /**
     * 应用编码
     * @type {string}
     * @memberof UserCenterSsoAppInfoVOModel
     */
    'code': string;
    /**
     * 应用LOGO
     * @type {string}
     * @memberof UserCenterSsoAppInfoVOModel
     */
    'logo': string;
    /**
     * 应用名称
     * @type {string}
     * @memberof UserCenterSsoAppInfoVOModel
     */
    'name': string;
}

