/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 渠道站点信息
 * @export
 * @interface UserCenterIamSiteTenantVOModel
 */
export interface UserCenterIamSiteTenantVOModel {
    /**
     * 渠道站点id
     * @type {string}
     * @memberof UserCenterIamSiteTenantVOModel
     */
    'id': string;
    /**
     * 渠道id
     * @type {string}
     * @memberof UserCenterIamSiteTenantVOModel
     */
    'platformId': string;
    /**
     * 渠道code
     * @type {string}
     * @memberof UserCenterIamSiteTenantVOModel
     */
    'platformCode': string;
    /**
     * 渠道站点编码
     * @type {string}
     * @memberof UserCenterIamSiteTenantVOModel
     */
    'siteTenantCode': string;
    /**
     * 渠道站点名称
     * @type {string}
     * @memberof UserCenterIamSiteTenantVOModel
     */
    'siteTenantName': string;
    /**
     * 站点id
     * @type {string}
     * @memberof UserCenterIamSiteTenantVOModel
     */
    'platformRegionId': string;
    /**
     * 站点code
     * @type {string}
     * @memberof UserCenterIamSiteTenantVOModel
     */
    'platformRegionCode': string;
    /**
     * 渠道站点简易编码
     * @type {string}
     * @memberof UserCenterIamSiteTenantVOModel
     */
    'siteTenantSimpleCode': string;
}

