/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ResourceTreeVOModel } from './resource-tree-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { UserCenterIamSiteTenantDetailsVOModel } from './user-center-iam-site-tenant-details-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { UserCenterSsoEtagInfoVOModel } from './user-center-sso-etag-info-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { UserCenterSsoRoleInfoVOModel } from './user-center-sso-role-info-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { UserCenterSsoSampleUserInfoVOModel } from './user-center-sso-sample-user-info-vomodel';
// May contain unused imports in some cases
// @ts-ignore
import { UserCenterSsoTenantInfoVOModel } from './user-center-sso-tenant-info-vomodel';

/**
 * 用户信息
 * @export
 * @interface UserCenterSsoUserInfoVOModel
 */
export interface UserCenterSsoUserInfoVOModel {
    /**
     * 
     * @type {UserCenterSsoEtagInfoVOModel}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'etagInfo': UserCenterSsoEtagInfoVOModel;
    /**
     * 资源ETAG
     * @type {string}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'menuEtag': string;
    /**
     * 角色ETAG
     * @type {string}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'roleEtag': string;
    /**
     * 角色信息
     * @type {Array<UserCenterSsoRoleInfoVOModel>}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'roleInfo': Array<UserCenterSsoRoleInfoVOModel>;
    /**
     * 
     * @type {UserCenterSsoSampleUserInfoVOModel}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'userInfo': UserCenterSsoSampleUserInfoVOModel;
    /**
     * 接口权限ETAG
     * @type {string}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'permitEtag': string;
    /**
     * 租户信息
     * @type {Array<UserCenterSsoTenantInfoVOModel>}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'tenantInfo': Array<UserCenterSsoTenantInfoVOModel>;
    /**
     * 渠道编码
     * @type {string}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'platformCode': string;
    /**
     * 资源信息
     * @type {Array<ResourceTreeVOModel>}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'resourceInfo': Array<ResourceTreeVOModel>;
    /**
     * 渠道站点编码
     * @type {string}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'siteTenantCode': string;
    /**
     * 
     * @type {UserCenterIamSiteTenantDetailsVOModel}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'siteTenantDetails': UserCenterIamSiteTenantDetailsVOModel;
    /**
     * 站点编码
     * @type {string}
     * @memberof UserCenterSsoUserInfoVOModel
     */
    'platformRegionCode': string;
}

