/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 简易用户信息
 * @export
 * @interface UserCenterSsoSampleUserInfoVOModel
 */
export interface UserCenterSsoSampleUserInfoVOModel {
    /**
     * 用户ID
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'id': string;
    /**
     * 姓名
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'name': string;
    /**
     * 邮箱
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'email': string;
    /**
     * 手机
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'phone': string;
    /**
     * 头像
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'avatar': string;
    /**
     * 租户ID
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'tenantId': string;
    /**
     * 账号ID
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'accountId': string;
    /**
     * 租户Code
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'tenantCode': string;
    /**
     * 租户名称
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'tenantName': string;
    /**
     * 国家代码
     * @type {string}
     * @memberof UserCenterSsoSampleUserInfoVOModel
     */
    'countryCode': string;
}

