/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserCenterIamCurrencyVOModel } from './user-center-iam-currency-vomodel';

/**
 * 渠道站点详情
 * @export
 * @interface UserCenterIamSiteTenantDetailsVOModel
 */
export interface UserCenterIamSiteTenantDetailsVOModel {
    /**
     * id
     * @type {number}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'id': number;
    /**
     * 
     * @type {UserCenterIamCurrencyVOModel}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'currency': UserCenterIamCurrencyVOModel;
    /**
     * 时区
     * @type {string}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'timeZone': string;
    /**
     * 渠道id
     * @type {number}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'platformId': number;
    /**
     * 渠道code
     * @type {string}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'platformCode': string;
    /**
     * 渠道站点编码
     * @type {string}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'siteTenantCode': string;
    /**
     * 渠道站点名称
     * @type {string}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'siteTenantName': string;
    /**
     * 站点id
     * @type {number}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'platformRegionId': number;
    /**
     * 站点code
     * @type {string}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'platformRegionCode': string;
    /**
     * 渠道站点简易编码
     * @type {string}
     * @memberof UserCenterIamSiteTenantDetailsVOModel
     */
    'siteTenantSimpleCode': string;
}

