/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ETag 信息
 * @export
 * @interface UserCenterSsoEtagInfoVOModel
 */
export interface UserCenterSsoEtagInfoVOModel {
    /**
     * 角色ETAG
     * @type {string}
     * @memberof UserCenterSsoEtagInfoVOModel
     */
    'role': string;
    /**
     * 资源ETAG
     * @type {string}
     * @memberof UserCenterSsoEtagInfoVOModel
     */
    'resource': string;
}

