/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 角色信息
 * @export
 * @interface UserCenterSsoRoleInfoVOModel
 */
export interface UserCenterSsoRoleInfoVOModel {
    /**
     * 应用ID
     * @type {string}
     * @memberof UserCenterSsoRoleInfoVOModel
     */
    'id': string;
    /**
     * 应用编码
     * @type {string}
     * @memberof UserCenterSsoRoleInfoVOModel
     */
    'code': string;
    /**
     * 应用名称
     * @type {string}
     * @memberof UserCenterSsoRoleInfoVOModel
     */
    'name': string;
}

