/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 仓库和公司请求参数
 * @export
 * @interface WarehouseCommonBaseStorageCompanyQueryRequestModel
 */
export interface WarehouseCommonBaseStorageCompanyQueryRequestModel {
    /**
     * 仓库状态：(1弃用 0禁用)
     * @type {number}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    'status'?: number;
    /**
     * 模糊匹配（仓库编码，仓库中文名，仓库英文名）
     * @type {string}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    'keyword'?: string;
    /**
     * 公司id
     * @type {number}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    'companyId'?: number;
    /**
     * 仓库编码
     * @type {string}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    'storageCode'?: string;
    /**
     * 仓库类型：(1自发仓 2云仓 3自营仓)
     * @type {number}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    'storageType'?: number;
    /**
     * 模糊匹配仓库编码
     * @type {string}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    'likeStorageCode'?: string;
    /**
     * 仓库类型：(1自发仓 2云仓 3自营仓)
     * @type {Array<number>}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    'storageTypeList'?: Array<number>;
    /**
     * 其他字段--手动做单仓库标记，true-是过滤手动做单仓库，false-不过滤手动做单仓库
     * @type {boolean}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    'filterManualStorageFlag'?: boolean;
}

