/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 公司-仓库信息
 * @export
 * @interface WarehouseCommonBaseCompanyStorageVOModel
 */
export interface WarehouseCommonBaseCompanyStorageVOModel {
    /**
     * 公司id
     * @type {number}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'id': number;
    /**
     * 仓库所在城市
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'city': string;
    /**
     * 公司名称
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'name': string;
    /**
     * 仓库所在国家
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'state': string;
    /**
     * 仓库详细地址
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'address': string;
    /**
     * 仓库所在国家
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'country': string;
    /**
     * 邮编
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'postcode': string;
    /**
     * 公司编号
     * @type {number}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     * @deprecated
     */
    'companyId': number;
    /**
     * 仓库编码
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'storageCode': string;
    /**
     * 仓库名称
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'storageName': string;
    /**
     * 仓库类型
     * @type {number}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'storageType': number;
    /**
     * 公司编码
     * @type {string}
     * @memberof WarehouseCommonBaseCompanyStorageVOModel
     */
    'businessCode': string;
}

