/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 分页条件查询文件任务信息
 * @export
 * @interface WarehouseCommonBaseFileJobRequestModel
 */
export interface WarehouseCommonBaseFileJobRequestModel {
    /**
     * 状态
     * @type {string}
     * @memberof WarehouseCommonBaseFileJobRequestModel
     */
    'status'?: string;
    /**
     * 业务类型
     * @type {string}
     * @memberof WarehouseCommonBaseFileJobRequestModel
     */
    'bizType'?: string;
    /**
     * 展示条数
     * @type {number}
     * @memberof WarehouseCommonBaseFileJobRequestModel
     */
    'pageSize': number;
    /**
     * 当前页数
     * @type {number}
     * @memberof WarehouseCommonBaseFileJobRequestModel
     */
    'currentPage': number;
    /**
     * 任务开始时间-结束
     * @type {number}
     * @memberof WarehouseCommonBaseFileJobRequestModel
     */
    'jobStartDateMsEnd'?: number;
    /**
     * 任务开始时间-开始
     * @type {number}
     * @memberof WarehouseCommonBaseFileJobRequestModel
     */
    'jobStartDateMsBegin'?: number;
}

