/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import HttpClient, { HttpClientOptions } from './http-client'

export default class BaseSpotterApiSdk {
    protected httpClient!:  HttpClient
    constructor(httpOptions: HttpClientOptions) {
        this.httpClient = new HttpClient(httpOptions)
    }
    getHttpClient(){
        return this.httpClient
    }
}