/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { AddressInfoQueryRequestModel } from '../model';
// @ts-ignore
import { PredictionAddressReqModel } from '../model';
// @ts-ignore
import { ResponseResultListAddressVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOTmsOpenAddressInfoVOModel } from '../model';

/**
* Request parameters for getPredictionAddress operation in AddressApi.
* @export
* @interface AddressApiGetPredictionAddressRequest
* @extend {PredictionAddressReqModel}  
*/
export type AddressApiGetPredictionAddressRequest = PredictionAddressReqModel

/**
* Request parameters for pageAddressList operation in AddressApi.
* @export
* @interface AddressApiPageAddressListRequest
* @extend {AddressInfoQueryRequestModel}  
*/
export type AddressApiPageAddressListRequest = AddressInfoQueryRequestModel

/**
* AddressApi - object-oriented interface
* @export
* @class AddressApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterAddressApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 从谷歌获取地址预测信息
    * @summary 从谷歌获取地址预测信息
    * @param {AddressApiGetPredictionAddressRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AddressApi
    */
    async getPredictionAddress(requestParameters: AddressApiGetPredictionAddressRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListAddressVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-tms-web/open/address/getPredictionAddress',
            data: requestParameters
        })
    }
    /**
    * 收货地址列表
    * @summary 收货地址列表
    * @param {AddressApiPageAddressListRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AddressApi
    */
    async pageAddressList(requestParameters: AddressApiPageAddressListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOTmsOpenAddressInfoVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-tms-web/open/address/list',
            data: requestParameters
        })
    }
}
