/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { OrderOrderAmzBtrExportReqModel } from '../model';
// @ts-ignore
import { OrderPoAmzOrderPageReqSevcModel } from '../model';
// @ts-ignore
import { OrderPoOrderAmzQueryReqModel } from '../model';
// @ts-ignore
import { ResponseResultListOrderBboOrderAmzBboSevcVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderBboOrderAmzBboSevcVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';

/**
* Request parameters for bboExport operation in AmzOrderSevcApi.
* @export
* @interface AmzOrderSevcApiBboExportRequest
* @extend {OrderPoOrderAmzQueryReqModel}  
*/
export type AmzOrderSevcApiBboExportRequest = OrderPoOrderAmzQueryReqModel

/**
* Request parameters for btrExport operation in AmzOrderSevcApi.
* @export
* @interface AmzOrderSevcApiBtrExportRequest
* @extend {OrderOrderAmzBtrExportReqModel}  
*/
export type AmzOrderSevcApiBtrExportRequest = OrderOrderAmzBtrExportReqModel

/**
* Request parameters for listBboOrder operation in AmzOrderSevcApi.
* @export
* @interface AmzOrderSevcApiListBboOrderRequest
* @extend {OrderPoOrderAmzQueryReqModel}  
*/
export type AmzOrderSevcApiListBboOrderRequest = OrderPoOrderAmzQueryReqModel

/**
* Request parameters for pageBboOrder operation in AmzOrderSevcApi.
* @export
* @interface AmzOrderSevcApiPageBboOrderRequest
* @extend {OrderPoAmzOrderPageReqSevcModel}  
*/
export type AmzOrderSevcApiPageBboOrderRequest = OrderPoAmzOrderPageReqSevcModel

/**
* AmzOrderSevcApi - object-oriented interface
* @export
* @class AmzOrderSevcApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterAmzOrderSevcApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 导出数据的下单时间区间不超过30天
    * @summary bbo导出
    * @param {AmzOrderSevcApiBboExportRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderSevcApi
    */
    async bboExport(requestParameters: AmzOrderSevcApiBboExportRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/sevc/bbo/export',
            data: requestParameters
        })
    }
    /**
    * 亚马逊BTR订单导出
    * @summary 亚马逊BTR订单导出
    * @param {AmzOrderSevcApiBtrExportRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderSevcApi
    */
    async btrExport(requestParameters: AmzOrderSevcApiBtrExportRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/sevc/btr/export',
            data: requestParameters
        })
    }
    /**
    * 亚马逊BBO询盘订单列表
    * @summary 亚马逊BBO询盘订单列表
    * @param {AmzOrderSevcApiListBboOrderRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderSevcApi
    */
    async listBboOrder(requestParameters: AmzOrderSevcApiListBboOrderRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOrderBboOrderAmzBboSevcVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/sevc/list/bbo',
            data: requestParameters
        })
    }
    /**
    * 亚马逊BBO询盘订单分页
    * @summary 亚马逊BBO询盘订单分页
    * @param {AmzOrderSevcApiPageBboOrderRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderSevcApi
    */
    async pageBboOrder(requestParameters: AmzOrderSevcApiPageBboOrderRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderBboOrderAmzBboSevcVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/sevc/pageOrder/bbo',
            data: requestParameters
        })
    }
}
