/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { OrderBboOrderBboConfirmedReqModel } from '../model';
// @ts-ignore
import { OrderDfOrderAmzDfInventoryModifyReqModel } from '../model';
// @ts-ignore
import { OrderDfOrderAmzDfPageReqModel } from '../model';
// @ts-ignore
import { OrderDfOrderAmzDfQueryReqModel } from '../model';
// @ts-ignore
import { OrderPoAmzOrderPageReqGmeshModel } from '../model';
// @ts-ignore
import { ResponseResultBooleanModel } from '../model';
// @ts-ignore
import { ResponseResultOrderAmzBboStatisticsVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderDfOrderAmzDfInventoryModifyResultVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderDfOrderAmzDfStatisticVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderDfOrderAmzDfWithInventoryVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderDfOrderAmzDfInventoryModifyVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderDfOrderAmzDfInventoryVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderDfOrderAmzDfItemVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';

/**
* Request parameters for bboStatistics operation in AmzOrderApi.
* @export
* @interface AmzOrderApiBboStatisticsRequest
* @extend {OrderPoAmzOrderPageReqGmeshModel}  
*/
export type AmzOrderApiBboStatisticsRequest = OrderPoAmzOrderPageReqGmeshModel

/**
* Request parameters for confirmBbo operation in AmzOrderApi.
* @export
* @interface AmzOrderApiConfirmBboRequest
* @extend {Array<OrderBboOrderBboConfirmedReqModel>}  
*/
export type AmzOrderApiConfirmBboRequest = Array<OrderBboOrderBboConfirmedReqModel>

/**
* Request parameters for dfStatistic operation in AmzOrderApi.
* @export
* @interface AmzOrderApiDfStatisticRequest
* @extend {OrderDfOrderAmzDfQueryReqModel}  
*/
export type AmzOrderApiDfStatisticRequest = OrderDfOrderAmzDfQueryReqModel

/**
* Request parameters for exportDfInventory operation in AmzOrderApi.
* @export
* @interface AmzOrderApiExportDfInventoryRequest
* @extend {OrderDfOrderAmzDfQueryReqModel}  
*/
export type AmzOrderApiExportDfInventoryRequest = OrderDfOrderAmzDfQueryReqModel

/**
* Request parameters for exportDfOrder operation in AmzOrderApi.
* @export
* @interface AmzOrderApiExportDfOrderRequest
* @extend {OrderDfOrderAmzDfQueryReqModel}  
*/
export type AmzOrderApiExportDfOrderRequest = OrderDfOrderAmzDfQueryReqModel

/**
* Request parameters for listDfNew operation in AmzOrderApi.
* @export
* @interface AmzOrderApiListDfNewRequest
* @extend {OrderDfOrderAmzDfQueryReqModel}  
*/
export type AmzOrderApiListDfNewRequest = OrderDfOrderAmzDfQueryReqModel

/**
* Request parameters for modifyDfInventory operation in AmzOrderApi.
* @export
* @interface AmzOrderApiModifyDfInventoryRequest
* @extend {Array<OrderDfOrderAmzDfInventoryModifyReqModel>}  
*/
export type AmzOrderApiModifyDfInventoryRequest = Array<OrderDfOrderAmzDfInventoryModifyReqModel>

/**
* Request parameters for pageDfAll operation in AmzOrderApi.
* @export
* @interface AmzOrderApiPageDfAllRequest
* @extend {OrderDfOrderAmzDfPageReqModel}  
*/
export type AmzOrderApiPageDfAllRequest = OrderDfOrderAmzDfPageReqModel

/**
* Request parameters for pageDfInventory operation in AmzOrderApi.
* @export
* @interface AmzOrderApiPageDfInventoryRequest
* @extend {OrderDfOrderAmzDfPageReqModel}  
*/
export type AmzOrderApiPageDfInventoryRequest = OrderDfOrderAmzDfPageReqModel

/**
* Request parameters for pageDfInventoryModify operation in AmzOrderApi.
* @export
* @interface AmzOrderApiPageDfInventoryModifyRequest
* @extend {OrderDfOrderAmzDfPageReqModel}  
*/
export type AmzOrderApiPageDfInventoryModifyRequest = OrderDfOrderAmzDfPageReqModel

/**
* AmzOrderApi - object-oriented interface
* @export
* @class AmzOrderApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterAmzOrderApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 亚马逊BBO订单统计
    * @summary 亚马逊BBO订单统计
    * @param {AmzOrderApiBboStatisticsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async bboStatistics(requestParameters: AmzOrderApiBboStatisticsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderAmzBboStatisticsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/statistics/bbo',
            data: requestParameters
        })
    }
    /**
    * 修改bbo接单数量
    * @summary 修改bbo接单数量
    * @param {AmzOrderApiConfirmBboRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async confirmBbo(requestParameters: AmzOrderApiConfirmBboRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/bbo/confirm',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df统计
    * @summary 亚马逊df统计
    * @param {AmzOrderApiDfStatisticRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async dfStatistic(requestParameters: AmzOrderApiDfStatisticRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderDfOrderAmzDfStatisticVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/statistics/df',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df可售数量导出
    * @summary 亚马逊df可售数量导出
    * @param {AmzOrderApiExportDfInventoryRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async exportDfInventory(requestParameters: AmzOrderApiExportDfInventoryRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/export/df/inventory',
            data: requestParameters
        })
    }
    /**
    * 亚马逊DF订单列表导出
    * @summary 亚马逊DF订单列表导出
    * @param {AmzOrderApiExportDfOrderRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async exportDfOrder(requestParameters: AmzOrderApiExportDfOrderRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/export/df',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df待确认订单列表
    * @summary 亚马逊df待确认订单列表
    * @param {AmzOrderApiListDfNewRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async listDfNew(requestParameters: AmzOrderApiListDfNewRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderDfOrderAmzDfWithInventoryVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/list/df/new',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df可售数量修改
    * @summary 亚马逊df可售数量修改
    * @param {AmzOrderApiModifyDfInventoryRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async modifyDfInventory(requestParameters: AmzOrderApiModifyDfInventoryRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderDfOrderAmzDfInventoryModifyResultVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/modify/df/inventory',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df订单分页
    * @summary 亚马逊df订单分页
    * @param {AmzOrderApiPageDfAllRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async pageDfAll(requestParameters: AmzOrderApiPageDfAllRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderDfOrderAmzDfItemVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/page/df',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df可售数量分页
    * @summary 亚马逊df可售数量分页
    * @param {AmzOrderApiPageDfInventoryRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async pageDfInventory(requestParameters: AmzOrderApiPageDfInventoryRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderDfOrderAmzDfInventoryVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/page/df/inventory',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df可售数量修改分页
    * @summary 亚马逊df可售数量修改分页
    * @param {AmzOrderApiPageDfInventoryModifyRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof AmzOrderApi
    */
    async pageDfInventoryModify(requestParameters: AmzOrderApiPageDfInventoryModifyRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderDfOrderAmzDfInventoryModifyVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/page/df/inventory/modify',
            data: requestParameters
        })
    }
}
