/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { ResponseResultListTmsOpenCarrierVOModel } from '../model';

/**
* CarrierApi - object-oriented interface
* @export
* @class CarrierApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterCarrierApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 物流商列表
    * @summary 物流商列表
    * @param {*} [options] Override http request option.
    * @memberof CarrierApi
    */
    async list(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListTmsOpenCarrierVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-tms-web/open/carrier/list',
        })
    }
}
