/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { ResponseResultListResourceTreeVOModel } from '../model';
// @ts-ignore
import { ResponseResultListUserCenterSsoRoleInfoVOModel } from '../model';
// @ts-ignore
import { ResponseResultUserCenterSsoUserInfoVOModel } from '../model';

/**
* DevelopUserEndpointApi - object-oriented interface
* @export
* @class DevelopUserEndpointApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterDevelopUserEndpointApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 获取用户信息
    * @summary 获取用户信息
    * @param {*} [options] Override http request option.
    * @memberof DevelopUserEndpointApi
    */
    async getUserInfo(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultUserCenterSsoUserInfoVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-user-center/user/info',
        })
    }
    /**
    * 获取用户可访问资源
    * @summary 获取用户可访问资源
    * @param {*} [options] Override http request option.
    * @memberof DevelopUserEndpointApi
    */
    async getUserResources(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListResourceTreeVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-user-center/user/resources',
        })
    }
    /**
    * 获取用户可用角色
    * @summary 获取用户可用角色
    * @param {*} [options] Override http request option.
    * @memberof DevelopUserEndpointApi
    */
    async getUserRoles(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListUserCenterSsoRoleInfoVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-user-center/user/roles',
        })
    }
}
