/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { ResponseResultStorageStorageTemporaryCredentialVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';
// @ts-ignore
import { StorageFileDownloadSignerReqModel } from '../model';
// @ts-ignore
import { StorageStorageTemporaryCredentialReqModel } from '../model';

/**
* Request parameters for getSevcFileDownloadSigner operation in FileApi.
* @export
* @interface FileApiGetSevcFileDownloadSignerRequest
* @extend {StorageFileDownloadSignerReqModel}  
*/
export type FileApiGetSevcFileDownloadSignerRequest = StorageFileDownloadSignerReqModel

/**
* Request parameters for getSevcTemporaryCredential operation in FileApi.
* @export
* @interface FileApiGetSevcTemporaryCredentialRequest
* @extend {StorageStorageTemporaryCredentialReqModel}  
*/
export type FileApiGetSevcTemporaryCredentialRequest = StorageStorageTemporaryCredentialReqModel

/**
* FileApi - object-oriented interface
* @export
* @class FileApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterFileApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 获取下载文件的签名
    * @summary 获取文件下载的签名(sevc)
    * @param {FileApiGetSevcFileDownloadSignerRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof FileApi
    */
    async getSevcFileDownloadSigner(requestParameters: FileApiGetSevcFileDownloadSignerRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/file/sevc/download',
            data: requestParameters
        })
    }
    /**
    * 获取指定存储桶的临时密钥
    * @summary 获取指定存储桶的临时密钥(sevc)
    * @param {FileApiGetSevcTemporaryCredentialRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof FileApi
    */
    async getSevcTemporaryCredential(requestParameters: FileApiGetSevcTemporaryCredentialRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStorageStorageTemporaryCredentialVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/file/sevc/credential',
            data: requestParameters
        })
    }
}
