/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { OrderB2bConfirmReqModel } from '../model';
// @ts-ignore
import { OrderB2bFulfillDetailPageQueryModel } from '../model';
// @ts-ignore
import { OrderB2bSptOrderDetailQueryModel } from '../model';
// @ts-ignore
import { OrderB2bSptOrderPageQueryModel } from '../model';
// @ts-ignore
import { ResponseResultBooleanModel } from '../model';
// @ts-ignore
import { ResponseResultOrderB2bB2bStatisticsVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderB2bSptOrderDetailVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderB2bSptOrderDetailsWithIvtVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderB2bSptOrderPageVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';

/**
* Request parameters for batchConfirm operation in FulfillB2bOrderSevcApi.
* @export
* @interface FulfillB2bOrderSevcApiBatchConfirmRequest
* @extend {Array<OrderB2bConfirmReqModel>}  
*/
export type FulfillB2bOrderSevcApiBatchConfirmRequest = Array<OrderB2bConfirmReqModel>

/**
* Request parameters for batchSecondConfirm operation in FulfillB2bOrderSevcApi.
* @export
* @interface FulfillB2bOrderSevcApiBatchSecondConfirmRequest
* @extend {Array<OrderB2bConfirmReqModel>}  
*/
export type FulfillB2bOrderSevcApiBatchSecondConfirmRequest = Array<OrderB2bConfirmReqModel>

/**
* Request parameters for editInPending operation in FulfillB2bOrderSevcApi.
* @export
* @interface FulfillB2bOrderSevcApiEditInPendingRequest
* @extend {Array<OrderB2bConfirmReqModel>}  
*/
export type FulfillB2bOrderSevcApiEditInPendingRequest = Array<OrderB2bConfirmReqModel>

/**
* Request parameters for listSptOrderDetailsWithInventory operation in FulfillB2bOrderSevcApi.
* @export
* @interface FulfillB2bOrderSevcApiListSptOrderDetailsWithInventoryRequest
* @extend {OrderB2bSptOrderDetailQueryModel}  
*/
export type FulfillB2bOrderSevcApiListSptOrderDetailsWithInventoryRequest = OrderB2bSptOrderDetailQueryModel

/**
* Request parameters for quantityStatistics operation in FulfillB2bOrderSevcApi.
* @export
* @interface FulfillB2bOrderSevcApiQuantityStatisticsRequest
* @extend {OrderB2bFulfillDetailPageQueryModel}  
*/
export type FulfillB2bOrderSevcApiQuantityStatisticsRequest = OrderB2bFulfillDetailPageQueryModel

/**
* Request parameters for sptOrderDetail operation in FulfillB2bOrderSevcApi.
* @export
* @interface FulfillB2bOrderSevcApiSptOrderDetailRequest
* @extend {OrderB2bSptOrderDetailQueryModel}  
*/
export type FulfillB2bOrderSevcApiSptOrderDetailRequest = OrderB2bSptOrderDetailQueryModel

/**
* Request parameters for sptOrderPage operation in FulfillB2bOrderSevcApi.
* @export
* @interface FulfillB2bOrderSevcApiSptOrderPageRequest
* @extend {OrderB2bSptOrderPageQueryModel}  
*/
export type FulfillB2bOrderSevcApiSptOrderPageRequest = OrderB2bSptOrderPageQueryModel

/**
* Request parameters for sptOrderPageExport operation in FulfillB2bOrderSevcApi.
* @export
* @interface FulfillB2bOrderSevcApiSptOrderPageExportRequest
* @extend {OrderB2bSptOrderPageQueryModel}  
*/
export type FulfillB2bOrderSevcApiSptOrderPageExportRequest = OrderB2bSptOrderPageQueryModel

/**
* FulfillB2bOrderSevcApi - object-oriented interface
* @export
* @class FulfillB2bOrderSevcApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterFulfillB2bOrderSevcApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 批量确认
    * @summary 批量确认
    * @param {FulfillB2bOrderSevcApiBatchConfirmRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillB2bOrderSevcApi
    */
    async batchConfirm(requestParameters: FulfillB2bOrderSevcApiBatchConfirmRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/batchConfirm',
            data: requestParameters
        })
    }
    /**
    * 批量二次确认
    * @summary 批量二次确认
    * @param {FulfillB2bOrderSevcApiBatchSecondConfirmRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillB2bOrderSevcApi
    */
    async batchSecondConfirm(requestParameters: FulfillB2bOrderSevcApiBatchSecondConfirmRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/batchSecondConfirm',
            data: requestParameters
        })
    }
    /**
    * 待提交编辑
    * @summary 待提交编辑
    * @param {FulfillB2bOrderSevcApiEditInPendingRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillB2bOrderSevcApi
    */
    async editInPending(requestParameters: FulfillB2bOrderSevcApiEditInPendingRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/editInPending',
            data: requestParameters
        })
    }
    /**
    * 查询SA对应履约明细(带库存信息)
    * @summary 查询SA对应履约明细(带库存信息)
    * @param {FulfillB2bOrderSevcApiListSptOrderDetailsWithInventoryRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillB2bOrderSevcApi
    */
    async listSptOrderDetailsWithInventory(requestParameters: FulfillB2bOrderSevcApiListSptOrderDetailsWithInventoryRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderB2bSptOrderDetailsWithIvtVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/listSptOrderDetailsWithInventory',
            data: requestParameters
        })
    }
    /**
    * b2b订单接单率统计
    * @summary b2b订单接单率统计
    * @param {FulfillB2bOrderSevcApiQuantityStatisticsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof FulfillB2bOrderSevcApi
    */
    async quantityStatistics(requestParameters: FulfillB2bOrderSevcApiQuantityStatisticsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderB2bB2bStatisticsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/quantityStatistics',
            data: requestParameters
        })
    }
    /**
    * 详情(SA维度)
    * @summary 详情(SA维度)
    * @param {FulfillB2bOrderSevcApiSptOrderDetailRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillB2bOrderSevcApi
    */
    async sptOrderDetail(requestParameters: FulfillB2bOrderSevcApiSptOrderDetailRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderB2bSptOrderDetailVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/sptOrderDetail',
            data: requestParameters
        })
    }
    /**
    * 列表查询(SA维度)
    * @summary 列表查询(SA维度)
    * @param {FulfillB2bOrderSevcApiSptOrderPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillB2bOrderSevcApi
    */
    async sptOrderPage(requestParameters: FulfillB2bOrderSevcApiSptOrderPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderB2bSptOrderPageVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/sptOrderPage',
            data: requestParameters
        })
    }
    /**
    * 列表查询(SA维度)导出
    * @summary 列表查询(SA维度)导出
    * @param {FulfillB2bOrderSevcApiSptOrderPageExportRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillB2bOrderSevcApi
    */
    async sptOrderPageExport(requestParameters: FulfillB2bOrderSevcApiSptOrderPageExportRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/sptOrderPageExport',
            data: requestParameters
        })
    }
    /**
    * b2b订单统计
    * @summary b2b订单统计
    * @param {*} [options] Override http request option.
    * @memberof FulfillB2bOrderSevcApi
    */
    async statistics(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderB2bB2bStatisticsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/b2bOrder/sevc/statistics',
        })
    }
}
