/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { CreateBatchReqModel } from '../model';
// @ts-ignore
import { OrderMultichannelAllPageQueryModel } from '../model';
// @ts-ignore
import { OrderMultichannelBatchSaveAttachReqModel } from '../model';
// @ts-ignore
import { OrderMultichannelCancelFulfillDetailReqModel } from '../model';
// @ts-ignore
import { OrderMultichannelCancelPltOrderReqModel } from '../model';
// @ts-ignore
import { OrderMultichannelCreateReqModel } from '../model';
// @ts-ignore
import { OrderMultichannelDetailQueryReqModel } from '../model';
// @ts-ignore
import { OrderMultichannelEditReqModel } from '../model';
// @ts-ignore
import { OrderMultichannelExceptionPageQueryModel } from '../model';
// @ts-ignore
import { OrderMultichannelPendingPageQueryModel } from '../model';
// @ts-ignore
import { OrderMultichannelPreCheckAttachReqModel } from '../model';
// @ts-ignore
import { OrderMultichannelShipReqModel } from '../model';
// @ts-ignore
import { ProductPageQueryReqModel } from '../model';
// @ts-ignore
import { ResponseResultListOrderMultichannelAttachVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderMultichannelCreateOrEditResultVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderMultichannelDetailVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderMultichannelPreCheckAttachVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderMultichannelStatisticsVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderMultichannelMcFulfillDetailVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderMultichannelPendingPageVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderMultichannelProductVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';
// @ts-ignore
import { ResponseResultVoidModel } from '../model';

/**
* Request parameters for allPage operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiAllPageRequest
* @extend {OrderMultichannelAllPageQueryModel}  
*/
export type FulfillMcOrderApiAllPageRequest = OrderMultichannelAllPageQueryModel

/**
* Request parameters for allPageExport operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiAllPageExportRequest
* @extend {OrderMultichannelAllPageQueryModel}  
*/
export type FulfillMcOrderApiAllPageExportRequest = OrderMultichannelAllPageQueryModel

/**
* Request parameters for batchSaveAttach operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiBatchSaveAttachRequest
* @extend {OrderMultichannelBatchSaveAttachReqModel}  
*/
export type FulfillMcOrderApiBatchSaveAttachRequest = OrderMultichannelBatchSaveAttachReqModel

/**
* Request parameters for cancelFulfilDetail operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiCancelFulfilDetailRequest
* @extend {OrderMultichannelCancelFulfillDetailReqModel}  
*/
export type FulfillMcOrderApiCancelFulfilDetailRequest = OrderMultichannelCancelFulfillDetailReqModel

/**
* Request parameters for cancelPltOrder operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiCancelPltOrderRequest
* @extend {OrderMultichannelCancelPltOrderReqModel}  
*/
export type FulfillMcOrderApiCancelPltOrderRequest = OrderMultichannelCancelPltOrderReqModel

/**
* Request parameters for create operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiCreateRequest
* @extend {OrderMultichannelCreateReqModel}  
*/
export type FulfillMcOrderApiCreateRequest = OrderMultichannelCreateReqModel

/**
* Request parameters for createBatch operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiCreateBatchRequest
* @extend {CreateBatchReqModel}  
*/
export type FulfillMcOrderApiCreateBatchRequest = CreateBatchReqModel

/**
* Request parameters for detail operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiDetailRequest
* @extend {OrderMultichannelDetailQueryReqModel}  
*/
export type FulfillMcOrderApiDetailRequest = OrderMultichannelDetailQueryReqModel

/**
* Request parameters for edit operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiEditRequest
* @extend {OrderMultichannelEditReqModel}  
*/
export type FulfillMcOrderApiEditRequest = OrderMultichannelEditReqModel

/**
* Request parameters for exceptionPage operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiExceptionPageRequest
* @extend {OrderMultichannelExceptionPageQueryModel}  
*/
export type FulfillMcOrderApiExceptionPageRequest = OrderMultichannelExceptionPageQueryModel

/**
* Request parameters for listAttach operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiListAttachRequest
* @extend {OrderMultichannelDetailQueryReqModel}  
*/
export type FulfillMcOrderApiListAttachRequest = OrderMultichannelDetailQueryReqModel

/**
* Request parameters for pendingPage operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiPendingPageRequest
* @extend {OrderMultichannelPendingPageQueryModel}  
*/
export type FulfillMcOrderApiPendingPageRequest = OrderMultichannelPendingPageQueryModel

/**
* Request parameters for pendingPageExport operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiPendingPageExportRequest
* @extend {OrderMultichannelPendingPageQueryModel}  
*/
export type FulfillMcOrderApiPendingPageExportRequest = OrderMultichannelPendingPageQueryModel

/**
* Request parameters for preCheckAttach operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiPreCheckAttachRequest
* @extend {OrderMultichannelPreCheckAttachReqModel}  
*/
export type FulfillMcOrderApiPreCheckAttachRequest = OrderMultichannelPreCheckAttachReqModel

/**
* Request parameters for productPage operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiProductPageRequest
* @extend {ProductPageQueryReqModel}  
*/
export type FulfillMcOrderApiProductPageRequest = ProductPageQueryReqModel

/**
* Request parameters for ship operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiShipRequest
* @extend {OrderMultichannelShipReqModel}  
*/
export type FulfillMcOrderApiShipRequest = OrderMultichannelShipReqModel

/**
* Request parameters for statistics operation in FulfillMcOrderApi.
* @export
* @interface FulfillMcOrderApiStatisticsRequest
* @extend {object}  
*/
export type FulfillMcOrderApiStatisticsRequest = object

/**
* FulfillMcOrderApi - object-oriented interface
* @export
* @class FulfillMcOrderApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterFulfillMcOrderApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 订单全部分页(履约明细维度)
    * @summary 订单全部分页
    * @param {FulfillMcOrderApiAllPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async allPage(requestParameters: FulfillMcOrderApiAllPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderMultichannelMcFulfillDetailVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/allPage',
            data: requestParameters
        })
    }
    /**
    * 订单全部分页导出(履约明细维度)
    * @summary 订单全部分页导出
    * @param {FulfillMcOrderApiAllPageExportRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async allPageExport(requestParameters: FulfillMcOrderApiAllPageExportRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/allPageExport',
            data: requestParameters
        })
    }
    /**
    * 附件批量保存
    * @summary 附件批量保存
    * @param {FulfillMcOrderApiBatchSaveAttachRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async batchSaveAttach(requestParameters: FulfillMcOrderApiBatchSaveAttachRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultVoidModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/batchSaveAttach',
            data: requestParameters
        })
    }
    /**
    * 取消履约明细
    * @summary 取消履约明细
    * @param {FulfillMcOrderApiCancelFulfilDetailRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async cancelFulfilDetail(requestParameters: FulfillMcOrderApiCancelFulfilDetailRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultVoidModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/cancelFulfilDetail',
            data: requestParameters
        })
    }
    /**
    * 取消渠道订单
    * @summary 取消渠道订单
    * @param {FulfillMcOrderApiCancelPltOrderRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async cancelPltOrder(requestParameters: FulfillMcOrderApiCancelPltOrderRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultVoidModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/cancelPltOrder',
            data: requestParameters
        })
    }
    /**
    * 单条创建
    * @summary 单条创建
    * @param {FulfillMcOrderApiCreateRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async create(requestParameters: FulfillMcOrderApiCreateRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderMultichannelCreateOrEditResultVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/create',
            data: requestParameters
        })
    }
    /**
    * 批量创建
    * @summary 批量创建
    * @param {FulfillMcOrderApiCreateBatchRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async createBatch(requestParameters: FulfillMcOrderApiCreateBatchRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/createBatch',
            data: requestParameters
        })
    }
    /**
    * 订单详情
    * @summary 订单详情
    * @param {FulfillMcOrderApiDetailRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async detail(requestParameters: FulfillMcOrderApiDetailRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderMultichannelDetailVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/detail',
            data: requestParameters
        })
    }
    /**
    * 单条创建
    * @summary 单条编辑
    * @param {FulfillMcOrderApiEditRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async edit(requestParameters: FulfillMcOrderApiEditRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderMultichannelCreateOrEditResultVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/edit',
            data: requestParameters
        })
    }
    /**
    * 发货异常分页(履约明细维度)
    * @summary 发货异常分页
    * @param {FulfillMcOrderApiExceptionPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async exceptionPage(requestParameters: FulfillMcOrderApiExceptionPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderMultichannelMcFulfillDetailVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/exceptionPage',
            data: requestParameters
        })
    }
    /**
    * 查询附件:取订单和TMS的并集,优先选TMS
    * @summary 查询附件
    * @param {FulfillMcOrderApiListAttachRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async listAttach(requestParameters: FulfillMcOrderApiListAttachRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOrderMultichannelAttachVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/listAttach',
            data: requestParameters
        })
    }
    /**
    * 订单待处理分页(渠道订单维度)
    * @summary 订单待处理分页
    * @param {FulfillMcOrderApiPendingPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async pendingPage(requestParameters: FulfillMcOrderApiPendingPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderMultichannelPendingPageVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/pendingPage',
            data: requestParameters
        })
    }
    /**
    * 订单待处理导出
    * @summary 订单待处理导出
    * @param {FulfillMcOrderApiPendingPageExportRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async pendingPageExport(requestParameters: FulfillMcOrderApiPendingPageExportRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/pendingPageExport',
            data: requestParameters
        })
    }
    /**
    * 附件批量预校验
    * @summary 附件批量预校验
    * @param {FulfillMcOrderApiPreCheckAttachRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async preCheckAttach(requestParameters: FulfillMcOrderApiPreCheckAttachRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderMultichannelPreCheckAttachVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/preCheckAttach',
            data: requestParameters
        })
    }
    /**
    * 产品列表
    * @summary 产品列表
    * @param {FulfillMcOrderApiProductPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async productPage(requestParameters: FulfillMcOrderApiProductPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderMultichannelProductVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/productPage',
            data: requestParameters
        })
    }
    /**
    * 重新发货
    * @summary 重新发货
    * @param {FulfillMcOrderApiShipRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async ship(requestParameters: FulfillMcOrderApiShipRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultVoidModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/ship',
            data: requestParameters
        })
    }
    /**
    * 多渠道订单统计
    * @summary 多渠道订单统计
    * @param {FulfillMcOrderApiStatisticsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillMcOrderApi
    */
    async statistics(requestParameters: FulfillMcOrderApiStatisticsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderMultichannelStatisticsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/mcOrder/statistics',
            data: requestParameters
        })
    }
}
