/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { OrderFulfillmentFulfillmentCancelReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentConfirmPreCheckReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentConfirmReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentDetailReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentLackQueryReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentModifyReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentPageReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentQueryReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentShipReqModel } from '../model';
// @ts-ignore
import { ResponseResultBooleanModel } from '../model';
// @ts-ignore
import { ResponseResultListOrderFulfillmentAccountMapVOModel } from '../model';
// @ts-ignore
import { ResponseResultListOrderFulfillmentFulfillmentConfirmRespDetailVOModel } from '../model';
// @ts-ignore
import { ResponseResultListOrderFulfillmentFulfillmentLackVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderFulfillmentFulfillmentConfirmRespVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderFulfillmentFulfillmentDetailVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderFulfillmentFulfillmentStatisticsVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderFulfillmentFulfillmentVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';

/**
* Request parameters for cancel operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiCancelRequest
* @extend {OrderFulfillmentFulfillmentCancelReqModel}  
*/
export type FulfillRetailApiCancelRequest = OrderFulfillmentFulfillmentCancelReqModel

/**
* Request parameters for confirm operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiConfirmRequest
* @extend {Array<OrderFulfillmentFulfillmentConfirmReqModel>}  
*/
export type FulfillRetailApiConfirmRequest = Array<OrderFulfillmentFulfillmentConfirmReqModel>

/**
* Request parameters for confirmPreCheck operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiConfirmPreCheckRequest
* @extend {Array<OrderFulfillmentFulfillmentConfirmPreCheckReqModel>}  
*/
export type FulfillRetailApiConfirmPreCheckRequest = Array<OrderFulfillmentFulfillmentConfirmPreCheckReqModel>

/**
* Request parameters for detail operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiDetailRequest
* @extend {OrderFulfillmentFulfillmentDetailReqModel}  
*/
export type FulfillRetailApiDetailRequest = OrderFulfillmentFulfillmentDetailReqModel

/**
* Request parameters for exportDfLack operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiExportDfLackRequest
* @extend {OrderFulfillmentFulfillmentLackQueryReqModel}  
*/
export type FulfillRetailApiExportDfLackRequest = OrderFulfillmentFulfillmentLackQueryReqModel

/**
* Request parameters for exportExcel operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiExportExcelRequest
* @extend {OrderFulfillmentFulfillmentQueryReqModel}  
*/
export type FulfillRetailApiExportExcelRequest = OrderFulfillmentFulfillmentQueryReqModel

/**
* Request parameters for listDfLack operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiListDfLackRequest
* @extend {OrderFulfillmentFulfillmentLackQueryReqModel}  
*/
export type FulfillRetailApiListDfLackRequest = OrderFulfillmentFulfillmentLackQueryReqModel

/**
* Request parameters for modifyStorage operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiModifyStorageRequest
* @extend {OrderFulfillmentFulfillmentModifyReqModel}  
*/
export type FulfillRetailApiModifyStorageRequest = OrderFulfillmentFulfillmentModifyReqModel

/**
* Request parameters for page operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiPageRequest
* @extend {OrderFulfillmentFulfillmentPageReqModel}  
*/
export type FulfillRetailApiPageRequest = OrderFulfillmentFulfillmentPageReqModel

/**
* Request parameters for ship operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiShipRequest
* @extend {Array<OrderFulfillmentFulfillmentShipReqModel>}  
*/
export type FulfillRetailApiShipRequest = Array<OrderFulfillmentFulfillmentShipReqModel>

/**
* Request parameters for statistics operation in FulfillRetailApi.
* @export
* @interface FulfillRetailApiStatisticsRequest
* @extend {OrderFulfillmentFulfillmentQueryReqModel}  
*/
export type FulfillRetailApiStatisticsRequest = OrderFulfillmentFulfillmentQueryReqModel

/**
* FulfillRetailApi - object-oriented interface
* @export
* @class FulfillRetailApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterFulfillRetailApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 订单取消
    * @summary 订单取消
    * @param {FulfillRetailApiCancelRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async cancel(requestParameters: FulfillRetailApiCancelRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/cancel',
            data: requestParameters
        })
    }
    /**
    * 订单确认
    * @summary 订单确认
    * @param {FulfillRetailApiConfirmRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async confirm(requestParameters: FulfillRetailApiConfirmRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderFulfillmentFulfillmentConfirmRespVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/confirm',
            data: requestParameters
        })
    }
    /**
    * 订单确认预校验
    * @summary 订单确认预校验
    * @param {FulfillRetailApiConfirmPreCheckRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async confirmPreCheck(requestParameters: FulfillRetailApiConfirmPreCheckRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOrderFulfillmentFulfillmentConfirmRespDetailVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/confirm/preCheck',
            data: requestParameters
        })
    }
    /**
    * 订单详情
    * @summary 订单详情
    * @param {FulfillRetailApiDetailRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async detail(requestParameters: FulfillRetailApiDetailRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderFulfillmentFulfillmentDetailVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/detail',
            data: requestParameters
        })
    }
    /**
    * 订单缺货列表导出
    * @summary 订单缺货列表导出
    * @param {FulfillRetailApiExportDfLackRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async exportDfLack(requestParameters: FulfillRetailApiExportDfLackRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/lack/export',
            data: requestParameters
        })
    }
    /**
    * 订单导出
    * @summary 订单导出
    * @param {FulfillRetailApiExportExcelRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async exportExcel(requestParameters: FulfillRetailApiExportExcelRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/exportExcel',
            data: requestParameters
        })
    }
    /**
    * 账号列表
    * @summary 账号列表
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async listAccount(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOrderFulfillmentAccountMapVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/list/account',
        })
    }
    /**
    * 订单缺货列表
    * @summary 订单缺货列表
    * @param {FulfillRetailApiListDfLackRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async listDfLack(requestParameters: FulfillRetailApiListDfLackRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOrderFulfillmentFulfillmentLackVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/lack/page',
            data: requestParameters
        })
    }
    /**
    * 订单单条编辑
    * @summary 订单单条编辑
    * @param {FulfillRetailApiModifyStorageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async modifyStorage(requestParameters: FulfillRetailApiModifyStorageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/modifyStorage',
            data: requestParameters
        })
    }
    /**
    * 订单分页
    * @summary 订单分页
    * @param {FulfillRetailApiPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async page(requestParameters: FulfillRetailApiPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderFulfillmentFulfillmentVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/page',
            data: requestParameters
        })
    }
    /**
    * 订单发货
    * @summary 订单发货
    * @param {FulfillRetailApiShipRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async ship(requestParameters: FulfillRetailApiShipRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/ship',
            data: requestParameters
        })
    }
    /**
    * 订单统计
    * @summary 订单统计
    * @param {FulfillRetailApiStatisticsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof FulfillRetailApi
    */
    async statistics(requestParameters: FulfillRetailApiStatisticsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderFulfillmentFulfillmentStatisticsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/statistics',
            data: requestParameters
        })
    }
}
