/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { ResponseResultPageVOStorageFileJobVOModel } from '../model';
// @ts-ignore
import { StorageFileJobRequestModel } from '../model';

/**
* Request parameters for gmeshFileJobPage operation in GmeshStorageApi.
* @export
* @interface GmeshStorageApiGmeshFileJobPageRequest
* @extend {StorageFileJobRequestModel}  
*/
export type GmeshStorageApiGmeshFileJobPageRequest = StorageFileJobRequestModel

/**
* Request parameters for sevcFileJobPage operation in GmeshStorageApi.
* @export
* @interface GmeshStorageApiSevcFileJobPageRequest
* @extend {StorageFileJobRequestModel}  
*/
export type GmeshStorageApiSevcFileJobPageRequest = StorageFileJobRequestModel

/**
* GmeshStorageApi - object-oriented interface
* @export
* @class GmeshStorageApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterGmeshStorageApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 文件处理任务分页
    * @summary 文件处理任务分页
    * @param {GmeshStorageApiGmeshFileJobPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshStorageApi
    */
    async gmeshFileJobPage(requestParameters: GmeshStorageApiGmeshFileJobPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOStorageFileJobVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/file/job/page/gmesh',
            data: requestParameters
        })
    }
    /**
    * 文件处理任务分页
    * @summary 文件处理任务分页
    * @param {GmeshStorageApiSevcFileJobPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshStorageApi
    */
    async sevcFileJobPage(requestParameters: GmeshStorageApiSevcFileJobPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOStorageFileJobVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/file/job/page',
            data: requestParameters
        })
    }
}
