/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { OrderBboOrderBboConfirmedReqModel } from '../model';
// @ts-ignore
import { OrderDfOrderAmzDfInventoryModifyReqModel } from '../model';
// @ts-ignore
import { OrderDfOrderAmzDfPageReqModel } from '../model';
// @ts-ignore
import { OrderDfOrderAmzDfQueryReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentCancelReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentConfirmPreCheckReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentConfirmReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentDetailReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentLackQueryReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentModifyReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentPageReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentQueryReqModel } from '../model';
// @ts-ignore
import { OrderFulfillmentFulfillmentShipReqModel } from '../model';
// @ts-ignore
import { OrderPoAmzOrderPageReqGmeshModel } from '../model';
// @ts-ignore
import { ResponseResultBooleanModel } from '../model';
// @ts-ignore
import { ResponseResultGuardWebUserUserValidateVOModel } from '../model';
// @ts-ignore
import { ResponseResultListGuardWebRoleRoleListOneVOModel } from '../model';
// @ts-ignore
import { ResponseResultListOrderFulfillmentAccountMapVOModel } from '../model';
// @ts-ignore
import { ResponseResultListOrderFulfillmentFulfillmentConfirmRespDetailVOModel } from '../model';
// @ts-ignore
import { ResponseResultListOrderFulfillmentFulfillmentLackVOModel } from '../model';
// @ts-ignore
import { ResponseResultListPermitMenuVOModel } from '../model';
// @ts-ignore
import { ResponseResultListPermitSimpleOneVOModel } from '../model';
// @ts-ignore
import { ResponseResultListTmsOpenCarrierVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderAmzBboStatisticsVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderDfOrderAmzDfInventoryModifyResultVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderDfOrderAmzDfStatisticVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderDfOrderAmzDfWithInventoryVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderFulfillmentFulfillmentConfirmRespVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderFulfillmentFulfillmentDetailVOModel } from '../model';
// @ts-ignore
import { ResponseResultOrderFulfillmentFulfillmentStatisticsVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderDfOrderAmzDfInventoryModifyVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderDfOrderAmzDfInventoryVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderDfOrderAmzDfItemVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOrderFulfillmentFulfillmentVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel } from '../model';
// @ts-ignore
import { ResponseResultShipmentWebCommonVoAmzShipmentWithItemsVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';
// @ts-ignore
import { ShipmentWebCommonAmzDfShipmentDetailReqModel } from '../model';
// @ts-ignore
import { ShipmentWebCommonAmzDfShipmentExportReqModel } from '../model';
// @ts-ignore
import { ShipmentWebCommonAmzDfShipmentListReqModel } from '../model';

/**
* Request parameters for bboStatistics operation in GmeshApi.
* @export
* @interface GmeshApiBboStatisticsRequest
* @extend {OrderPoAmzOrderPageReqGmeshModel}  
*/
export type GmeshApiBboStatisticsRequest = OrderPoAmzOrderPageReqGmeshModel

/**
* Request parameters for cancel operation in GmeshApi.
* @export
* @interface GmeshApiCancelRequest
* @extend {OrderFulfillmentFulfillmentCancelReqModel}  
*/
export type GmeshApiCancelRequest = OrderFulfillmentFulfillmentCancelReqModel

/**
* Request parameters for confirm operation in GmeshApi.
* @export
* @interface GmeshApiConfirmRequest
* @extend {Array<OrderFulfillmentFulfillmentConfirmReqModel>}  
*/
export type GmeshApiConfirmRequest = Array<OrderFulfillmentFulfillmentConfirmReqModel>

/**
* Request parameters for confirmBbo operation in GmeshApi.
* @export
* @interface GmeshApiConfirmBboRequest
* @extend {Array<OrderBboOrderBboConfirmedReqModel>}  
*/
export type GmeshApiConfirmBboRequest = Array<OrderBboOrderBboConfirmedReqModel>

/**
* Request parameters for confirmPreCheck operation in GmeshApi.
* @export
* @interface GmeshApiConfirmPreCheckRequest
* @extend {Array<OrderFulfillmentFulfillmentConfirmPreCheckReqModel>}  
*/
export type GmeshApiConfirmPreCheckRequest = Array<OrderFulfillmentFulfillmentConfirmPreCheckReqModel>

/**
* Request parameters for detail operation in GmeshApi.
* @export
* @interface GmeshApiDetailRequest
* @extend {OrderFulfillmentFulfillmentDetailReqModel}  
*/
export type GmeshApiDetailRequest = OrderFulfillmentFulfillmentDetailReqModel

/**
* Request parameters for dfStatistic operation in GmeshApi.
* @export
* @interface GmeshApiDfStatisticRequest
* @extend {OrderDfOrderAmzDfQueryReqModel}  
*/
export type GmeshApiDfStatisticRequest = OrderDfOrderAmzDfQueryReqModel

/**
* Request parameters for exportDfInventory operation in GmeshApi.
* @export
* @interface GmeshApiExportDfInventoryRequest
* @extend {OrderDfOrderAmzDfQueryReqModel}  
*/
export type GmeshApiExportDfInventoryRequest = OrderDfOrderAmzDfQueryReqModel

/**
* Request parameters for exportDfLack operation in GmeshApi.
* @export
* @interface GmeshApiExportDfLackRequest
* @extend {OrderFulfillmentFulfillmentLackQueryReqModel}  
*/
export type GmeshApiExportDfLackRequest = OrderFulfillmentFulfillmentLackQueryReqModel

/**
* Request parameters for exportDfOrder operation in GmeshApi.
* @export
* @interface GmeshApiExportDfOrderRequest
* @extend {OrderDfOrderAmzDfQueryReqModel}  
*/
export type GmeshApiExportDfOrderRequest = OrderDfOrderAmzDfQueryReqModel

/**
* Request parameters for exportDfShipment operation in GmeshApi.
* @export
* @interface GmeshApiExportDfShipmentRequest
* @extend {ShipmentWebCommonAmzDfShipmentExportReqModel}  
*/
export type GmeshApiExportDfShipmentRequest = ShipmentWebCommonAmzDfShipmentExportReqModel

/**
* Request parameters for exportExcel operation in GmeshApi.
* @export
* @interface GmeshApiExportExcelRequest
* @extend {OrderFulfillmentFulfillmentQueryReqModel}  
*/
export type GmeshApiExportExcelRequest = OrderFulfillmentFulfillmentQueryReqModel

/**
* Request parameters for getDetails operation in GmeshApi.
* @export
* @interface GmeshApiGetDetailsRequest
* @extend {ShipmentWebCommonAmzDfShipmentDetailReqModel}  
*/
export type GmeshApiGetDetailsRequest = ShipmentWebCommonAmzDfShipmentDetailReqModel

/**
* Request parameters for getShipmentList operation in GmeshApi.
* @export
* @interface GmeshApiGetShipmentListRequest
* @extend {ShipmentWebCommonAmzDfShipmentListReqModel}  
*/
export type GmeshApiGetShipmentListRequest = ShipmentWebCommonAmzDfShipmentListReqModel

/**
* Request parameters for listDfLack operation in GmeshApi.
* @export
* @interface GmeshApiListDfLackRequest
* @extend {OrderFulfillmentFulfillmentLackQueryReqModel}  
*/
export type GmeshApiListDfLackRequest = OrderFulfillmentFulfillmentLackQueryReqModel

/**
* Request parameters for listDfNew operation in GmeshApi.
* @export
* @interface GmeshApiListDfNewRequest
* @extend {OrderDfOrderAmzDfQueryReqModel}  
*/
export type GmeshApiListDfNewRequest = OrderDfOrderAmzDfQueryReqModel

/**
* Request parameters for modifyDfInventory operation in GmeshApi.
* @export
* @interface GmeshApiModifyDfInventoryRequest
* @extend {Array<OrderDfOrderAmzDfInventoryModifyReqModel>}  
*/
export type GmeshApiModifyDfInventoryRequest = Array<OrderDfOrderAmzDfInventoryModifyReqModel>

/**
* Request parameters for modifyStorage operation in GmeshApi.
* @export
* @interface GmeshApiModifyStorageRequest
* @extend {OrderFulfillmentFulfillmentModifyReqModel}  
*/
export type GmeshApiModifyStorageRequest = OrderFulfillmentFulfillmentModifyReqModel

/**
* Request parameters for page operation in GmeshApi.
* @export
* @interface GmeshApiPageRequest
* @extend {OrderFulfillmentFulfillmentPageReqModel}  
*/
export type GmeshApiPageRequest = OrderFulfillmentFulfillmentPageReqModel

/**
* Request parameters for pageDfAll operation in GmeshApi.
* @export
* @interface GmeshApiPageDfAllRequest
* @extend {OrderDfOrderAmzDfPageReqModel}  
*/
export type GmeshApiPageDfAllRequest = OrderDfOrderAmzDfPageReqModel

/**
* Request parameters for pageDfInventory operation in GmeshApi.
* @export
* @interface GmeshApiPageDfInventoryRequest
* @extend {OrderDfOrderAmzDfPageReqModel}  
*/
export type GmeshApiPageDfInventoryRequest = OrderDfOrderAmzDfPageReqModel

/**
* Request parameters for pageDfInventoryModify operation in GmeshApi.
* @export
* @interface GmeshApiPageDfInventoryModifyRequest
* @extend {OrderDfOrderAmzDfPageReqModel}  
*/
export type GmeshApiPageDfInventoryModifyRequest = OrderDfOrderAmzDfPageReqModel

/**
* Request parameters for ship operation in GmeshApi.
* @export
* @interface GmeshApiShipRequest
* @extend {Array<OrderFulfillmentFulfillmentShipReqModel>}  
*/
export type GmeshApiShipRequest = Array<OrderFulfillmentFulfillmentShipReqModel>

/**
* Request parameters for statistics operation in GmeshApi.
* @export
* @interface GmeshApiStatisticsRequest
* @extend {OrderFulfillmentFulfillmentQueryReqModel}  
*/
export type GmeshApiStatisticsRequest = OrderFulfillmentFulfillmentQueryReqModel

/**
* GmeshApi - object-oriented interface
* @export
* @class GmeshApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterGmeshApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 亚马逊BBO订单统计
    * @summary 亚马逊BBO订单统计
    * @param {GmeshApiBboStatisticsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async bboStatistics(requestParameters: GmeshApiBboStatisticsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderAmzBboStatisticsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/statistics/bbo',
            data: requestParameters
        })
    }
    /**
    * 订单取消
    * @summary 订单取消
    * @param {GmeshApiCancelRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async cancel(requestParameters: GmeshApiCancelRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/cancel',
            data: requestParameters
        })
    }
    /**
    * 订单确认
    * @summary 订单确认
    * @param {GmeshApiConfirmRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async confirm(requestParameters: GmeshApiConfirmRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderFulfillmentFulfillmentConfirmRespVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/confirm',
            data: requestParameters
        })
    }
    /**
    * 修改bbo接单数量
    * @summary 修改bbo接单数量
    * @param {GmeshApiConfirmBboRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async confirmBbo(requestParameters: GmeshApiConfirmBboRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/bbo/confirm',
            data: requestParameters
        })
    }
    /**
    * 订单确认预校验
    * @summary 订单确认预校验
    * @param {GmeshApiConfirmPreCheckRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async confirmPreCheck(requestParameters: GmeshApiConfirmPreCheckRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOrderFulfillmentFulfillmentConfirmRespDetailVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/confirm/preCheck',
            data: requestParameters
        })
    }
    /**
    * 订单详情
    * @summary 订单详情
    * @param {GmeshApiDetailRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async detail(requestParameters: GmeshApiDetailRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderFulfillmentFulfillmentDetailVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/detail',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df统计
    * @summary 亚马逊df统计
    * @param {GmeshApiDfStatisticRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async dfStatistic(requestParameters: GmeshApiDfStatisticRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderDfOrderAmzDfStatisticVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/statistics/df',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df可售数量导出
    * @summary 亚马逊df可售数量导出
    * @param {GmeshApiExportDfInventoryRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async exportDfInventory(requestParameters: GmeshApiExportDfInventoryRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/export/df/inventory',
            data: requestParameters
        })
    }
    /**
    * 订单缺货列表导出
    * @summary 订单缺货列表导出
    * @param {GmeshApiExportDfLackRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async exportDfLack(requestParameters: GmeshApiExportDfLackRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/lack/export',
            data: requestParameters
        })
    }
    /**
    * 亚马逊DF订单列表导出
    * @summary 亚马逊DF订单列表导出
    * @param {GmeshApiExportDfOrderRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async exportDfOrder(requestParameters: GmeshApiExportDfOrderRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/export/df',
            data: requestParameters
        })
    }
    /**
    * 导出Excel
    * @summary 导出Excel
    * @param {GmeshApiExportDfShipmentRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof GmeshApi
    */
    async exportDfShipment(requestParameters: GmeshApiExportDfShipmentRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/shipment/df/amz/export',
            data: requestParameters
        })
    }
    /**
    * 订单导出
    * @summary 订单导出
    * @param {GmeshApiExportExcelRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async exportExcel(requestParameters: GmeshApiExportExcelRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/exportExcel',
            data: requestParameters
        })
    }
    /**
    * shipment详情(VCPO和DF)
    * @summary dfShipment详情列表
    * @param {GmeshApiGetDetailsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof GmeshApi
    */
    async getDetails(requestParameters: GmeshApiGetDetailsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultShipmentWebCommonVoAmzShipmentWithItemsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/shipment/df/amz/detailV2',
            data: requestParameters
        })
    }
    /**
    * shipment列表(VCPO和DF)
    * @summary shipment列表
    * @param {GmeshApiGetShipmentListRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof GmeshApi
    */
    async getShipmentList(requestParameters: GmeshApiGetShipmentListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOShipmentWebCommonVoAmzShipmentWithSimpleItemsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/shipment/df/amz/list',
            data: requestParameters
        })
    }
    /**
    * 物流商列表
    * @summary 物流商列表
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async list(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListTmsOpenCarrierVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-tms-web/open/carrier/list',
        })
    }
    /**
    * 账号列表
    * @summary 账号列表
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async listAccount(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOrderFulfillmentAccountMapVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/list/account',
        })
    }
    /**
    * 订单缺货列表
    * @summary 订单缺货列表
    * @param {GmeshApiListDfLackRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async listDfLack(requestParameters: GmeshApiListDfLackRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOrderFulfillmentFulfillmentLackVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/lack/page',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df待确认订单列表
    * @summary 亚马逊df待确认订单列表
    * @param {GmeshApiListDfNewRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async listDfNew(requestParameters: GmeshApiListDfNewRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderDfOrderAmzDfWithInventoryVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/list/df/new',
            data: requestParameters
        })
    }
    /**
    * 菜单信息
    * @summary 菜单信息
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof GmeshApi
    */
    async menus(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListPermitMenuVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-guard-web/validate/menus',
        })
    }
    /**
    * 亚马逊df可售数量修改
    * @summary 亚马逊df可售数量修改
    * @param {GmeshApiModifyDfInventoryRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async modifyDfInventory(requestParameters: GmeshApiModifyDfInventoryRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderDfOrderAmzDfInventoryModifyResultVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/modify/df/inventory',
            data: requestParameters
        })
    }
    /**
    * 订单单条编辑
    * @summary 订单单条编辑
    * @param {GmeshApiModifyStorageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async modifyStorage(requestParameters: GmeshApiModifyStorageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/modifyStorage',
            data: requestParameters
        })
    }
    /**
    * 订单分页
    * @summary 订单分页
    * @param {GmeshApiPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async page(requestParameters: GmeshApiPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderFulfillmentFulfillmentVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/page',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df订单分页
    * @summary 亚马逊df订单分页
    * @param {GmeshApiPageDfAllRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async pageDfAll(requestParameters: GmeshApiPageDfAllRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderDfOrderAmzDfItemVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/page/df',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df可售数量分页
    * @summary 亚马逊df可售数量分页
    * @param {GmeshApiPageDfInventoryRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async pageDfInventory(requestParameters: GmeshApiPageDfInventoryRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderDfOrderAmzDfInventoryVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/page/df/inventory',
            data: requestParameters
        })
    }
    /**
    * 亚马逊df可售数量修改分页
    * @summary 亚马逊df可售数量修改分页
    * @param {GmeshApiPageDfInventoryModifyRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async pageDfInventoryModify(requestParameters: GmeshApiPageDfInventoryModifyRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOrderDfOrderAmzDfInventoryModifyVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/amzOrder/page/df/inventory/modify',
            data: requestParameters
        })
    }
    /**
    * 权限信息
    * @summary 权限信息
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof GmeshApi
    */
    async permits(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListPermitSimpleOneVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-guard-web/validate/permit',
        })
    }
    /**
    * 角色信息
    * @summary 角色信息
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof GmeshApi
    */
    async roles(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListGuardWebRoleRoleListOneVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-guard-web/validate/roles',
        })
    }
    /**
    * 订单发货
    * @summary 订单发货
    * @param {GmeshApiShipRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async ship(requestParameters: GmeshApiShipRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultBooleanModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/ship',
            data: requestParameters
        })
    }
    /**
    * 订单统计
    * @summary 订单统计
    * @param {GmeshApiStatisticsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof GmeshApi
    */
    async statistics(requestParameters: GmeshApiStatisticsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultOrderFulfillmentFulfillmentStatisticsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-order-web/fulfill/retail/statistics',
            data: requestParameters
        })
    }
    /**
    * 登录验证V2
    * @summary 登录验证V2
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof GmeshApi
    */
    async validateV(options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultGuardWebUserUserValidateVOModel>({
            ...options,
            method: 'GET',
            url: '/spotter-guard-web/validate/v2',
        })
    }
}
