/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { OperationOperationSearchPageRequestModel } from '../model';
// @ts-ignore
import { OperationOperationSearchRequestModel } from '../model';
// @ts-ignore
import { ResponseResultListOperationLogVOModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOOperationLogVOModel } from '../model';

/**
* Request parameters for findList operation in OperationForeignApi.
* @export
* @interface OperationForeignApiFindListRequest
* @extend {OperationOperationSearchRequestModel}  
*/
export type OperationForeignApiFindListRequest = OperationOperationSearchRequestModel

/**
* Request parameters for findPage operation in OperationForeignApi.
* @export
* @interface OperationForeignApiFindPageRequest
* @extend {OperationOperationSearchPageRequestModel}  
*/
export type OperationForeignApiFindPageRequest = OperationOperationSearchPageRequestModel

/**
* OperationForeignApi - object-oriented interface
* @export
* @class OperationForeignApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterOperationForeignApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 业务id关联操作日志查询
    * @summary 业务id关联操作日志查询
    * @param {OperationForeignApiFindListRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof OperationForeignApi
    */
    async findList(requestParameters: OperationForeignApiFindListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListOperationLogVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-operation-log-web/log/biz/search/list',
            data: requestParameters
        })
    }
    /**
    * 业务id关联操作日志查询
    * @summary 业务id关联操作日志查询（分页）
    * @param {OperationForeignApiFindPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof OperationForeignApi
    */
    async findPage(requestParameters: OperationForeignApiFindPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOOperationLogVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-operation-log-web/log/biz/search/page',
            data: requestParameters
        })
    }
}
