/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { CooperationProductRProductSummaryPageSearchRequestModel } from '../model';
// @ts-ignore
import { ResponseResultPageVOCooperationProductRProductSummaryVOModel } from '../model';

/**
* Request parameters for summary operation in ProductApi.
* @export
* @interface ProductApiSummaryRequest
* @extend {CooperationProductRProductSummaryPageSearchRequestModel}  
*/
export type ProductApiSummaryRequest = CooperationProductRProductSummaryPageSearchRequestModel

/**
* ProductApi - object-oriented interface
* @export
* @class ProductApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterProductApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 产品概览搜索(romerx)，仅产品池使用
    * @summary 产品概览搜索(romerx)，仅产品池使用
    * @param {ProductApiSummaryRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof ProductApi
    */
    async summary(requestParameters: ProductApiSummaryRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOCooperationProductRProductSummaryVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-cooperation-web/product/romerx/summary',
            data: requestParameters
        })
    }
}
