/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { ResponseResultListShipmentWebSevcAmzShipmentLogisticsVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';
// @ts-ignore
import { ShipmentWebAmzShipmentLogisticsExportReqModel } from '../model';
// @ts-ignore
import { ShipmentWebSevcAmzShipmentLogisticsListReqModel } from '../model';

/**
* Request parameters for exportLogisticsDfList operation in SevcShipmentAmzLogisticsApi.
* @export
* @interface SevcShipmentAmzLogisticsApiExportLogisticsDfListRequest
* @extend {ShipmentWebAmzShipmentLogisticsExportReqModel}  
*/
export type SevcShipmentAmzLogisticsApiExportLogisticsDfListRequest = ShipmentWebAmzShipmentLogisticsExportReqModel

/**
* Request parameters for exportLogisticsList operation in SevcShipmentAmzLogisticsApi.
* @export
* @interface SevcShipmentAmzLogisticsApiExportLogisticsListRequest
* @extend {ShipmentWebAmzShipmentLogisticsExportReqModel}  
*/
export type SevcShipmentAmzLogisticsApiExportLogisticsListRequest = ShipmentWebAmzShipmentLogisticsExportReqModel

/**
* Request parameters for getShipmentLogisticsList operation in SevcShipmentAmzLogisticsApi.
* @export
* @interface SevcShipmentAmzLogisticsApiGetShipmentLogisticsListRequest
* @extend {ShipmentWebSevcAmzShipmentLogisticsListReqModel}  
*/
export type SevcShipmentAmzLogisticsApiGetShipmentLogisticsListRequest = ShipmentWebSevcAmzShipmentLogisticsListReqModel

/**
* SevcShipmentAmzLogisticsApi - object-oriented interface
* @export
* @class SevcShipmentAmzLogisticsApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterSevcShipmentAmzLogisticsApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * VCDF导出运单号
    * @summary VCDF导出运单号
    * @param {SevcShipmentAmzLogisticsApiExportLogisticsDfListRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof SevcShipmentAmzLogisticsApi
    */
    async exportLogisticsDfList(requestParameters: SevcShipmentAmzLogisticsApiExportLogisticsDfListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/sevc/shipment/amz/logistics/df/export',
            data: requestParameters
        })
    }
    /**
    * VCPO导出运单号
    * @summary VCPO导出运单号
    * @param {SevcShipmentAmzLogisticsApiExportLogisticsListRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof SevcShipmentAmzLogisticsApi
    */
    async exportLogisticsList(requestParameters: SevcShipmentAmzLogisticsApiExportLogisticsListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/sevc/shipment/amz/logistics/export',
            data: requestParameters
        })
    }
    /**
    * shipment logistics 列表
    * @summary shipment logistics 列表
    * @param {SevcShipmentAmzLogisticsApiGetShipmentLogisticsListRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof SevcShipmentAmzLogisticsApi
    */
    async getShipmentLogisticsList(requestParameters: SevcShipmentAmzLogisticsApiGetShipmentLogisticsListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListShipmentWebSevcAmzShipmentLogisticsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/sevc/shipment/amz/logistics/list',
            data: requestParameters
        })
    }
}
