/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { CooperationAmazonAccountAccountSearchRequestModel } from '../model';
// @ts-ignore
import { ResponseResultListRAccountSimpleVOModel } from '../model';

/**
* Request parameters for list operation in SevcAccountApi.
* @export
* @interface SevcAccountApiListRequest
* @extend {CooperationAmazonAccountAccountSearchRequestModel}  
*/
export type SevcAccountApiListRequest = CooperationAmazonAccountAccountSearchRequestModel

/**
* SevcAccountApi - object-oriented interface
* @export
* @class SevcAccountApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterSevcAccountApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 根据参数查询列表
    * @summary 根据参数查询亚马逊账号列表
    * @param {SevcAccountApiListRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof SevcAccountApi
    */
    async list(requestParameters: SevcAccountApiListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListRAccountSimpleVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-cooperation-web/amazon/account/sevc/list/search',
            data: requestParameters
        })
    }
}
