/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { ResponseResultPageVOShipmentWebSevcAmzShipmentWithSimpleItemsVOModel } from '../model';
// @ts-ignore
import { ResponseResultShipmentWebSevcAmzShipmentWithItemsVOModel } from '../model';
// @ts-ignore
import { ResponseResultStringModel } from '../model';
// @ts-ignore
import { ShipmentWebSevcAmzShipmentDetailReqModel } from '../model';
// @ts-ignore
import { ShipmentWebSevcAmzShipmentListReqModel } from '../model';

/**
* Request parameters for exportSevcShipment operation in SevcShipmentAmzApi.
* @export
* @interface SevcShipmentAmzApiExportSevcShipmentRequest
* @extend {ShipmentWebSevcAmzShipmentListReqModel}  
*/
export type SevcShipmentAmzApiExportSevcShipmentRequest = ShipmentWebSevcAmzShipmentListReqModel

/**
* Request parameters for getShipmentDetailWithItems operation in SevcShipmentAmzApi.
* @export
* @interface SevcShipmentAmzApiGetShipmentDetailWithItemsRequest
* @extend {ShipmentWebSevcAmzShipmentDetailReqModel}  
*/
export type SevcShipmentAmzApiGetShipmentDetailWithItemsRequest = ShipmentWebSevcAmzShipmentDetailReqModel

/**
* Request parameters for getShipmentListWithItems operation in SevcShipmentAmzApi.
* @export
* @interface SevcShipmentAmzApiGetShipmentListWithItemsRequest
* @extend {ShipmentWebSevcAmzShipmentListReqModel}  
*/
export type SevcShipmentAmzApiGetShipmentListWithItemsRequest = ShipmentWebSevcAmzShipmentListReqModel

/**
* SevcShipmentAmzApi - object-oriented interface
* @export
* @class SevcShipmentAmzApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterSevcShipmentAmzApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 导出物货运信息
    * @summary 导出货运信息
    * @param {SevcShipmentAmzApiExportSevcShipmentRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof SevcShipmentAmzApi
    */
    async exportSevcShipment(requestParameters: SevcShipmentAmzApiExportSevcShipmentRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultStringModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/sevc/shipment/amz/export',
            data: requestParameters
        })
    }
    /**
    * shipment详情
    * @summary shipment详情
    * @param {SevcShipmentAmzApiGetShipmentDetailWithItemsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof SevcShipmentAmzApi
    */
    async getShipmentDetailWithItems(requestParameters: SevcShipmentAmzApiGetShipmentDetailWithItemsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultShipmentWebSevcAmzShipmentWithItemsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/sevc/shipment/amz/detail',
            data: requestParameters
        })
    }
    /**
    * shipment列表
    * @summary shipment列表
    * @param {SevcShipmentAmzApiGetShipmentListWithItemsRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof SevcShipmentAmzApi
    */
    async getShipmentListWithItems(requestParameters: SevcShipmentAmzApiGetShipmentListWithItemsRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOShipmentWebSevcAmzShipmentWithSimpleItemsVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-shipment-web/sevc/shipment/amz/list',
            data: requestParameters
        })
    }
}
