/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { ResponseResultPageVOStorageFileJobVOModel } from '../model';
// @ts-ignore
import { StorageFileJobRequestModel } from '../model';

/**
* Request parameters for gmeshFileJobPage operation in StorageApi.
* @export
* @interface StorageApiGmeshFileJobPageRequest
* @extend {StorageFileJobRequestModel}  
*/
export type StorageApiGmeshFileJobPageRequest = StorageFileJobRequestModel

/**
* Request parameters for sevcFileJobPage operation in StorageApi.
* @export
* @interface StorageApiSevcFileJobPageRequest
* @extend {StorageFileJobRequestModel}  
*/
export type StorageApiSevcFileJobPageRequest = StorageFileJobRequestModel

/**
* StorageApi - object-oriented interface
* @export
* @class StorageApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterStorageApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 文件处理任务分页
    * @summary 文件处理任务分页
    * @param {StorageApiGmeshFileJobPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof StorageApi
    */
    async gmeshFileJobPage(requestParameters: StorageApiGmeshFileJobPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOStorageFileJobVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/file/job/page/gmesh',
            data: requestParameters
        })
    }
    /**
    * 文件处理任务分页
    * @summary 文件处理任务分页
    * @param {StorageApiSevcFileJobPageRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @memberof StorageApi
    */
    async sevcFileJobPage(requestParameters: StorageApiSevcFileJobPageRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultPageVOStorageFileJobVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-storage-web/file/job/page',
            data: requestParameters
        })
    }
}
