/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { HttpClientRequestConfig } from '../type';
// @ts-ignore
import * as axios from 'axios';
// @ts-ignore
import JSONBigInt from 'json-bigint';
// Some imports not used depending on template conditions
// @ts-ignore
import BaseSpotterApiSdk from '../base-api-sdk';
// @ts-ignore
import { ResponseResultListWarehouseCommonBaseCompanyStorageVOModel } from '../model';
// @ts-ignore
import { ResponseResultListWarehouseSevcBaseStorageInfoVOModel } from '../model';
// @ts-ignore
import { StorageInfoConditionReqModel } from '../model';
// @ts-ignore
import { WarehouseCommonBaseStorageCompanyQueryRequestModel } from '../model';

/**
* Request parameters for getStorageListByCondition operation in WarehouseApi.
* @export
* @interface WarehouseApiGetStorageListByConditionRequest
* @extend {StorageInfoConditionReqModel}  
*/
export type WarehouseApiGetStorageListByConditionRequest = StorageInfoConditionReqModel

/**
* Request parameters for storageList operation in WarehouseApi.
* @export
* @interface WarehouseApiStorageListRequest
* @extend {WarehouseCommonBaseStorageCompanyQueryRequestModel}  
*/
export type WarehouseApiStorageListRequest = WarehouseCommonBaseStorageCompanyQueryRequestModel

/**
* WarehouseApi - object-oriented interface
* @export
* @class WarehouseApi
* @extends {BaseSpotterApiSdk}
*/
export class SpotterWarehouseApiSdk extends BaseSpotterApiSdk {
    constructor(...baseApiSdkParams: ConstructorParameters<typeof BaseSpotterApiSdk>) {
        super(...baseApiSdkParams);
    }
    /**
    * 
    * @summary 条件查询仓库信息列表
    * @param {WarehouseApiGetStorageListByConditionRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof WarehouseApi
    */
    async getStorageListByCondition(requestParameters: WarehouseApiGetStorageListByConditionRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListWarehouseSevcBaseStorageInfoVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-warehouse-web/storage/sevc/condition/list',
            data: requestParameters
        })
    }
    /**
    * 获取仓库列表,可根据公司id查，也可模糊查询
    * @summary 获取仓库列表,可根据公司id查，也可模糊查询
    * @param {WarehouseApiStorageListRequest} requestParameters Request parameters.
    * @param {*} [options] Override http request option.
    * @deprecated
    * @memberof WarehouseApi
    */
    async storageList(requestParameters: WarehouseApiStorageListRequest, options?: HttpClientRequestConfig) {
        return this.httpClient.request<ResponseResultListWarehouseCommonBaseCompanyStorageVOModel>({
            ...options,
            method: 'POST',
            url: '/spotter-warehouse-web/company/storage/storage/list',
            data: requestParameters
        })
    }
}
