/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import { JobDetailInfoVoModel } from './job-detail-info-vo-model';

/**
 * 请求结果数据
 * @export
 * @interface ExportJobInfoVoModel
 */
export interface ExportJobInfoVoModel {
    /**
     * 任务凭证
     * @type {string}
     * @memberof ExportJobInfoVoModel
     */
    evidence: string;
    /**
     *
     * @type {JobDetailInfoVoModel}
     * @memberof ExportJobInfoVoModel
     */
    job: JobDetailInfoVoModel;
    /**
     * 本次请求相对于上次的变化
     * @type {number}
     * @memberof ExportJobInfoVoModel
     */
    changed: number;
    /**
     * 凭证关联的任务是否已全部完成
     * @type {boolean}
     * @memberof ExportJobInfoVoModel
     */
    allJobDone: boolean;
}
