/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 扩展属性
 * @export
 * @interface JobAttachReqModel
 */
export interface JobAttachReqModel {
    /**
     * 指定导出列名
     * @type {Array<string>}
     * @memberof JobAttachReqModel
     */
    columns?: Array<string>;
    /**
     * 自定义文件名变量
     * @type {{ [key: string]: string; }}
     * @memberof JobAttachReqModel
     */
    fileNameRenderVar?: { [key: string]: string };
}
