/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 凭证关联的任务信息
 * @export
 * @interface JobDetailInfoVoModel
 */
export interface JobDetailInfoVoModel {
    /**
     * 当前凭证关联的任务总数
     * @type {number}
     * @memberof JobDetailInfoVoModel
     */
    total: number;
    /**
     * 进行中的任务
     * @type {number}
     * @memberof JobDetailInfoVoModel
     */
    process: number;
    /**
     * 已完成的任务
     * @type {number}
     * @memberof JobDetailInfoVoModel
     */
    done: number;
}
