/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 结果列表
 * @export
 * @interface JobPageVOModel
 */
export interface JobPageVOModel {
    /**
     * 任务Id
     * @type {number}
     * @memberof JobPageVOModel
     */
    id: number;
    /**
     * 下载类型
     * @type {string}
     * @memberof JobPageVOModel
     */
    downloadType: string;
    /**
     * 创建时间
     * @type {number}
     * @memberof JobPageVOModel
     */
    createTime: number;
    /**
     * 文件名称
     * @type {string}
     * @memberof JobPageVOModel
     */
    fileName: string;
    /**
     * 文件大小
     * @type {number}
     * @memberof JobPageVOModel
     */
    fileSize: number;
    /**
     * 状态 0生成中;1已生成;2生成失败
     * @type {number}
     * @memberof JobPageVOModel
     */
    exportStatus: number;
    /**
     * 失败原因
     * @type {string}
     * @memberof JobPageVOModel
     */
    cause: string;
}
