/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface JobPageReqModel
 */
export interface JobPageReqModel {
    /**
     * 当前页数
     * @type {number}
     * @memberof JobPageReqModel
     */
    currentPage: number;
    /**
     * 展示条数
     * @type {number}
     * @memberof JobPageReqModel
     */
    pageSize: number;
    /**
     * 文件名称
     * @type {string}
     * @memberof JobPageReqModel
     */
    fileName?: string;
    /**
     * 下载类型
     * @type {Array<string>}
     * @memberof JobPageReqModel
     */
    downloadTypeList?: Array<string>;
    /**
     * 状态 0生成中;1已生成;2生成失败
     * @type {Array<number>}
     * @memberof JobPageReqModel
     */
    exportStatusList?: Array<number>;
    /**
     * 创建时间开始
     * @type {number}
     * @memberof JobPageReqModel
     */
    createTimeStart?: number;
    /**
     * 创建时间结束
     * @type {number}
     * @memberof JobPageReqModel
     */
    createTimeEnd?: number;
}
