/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { JobPageVOModel } from './job-page-vomodel';

/**
 * 请求结果数据
 * @export
 * @interface PageVOJobPageVOModel
 */
export interface PageVOJobPageVOModel {
    /**
     * 当前页
     * @type {number}
     * @memberof PageVOJobPageVOModel
     */
    currentPage: number;
    /**
     * 每页显示的总条数
     * @type {number}
     * @memberof PageVOJobPageVOModel
     */
    pageSize: number;
    /**
     * 总条数
     * @type {number}
     * @memberof PageVOJobPageVOModel
     */
    totalNum: number;
    /**
     * 是否有下一页,true=有，false=没有
     * @type {boolean}
     * @memberof PageVOJobPageVOModel
     */
    isMore: boolean;
    /**
     * 总页数
     * @type {number}
     * @memberof PageVOJobPageVOModel
     */
    totalPage: number;
    /**
     * 开始索引
     * @type {number}
     * @memberof PageVOJobPageVOModel
     */
    startIndex: number;
    /**
     * 结果列表
     * @type {Array<JobPageVOModel>}
     * @memberof PageVOJobPageVOModel
     */
    data: Array<JobPageVOModel>;
}
