/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { JobAttachReqModel } from './job-attach-req-model';

/**
 * 导出任务提交请求
 * @export
 * @interface StorageJobSubmitReqModel
 */
export interface StorageJobSubmitReqModel {
    /**
     * 凭证
     * @type {string}
     * @memberof StorageJobSubmitReqModel
     */
    evidence?: string;
    /**
     * 模版编码
     * @type {string}
     * @memberof StorageJobSubmitReqModel
     */
    templateCode: string;
    /**
     * 查询条件
     * @type {Record<string, any>}
     * @memberof StorageJobSubmitReqModel
     */
    condition?: Record<string, any>;
    /**
     *
     * @type {JobAttachReqModel}
     * @memberof StorageJobSubmitReqModel
     */
    attach?: JobAttachReqModel;
}
