/* tslint:disable */
/* eslint-disable */
/**
 * Api SwaggerJson
 * 此文件由Spotter DevTools生成，请勿手动修改
 *
 * The version of the OpenAPI document: 1732084753814
 * Contact: william.duan@spotterio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 请求结果数据
 * @export
 * @interface SupplierInfoVOModel
 */
export interface SupplierInfoVOModel {
    /**
     * 供应商id
     * @type {number}
     * @memberof SupplierInfoVOModel
     */
    id: number;
    /**
     * 供应商简称
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    name: string;
    /**
     * 供应商全称
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    fullCnName: string;
    /**
     * 公司规模
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    companyScale: string;
    /**
     * 公司规模Desc
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    companyScaleDesc: string;
    /**
     * 主体类型
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    companyType: string;
    /**
     * 主体类型desc
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    companyTypeDesc: string;
    /**
     * 供应商类型
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    supplierType: string;
    /**
     * 供应商类型Desc
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    supplierTypeDesc: string;
    /**
     * 统一社会信用代码
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    uniformSocialCreditCode: string;
    /**
     * CR code
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    crCode: string;
    /**
     * EIN code
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    einCode: string;
    /**
     * BR code
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    brCode: string;
    /**
     * 联系电话
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    contactPhone: string;
    /**
     * 联系邮箱
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    contactEmail: string;
    /**
     * 供应商等级
     * @type {number}
     * @memberof SupplierInfoVOModel
     */
    supplierLevel: number;
    /**
     * 供应商等级描述
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    supplierLevelDesc: string;
    /**
     * 供应商目标等级
     * @type {number}
     * @memberof SupplierInfoVOModel
     */
    targetSupplierLevel: number;
    /**
     * 供应商目标等级Desc
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    targetSupplierLevelDesc: string;
    /**
     * 公司编码
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    businessCode: string;
    /**
     * 业务类型
     * @type {string}
     * @memberof SupplierInfoVOModel
     */
    quotationAttr: string;
    /**
     * 渠道站点集合
     * @type {Array<string>}
     * @memberof SupplierInfoVOModel
     */
    channelSite: Array<string>;
}
