/* tslint:disable */
/* eslint-disable */
/**
 * Api SwaggerJson
 * 此文件由Spotter DevTools生成，请勿手动修改
 *
 * The version of the OpenAPI document: 1732084753814
 * Contact: william.duan@spotterio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SupplierBaseListSearchReqModel
 */
export interface SupplierBaseListSearchReqModel {
    /**
     * 关键字模糊查询-供应商简称、全称、公司编码
     * @type {string}
     * @memberof SupplierBaseListSearchReqModel
     */
    keyword?: string;
}
