/* tslint:disable */
/* eslint-disable */
/**
 * Api SwaggerJson
 * 此文件由Spotter DevTools生成，请勿手动修改
 *
 * The version of the OpenAPI document: 1732084753814
 * Contact: william.duan@spotterio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 供应商列表搜索参数
 * @export
 * @interface SupplierWebSupplierSupplierListSearchRequestModel
 */
export interface SupplierWebSupplierSupplierListSearchRequestModel {
    /**
     * 模糊搜索关键字
     * @type {string}
     * @memberof SupplierWebSupplierSupplierListSearchRequestModel
     */
    keyword?: string;
    /**
     * 供应状态
     * @type {number}
     * @memberof SupplierWebSupplierSupplierListSearchRequestModel
     */
    status?: number;
}
