/* tslint:disable */
/* eslint-disable */
/**
 * api
 * api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: key.chen@spotterio.com.cn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 仓库和公司请求参数
 * @export
 * @interface WarehouseCommonBaseStorageCompanyQueryRequestModel
 */
export interface WarehouseCommonBaseStorageCompanyQueryRequestModel {
    /**
     * 仓库编码
     * @type {string}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    storageCode?: string;
    /**
     * 公司id
     * @type {number}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    companyId?: number;
    /**
     * 模糊匹配仓库编码
     * @type {string}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    likeStorageCode?: string;
    /**
     * 模糊匹配（仓库编码，仓库中文名，仓库英文名）
     * @type {string}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    keyword?: string;
    /**
     * 仓库类型：(1自发仓 2云仓 3自营仓)
     * @type {number}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    storageType?: number;
    /**
     * 仓库类型：(1自发仓 2云仓 3自营仓)
     * @type {Array<number>}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    storageTypeList?: Array<number>;
    /**
     * 仓库状态：(1弃用 0禁用)
     * @type {number}
     * @memberof WarehouseCommonBaseStorageCompanyQueryRequestModel
     */
    status?: number;
}
